import { useMemo, useState } from "react";
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { useRouter } from "expo-router";

import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";
import { trpc } from "@/lib/trpc";

type Section = "overview" | "learners" | "safety" | "packs";

export default function OwnerControlScreen() {
  const colors = useColors();
  const router = useRouter();
  const [section, setSection] = useState<Section>("overview");
  const overview = trpc.ownerControl.overview.useQuery();
  const resolveReport = trpc.ownerControl.resolveReport.useMutation({ onSuccess: () => void overview.refetch() });
  const data = overview.data;
  const programRows = useMemo(() => Object.entries(data?.programDistribution ?? {}).sort(([, a], [, b]) => b - a), [data?.programDistribution]);

  const resolve = (reportId: number) => Alert.alert("Resolve safety report?", "This records the report as reviewed. It does not automatically remove learner content.", [{ text: "Cancel", style: "cancel" }, { text: "Mark resolved", onPress: () => resolveReport.mutate({ reportId }) }]);

  if (overview.isLoading) return <ScreenContainer className="items-center justify-center"><ActivityIndicator color={colors.primary} /><Text style={[styles.loading, { color: colors.muted }]}>Opening Owner Control Center…</Text></ScreenContainer>;
  if (overview.error || !data) return <ScreenContainer className="p-6 justify-center"><Text style={[styles.eyebrow, { color: colors.primary }]}>ROUNDS OWNER</Text><Text style={[styles.deniedTitle, { color: colors.foreground }]}>This space is private.</Text><Text style={[styles.deniedBody, { color: colors.muted }]}>Only the configured Rounds Owner account can open platform controls. Learner study access is unchanged.</Text><Pressable onPress={() => router.replace("/(tabs)" as never)} style={[styles.outline, { borderColor: colors.border }]}><Text style={{ color: colors.foreground, fontWeight: "900" }}>Return to Rounds</Text></Pressable></ScreenContainer>;

  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><ScrollView contentContainerStyle={styles.scroll} showsVerticalScrollIndicator={false}>
    <View style={styles.header}><View><Text style={[styles.eyebrow, { color: colors.primary }]}>SEPARATE ADMINISTRATIVE SURFACE</Text><Text style={[styles.title, { color: colors.foreground }]}>Owner Control Center</Text><Text style={[styles.sub, { color: colors.muted }]}>Private operational oversight for the Rounds learning platform.</Text></View><Pressable onPress={() => router.replace("/(tabs)" as never)} accessibilityRole="button"><Text style={[styles.returnLink, { color: colors.primary }]}>Learner app</Text></Pressable></View>
    <View style={[styles.nav, { borderColor: colors.border, backgroundColor: colors.surface }]}>{(["overview", "learners", "packs", "safety"] as Section[]).map((item) => <Pressable key={item} onPress={() => setSection(item)} accessibilityRole="tab" accessibilityState={{ selected: section === item }} style={[styles.tab, section === item && { backgroundColor: colors.primary }]}><Text style={[styles.tabText, { color: section === item ? colors.background : colors.foreground }]}>{item}</Text></Pressable>)}</View>
    {section === "overview" && <><View style={styles.metrics}>{[["Learners", data.metrics.learners], ["Academic profiles", data.metrics.academicProfiles], ["Private materials", data.metrics.studyMaterials], ["Open safety reports", data.metrics.openReports]].map(([label, value]) => <View key={String(label)} style={[styles.metric, { borderColor: colors.border, backgroundColor: colors.surface }]}><Text style={[styles.metricValue, { color: colors.foreground }]}>{value}</Text><Text style={[styles.metricLabel, { color: colors.muted }]}>{label}</Text></View>)}</View><View style={[styles.card, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Program distribution</Text>{programRows.length ? programRows.map(([program, count]) => <View key={program} style={styles.listRow}><Text style={[styles.listName, { color: colors.foreground }]}>{program.replace(/_/g, " ")}</Text><Text style={[styles.listMeta, { color: colors.muted }]}>{count} learner{count === 1 ? "" : "s"}</Text></View>) : <Text style={[styles.empty, { color: colors.muted }]}>No completed academic profiles yet.</Text>}</View></>}
    {section === "learners" && <View style={[styles.card, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Recent learners</Text><Text style={[styles.cardCopy, { color: colors.muted }]}>Minimal operational identity only. Private answers, recordings, local practice data, and PDF contents are excluded.</Text>{data.recentLearners.map((learner) => <View key={learner.id} style={[styles.learnerRow, { borderTopColor: colors.border }]}><View style={styles.grow}><Text style={[styles.listName, { color: colors.foreground }]}>{learner.name || "Learner"}</Text><Text style={[styles.listMeta, { color: colors.muted }]}>{learner.email || "No email"}</Text><Text style={[styles.listMeta, { color: colors.muted }]}>{learner.institutionName ? `${learner.institutionName} · ${learner.program?.replace(/_/g, " ")}` : "Academic profile pending"}</Text></View><Text style={[styles.date, { color: colors.muted }]}>{new Date(learner.createdAt).toLocaleDateString()}</Text></View>)}</View>}
    {section === "packs" && <View style={[styles.card, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Course-pack roadmap</Text><Text style={[styles.cardCopy, { color: colors.muted }]}>Only Nursing is active today. Planned packs remain visible for rollout planning but are not presented as learner-ready.</Text>{data.packs.map((pack) => <View key={pack.id} style={[styles.packRow, { borderTopColor: colors.border }]}><View style={styles.grow}><Text style={[styles.listName, { color: colors.foreground }]}>{pack.title}</Text><Text style={[styles.listMeta, { color: colors.muted }]}>{pack.detail}</Text></View><Text style={[styles.badge, { color: pack.status === "active" ? colors.success : colors.warning, borderColor: pack.status === "active" ? colors.success : colors.warning }]}>{pack.status}</Text></View>)}</View>}
    {section === "safety" && <View style={[styles.card, { borderColor: colors.border }]}><Text style={[styles.cardTitle, { color: colors.foreground }]}>Community safety review</Text><Text style={[styles.cardCopy, { color: colors.muted }]}>Review the report category and affected item, then mark reviewed reports as resolved. Resolution does not automatically delete content.</Text>{data.openReports.length ? data.openReports.map((report) => <View key={report.id} style={[styles.reportRow, { borderTopColor: colors.border }]}><View style={styles.grow}><Text style={[styles.listName, { color: colors.foreground }]}>{report.reason.replace(/_/g, " ")} report</Text><Text style={[styles.listMeta, { color: colors.muted }]}>{report.targetType} #{report.targetId} · {new Date(report.createdAt).toLocaleDateString()}</Text></View><Pressable onPress={() => resolve(report.id)} disabled={resolveReport.isPending} accessibilityRole="button" style={[styles.resolve, { borderColor: colors.primary }]}><Text style={[styles.resolveText, { color: colors.primary }]}>Resolve</Text></Pressable></View>) : <Text style={[styles.empty, { color: colors.muted }]}>There are no open community safety reports.</Text>}</View>}
  </ScrollView></ScreenContainer>;
}

const styles = StyleSheet.create({ scroll: { paddingTop: 18, paddingBottom: 40, gap: 18 }, header: { flexDirection: "row", justifyContent: "space-between", gap: 18, alignItems: "flex-start" }, eyebrow: { fontSize: 10, fontWeight: "900", letterSpacing: 1.6 }, title: { fontFamily: "Georgia", fontWeight: "700", fontSize: 30, marginTop: 4 }, sub: { fontSize: 14, lineHeight: 20, marginTop: 5, maxWidth: 420 }, returnLink: { fontSize: 13, fontWeight: "900", paddingTop: 4 }, nav: { flexDirection: "row", borderWidth: 1, borderRadius: 16, padding: 4, gap: 4, flexWrap: "wrap" }, tab: { borderRadius: 11, paddingVertical: 9, paddingHorizontal: 12 }, tabText: { fontSize: 12, fontWeight: "900", textTransform: "capitalize" }, metrics: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, metric: { width: "47%", minHeight: 104, borderWidth: 1, borderRadius: 17, padding: 15, justifyContent: "space-between" }, metricValue: { fontFamily: "Georgia", fontWeight: "700", fontSize: 30 }, metricLabel: { fontSize: 12, lineHeight: 17 }, card: { borderWidth: 1, borderRadius: 20, padding: 17, gap: 10 }, cardTitle: { fontSize: 17, fontWeight: "900" }, cardCopy: { fontSize: 13, lineHeight: 19 }, listRow: { flexDirection: "row", justifyContent: "space-between", paddingVertical: 12 }, listName: { fontSize: 14, fontWeight: "800", textTransform: "capitalize" }, listMeta: { fontSize: 12, lineHeight: 17, marginTop: 2 }, empty: { fontSize: 14, lineHeight: 20, paddingVertical: 10 }, learnerRow: { flexDirection: "row", paddingVertical: 13, borderTopWidth: 1, gap: 10 }, grow: { flex: 1 }, date: { fontSize: 11 }, packRow: { flexDirection: "row", paddingVertical: 13, borderTopWidth: 1, gap: 12, alignItems: "flex-start" }, badge: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 4, fontSize: 10, fontWeight: "900", textTransform: "uppercase" }, reportRow: { flexDirection: "row", paddingVertical: 13, borderTopWidth: 1, gap: 12, alignItems: "center" }, resolve: { borderWidth: 1, borderRadius: 10, paddingHorizontal: 10, paddingVertical: 8 }, resolveText: { fontSize: 12, fontWeight: "900" }, loading: { marginTop: 12, fontSize: 14 }, deniedTitle: { fontFamily: "Georgia", fontSize: 32, fontWeight: "700", marginTop: 7 }, deniedBody: { fontSize: 16, lineHeight: 24, marginTop: 9 }, outline: { alignSelf: "flex-start", marginTop: 22, borderWidth: 1, borderRadius: 13, paddingHorizontal: 14, paddingVertical: 10 } });
