import { useState } from "react";
import { Alert, Pressable, StyleSheet, Switch, Text, View } from "react-native";
import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Speech from "expo-speech";
import { ScreenContainer } from "@/components/screen-container";
import { useColors } from "@/hooks/use-colors";

export default function SettingsScreen() {
  const colors = useColors();
  const [auto, setAuto] = useState(false);
  const [rate, setRate] = useState(0.98);
  const reset = () => Alert.alert("Reset session?", "This removes locally stored practice results.", [{ text: "Cancel", style: "cancel" }, { text: "Reset", style: "destructive", onPress: () => AsyncStorage.removeItem("rounds.session.v1") }]);
  return <ScreenContainer className="px-5" edges={["top", "left", "right"]}><View style={styles.header}><Text style={[styles.eyebrow, { color: colors.primary }]}>PREFERENCES</Text><Text style={[styles.title, { color: colors.foreground }]}>Make it yours.</Text><Text style={[styles.sub, { color: colors.muted }]}>Tune practice for your study rhythm.</Text></View><View style={[styles.group, { backgroundColor: colors.surface, borderColor: colors.border }]}><SettingRow label="Auto-advance" description="Move to the next question after feedback" right={<Switch value={auto} onValueChange={setAuto} trackColor={{ false: colors.border, true: colors.primary }} thumbColor={colors.background} />} colors={colors} /><View style={[styles.divider, { backgroundColor: colors.border }]} /><SettingRow label="Speech rate" description={`${rate.toFixed(2)}x · slower can improve comprehension`} right={<View style={styles.rateRow}><Pressable onPress={() => setRate(Math.max(0.7, rate - 0.05))} style={[styles.rateButton, { borderColor: colors.border }]}><Text style={{ color: colors.foreground }}>−</Text></Pressable><Pressable onPress={() => setRate(Math.min(1.2, rate + 0.05))} style={[styles.rateButton, { borderColor: colors.border }]}><Text style={{ color: colors.foreground }}>+</Text></Pressable></View>} colors={colors} /></View><View style={[styles.info, { borderColor: colors.border }]}><Text style={[styles.infoTitle, { color: colors.foreground }]}>Voice practice</Text><Text style={[styles.infoText, { color: colors.muted }]}>Rounds speaks each question aloud. When microphone speech recognition is unavailable, type your answer in the Practice screen instead. On iOS, turn off Silent Mode to hear speech.</Text><Pressable onPress={() => Speech.speak("Rounds is ready for your next practice question.", { rate, language: "en-US" })}><Text style={[styles.test, { color: colors.primary }]}>Test voice</Text></Pressable></View><Pressable onPress={reset} style={[styles.reset, { borderColor: colors.error }]}><Text style={{ color: colors.error, fontWeight: "800" }}>Reset local session results</Text></Pressable><Text style={[styles.version, { color: colors.muted }]}>Rounds NCLEX · Voice-first nursing practice</Text></ScreenContainer>;
}
function SettingRow({ label, description, right, colors }: { label: string; description: string; right: React.ReactNode; colors: ReturnType<typeof useColors> }) { return <View style={styles.row}><View style={styles.copy}><Text style={[styles.label, { color: colors.foreground }]}>{label}</Text><Text style={[styles.description, { color: colors.muted }]}>{description}</Text></View>{right}</View>; }
const styles = StyleSheet.create({ header: { paddingTop: 18, gap: 5 }, eyebrow: { fontSize: 12, letterSpacing: 2.2, fontWeight: "800" }, title: { fontFamily: "Georgia", fontSize: 30, fontWeight: "700", marginTop: 3 }, sub: { fontSize: 14, lineHeight: 20 }, group: { marginTop: 24, borderWidth: 1, borderRadius: 20, paddingHorizontal: 16 }, row: { minHeight: 74, flexDirection: "row", alignItems: "center", gap: 12 }, copy: { flex: 1, gap: 4 }, label: { fontSize: 16, fontWeight: "800" }, description: { fontSize: 12, lineHeight: 17 }, divider: { height: 1 }, rateRow: { flexDirection: "row", gap: 7 }, rateButton: { width: 34, height: 34, borderWidth: 1, borderRadius: 10, alignItems: "center", justifyContent: "center", fontSize: 20 }, info: { marginTop: 18, borderWidth: 1, borderRadius: 20, padding: 17, gap: 8 }, infoTitle: { fontSize: 16, fontWeight: "800" }, infoText: { fontSize: 14, lineHeight: 21 }, test: { fontSize: 14, fontWeight: "800", marginTop: 2 }, reset: { marginTop: 18, minHeight: 48, borderWidth: 1, borderRadius: 16, alignItems: "center", justifyContent: "center" }, version: { textAlign: "center", fontSize: 12, marginTop: 18 } });
