export type CaseChainStep = {
  id: string;
  title: string;
  situation: string;
  prompt: string;
  options: string[];
  bestOption: string;
  explanation: string;
  /** Optional, finite next-step map. Any option without a target proceeds to the next listed step or reflection. */
  nextStepByOption?: Record<string, string>;
};

export type CourseCaseChain = {
  id: string;
  packId: string;
  title: string;
  eyebrow: string;
  summary: string;
  boundaryNote?: string;
  reflectionPrompt: string;
  steps: CaseChainStep[];
};

export const COURSE_CASE_CHAINS: CourseCaseChain[] = [
  {
    id: "foundation-source-plan",
    packId: "university-foundation-year",
    title: "Prepare a traceable source plan",
    eyebrow: "ACADEMIC FOUNDATIONS CASE",
    summary: "Move from useful notes to an attributable, submission-ready draft.",
    reflectionPrompt: "What source-checking habit will you use before your next draft?",
    steps: [
      {
        id: "capture",
        title: "Capture the source details",
        situation: "You have copied useful wording from an online article into a private draft. The article remains open, but no author, date, title, or link has been recorded.",
        prompt: "What should you do first?",
        options: ["Record the source details and mark the borrowed wording for quotation or careful paraphrase.", "Leave the text unchanged because the page is public.", "Delete the browser history so no one can find the page."],
        bestOption: "Record the source details and mark the borrowed wording for quotation or careful paraphrase.",
        explanation: "Traceable source details support accurate attribution and allow you to check the original context later.",
        nextStepByOption: { "Record the source details and mark the borrowed wording for quotation or careful paraphrase.": "review", "Leave the text unchanged because the page is public.": "capture-repair", "Delete the browser history so no one can find the page.": "capture-repair" },
      },
      {
        id: "capture-repair",
        title: "Restore traceability",
        situation: "Before sharing the draft, you notice that borrowed wording cannot be traced back to its source.",
        prompt: "What should happen before the draft moves forward?",
        options: ["Return to the original source, record its details, and clearly mark or revise the borrowed wording.", "Keep the wording because it is only for private study.", "Replace the source with an invented citation."],
        bestOption: "Return to the original source, record its details, and clearly mark or revise the borrowed wording.",
        explanation: "A short repair step restores accountability before the source is used in a draft.",
      },
      {
        id: "review",
        title: "Check the draft before sharing",
        situation: "The source details are now recorded and the wording has been revised. You are preparing to share the draft with a study partner for feedback.",
        prompt: "Which final check best supports responsible academic work?",
        options: ["Make it clear which ideas are yours and which are sourced, then ask for feedback on the argument.", "Remove every citation so the draft looks more original.", "Ask the study partner to submit the draft under their name."],
        bestOption: "Make it clear which ideas are yours and which are sourced, then ask for feedback on the argument.",
        explanation: "Clear attribution and a focused feedback request help improve the work without hiding the origin of ideas.",
      },
    ],
  },
  {
    id: "computing-accessible-events",
    packId: "computing-foundations",
    title: "Plan an accessible events page",
    eyebrow: "COMPUTING CASE",
    summary: "Turn user needs into requirements and an early test plan.",
    reflectionPrompt: "What user need would you put into the first version’s acceptance criteria?",
    steps: [
      {
        id: "requirements",
        title: "Set the requirements",
        situation: "A student team is planning a campus-events page. Users mention keyboard navigation and readable contrast, and the team has limited time for a first version.",
        prompt: "How should the team treat these needs?",
        options: ["Include them as requirements for the first version.", "Treat them as decoration to add after launch.", "Ask affected users to use another website."],
        bestOption: "Include them as requirements for the first version.",
        explanation: "Accessibility needs belong in the problem definition, not as optional decoration.",
        nextStepByOption: { "Include them as requirements for the first version.": "test", "Treat them as decoration to add after launch.": "requirements-repair", "Ask affected users to use another website.": "requirements-repair" },
      },
      {
        id: "test",
        title: "Choose an early test",
        situation: "The first page prototype now includes labeled controls and visible focus order. The team needs a short test before building more features.",
        prompt: "Which test is most useful now?",
        options: ["Navigate the page using a keyboard and check whether each control has a clear label and visible focus.", "Add more animations before any interaction test.", "Assume that a page is accessible if it works with a mouse."],
        bestOption: "Navigate the page using a keyboard and check whether each control has a clear label and visible focus.",
        explanation: "A small task-based test checks the specific requirements the team identified.",
      },
      {
        id: "requirements-repair",
        title: "Reframe the first version",
        situation: "The team has paused before building the page. It now needs to turn the reported needs into a workable first-version plan.",
        prompt: "What should the team add to its plan before moving forward?",
        options: ["Clear accessibility requirements and a small keyboard-navigation test.", "A promise to consider access only after all features are finished.", "A note that users should adapt to the design."],
        bestOption: "Clear accessibility requirements and a small keyboard-navigation test.",
        explanation: "The repair step reconnects the plan to the needs that were originally reported.",
      },
    ],
  },
  {
    id: "business-consent-campaign",
    packId: "business-foundations",
    title: "Plan a consent-aware campaign",
    eyebrow: "BUSINESS CASE",
    summary: "Use customer contact details consistently with their stated purpose.",
    boundaryNote: "This is a learning case, not legal advice.",
    reflectionPrompt: "What would you state clearly on a future sign-up form?",
    steps: [
      {
        id: "purpose",
        title: "Check the collection purpose",
        situation: "A team collected email addresses for event attendance. It now wants to send a separate promotional message about a new idea.",
        prompt: "What should the team do first?",
        options: ["Check the stated purpose and seek clear permission for the promotional use.", "Send the promotion because addresses were collected at an event.", "Publish the address list for others to use."],
        bestOption: "Check the stated purpose and seek clear permission for the promotional use.",
        explanation: "New uses should be consistent with what people were told when their details were collected.",
        nextStepByOption: { "Check the stated purpose and seek clear permission for the promotional use.": "message", "Send the promotion because addresses were collected at an event.": "purpose-repair", "Publish the address list for others to use.": "purpose-repair" },
      },
      {
        id: "purpose-repair",
        title: "Reset the contact plan",
        situation: "The proposed promotion does not match the purpose communicated when the addresses were collected.",
        prompt: "What is the responsible next step?",
        options: ["Pause the promotion and seek a clear opt-in for the new purpose before sending it.", "Send it once and explain later if anyone objects.", "Share the list with more groups to make the event worthwhile."],
        bestOption: "Pause the promotion and seek a clear opt-in for the new purpose before sending it.",
        explanation: "The repair path protects the original expectation before any new communication is considered.",
      },
      {
        id: "message",
        title: "Write the invitation",
        situation: "The team has a list of people who have clearly opted in to receive updates. It is drafting the first message.",
        prompt: "Which message feature best supports a respectful campaign?",
        options: ["State why the recipient is receiving it and provide a clear way to stop future updates.", "Hide the sender’s identity so the message looks more urgent.", "Reuse the list for unrelated groups without explanation."],
        bestOption: "State why the recipient is receiving it and provide a clear way to stop future updates.",
        explanation: "Clear purpose and respectful control help recipients understand and manage the communication.",
      },
    ],
  },
  {
    id: "engineering-layout-evidence",
    packId: "engineering-foundations",
    title: "Compare a study-area layout",
    eyebrow: "ENGINEERING CASE",
    summary: "Use constraints and relevant evidence before choosing a design direction.",
    boundaryNote: "This is a learning case, not engineering or safety approval.",
    reflectionPrompt: "Which constraint would you verify first in a similar design decision?",
    steps: [
      {
        id: "constraints",
        title: "Name what matters",
        situation: "Two study-area layouts fit the wall space. One is cheaper, while the other may be easier for users to reach. The group has not checked maintenance needs.",
        prompt: "What is the strongest next step?",
        options: ["List access, cost, maintenance, and space constraints before comparing the layouts.", "Choose the cheaper layout immediately.", "Choose the layout with the most colors."],
        bestOption: "List access, cost, maintenance, and space constraints before comparing the layouts.",
        explanation: "A responsible decision begins with explicit constraints instead of a single preference.",
        nextStepByOption: { "List access, cost, maintenance, and space constraints before comparing the layouts.": "evidence", "Choose the cheaper layout immediately.": "constraints-repair", "Choose the layout with the most colors.": "constraints-repair" },
      },
      {
        id: "constraints-repair",
        title: "Re-establish the constraints",
        situation: "The group notices that an early choice would ignore access and maintenance implications.",
        prompt: "How should the comparison be repaired before a layout is selected?",
        options: ["Write the relevant access, cost, maintenance, and space constraints, then compare both layouts against them.", "Keep the first choice because changing direction is inefficient.", "Ask only the person who prefers the chosen layout."],
        bestOption: "Write the relevant access, cost, maintenance, and space constraints, then compare both layouts against them.",
        explanation: "The repair makes the criteria visible before evidence is gathered or a direction is chosen.",
      },
      {
        id: "evidence",
        title: "Gather a relevant check",
        situation: "The group has listed its constraints and needs one fast evidence step before selecting a layout.",
        prompt: "Which check best fits the stated constraints?",
        options: ["Ask relevant users about reach and ask facilities staff about maintenance implications.", "Build both permanent layouts before gathering feedback.", "Use a random choice to avoid bias."],
        bestOption: "Ask relevant users about reach and ask facilities staff about maintenance implications.",
        explanation: "Relevant input helps compare the options against the constraints the group has already stated.",
      },
    ],
  },
  {
    id: "science-observation-cycle",
    packId: "natural-sciences-foundations",
    title: "Handle an unexpected observation",
    eyebrow: "NATURAL SCIENCES CASE",
    summary: "Move from one unexpected value to a careful, documented next observation.",
    reflectionPrompt: "What condition would you record before repeating a classroom observation?",
    steps: [
      {
        id: "record",
        title: "Record the conditions",
        situation: "A classroom measurement includes one unexpected value. The learner cannot tell whether the reading was stable and the method notes are incomplete.",
        prompt: "What should happen before a conclusion is drawn?",
        options: ["Record the conditions and uncertainty surrounding the value.", "Treat the value as final proof of a new explanation.", "Delete the value without noting that it occurred."],
        bestOption: "Record the conditions and uncertainty surrounding the value.",
        explanation: "Transparent notes preserve the observation while avoiding an unsupported conclusion.",
        nextStepByOption: { "Record the conditions and uncertainty surrounding the value.": "repeat", "Treat the value as final proof of a new explanation.": "record-repair", "Delete the value without noting that it occurred.": "record-repair" },
      },
      {
        id: "record-repair",
        title: "Recover the observation record",
        situation: "The unexpected value has not been documented with enough context to interpret it responsibly.",
        prompt: "What should be recorded before repeating the classroom procedure?",
        options: ["Note the observed value, method conditions, and uncertainty instead of treating it as proof or erasing it.", "Change the recorded value so it matches the expected pattern.", "Conclude that the result is meaningless without keeping notes."],
        bestOption: "Note the observed value, method conditions, and uncertainty instead of treating it as proof or erasing it.",
        explanation: "Documenting both the value and the conditions preserves a transparent basis for a later repeat.",
      },
      {
        id: "repeat",
        title: "Repeat carefully",
        situation: "The method notes are now complete and the learner can repeat the same classroom procedure.",
        prompt: "What is the most useful next action?",
        options: ["Repeat the observation using the stated method and compare the recorded results.", "Choose the value that best matches an expected answer.", "Change several conditions at once without recording them."],
        bestOption: "Repeat the observation using the stated method and compare the recorded results.",
        explanation: "Careful repetition helps distinguish a one-time observation from a supported pattern.",
      },
    ],
  },
  {
    id: "education-inclusive-check",
    packId: "education-foundations",
    title: "Design an inclusive learning check",
    eyebrow: "EDUCATION CASE",
    summary: "Keep one learning objective while offering fair ways to show understanding.",
    reflectionPrompt: "How would you explain the same success criterion to learners using different response formats?",
    steps: [
      {
        id: "objective",
        title: "Keep the objective central",
        situation: "A tutor wants to check whether learners can explain the main idea from a lesson. Some learners prefer a short spoken response and others prefer writing.",
        prompt: "Which plan keeps the check connected to the objective?",
        options: ["Allow an appropriate spoken or written response using the same clear success criteria.", "Require one format only because different formats cannot show the same learning.", "Skip the learning check entirely."],
        bestOption: "Allow an appropriate spoken or written response using the same clear success criteria.",
        explanation: "Multiple response formats can be fair when they are evaluated against the same relevant objective.",
        nextStepByOption: { "Allow an appropriate spoken or written response using the same clear success criteria.": "feedback", "Require one format only because different formats cannot show the same learning.": "objective-repair", "Skip the learning check entirely.": "objective-repair" },
      },
      {
        id: "objective-repair",
        title: "Reconnect format and objective",
        situation: "The tutor recognizes that the planned response rule would measure format preference rather than the intended learning.",
        prompt: "What adjustment keeps the learning check fair and focused?",
        options: ["Use the same clear success criteria for an appropriate spoken or written response.", "Score learners only on how quickly they respond.", "Remove the criterion so any response receives the same result."],
        bestOption: "Use the same clear success criteria for an appropriate spoken or written response.",
        explanation: "The repair path restores a single objective while allowing a relevant way to demonstrate understanding.",
      },
      {
        id: "feedback",
        title: "Use the response well",
        situation: "Learners have responded in their chosen format. The tutor is deciding how to use the answers.",
        prompt: "What feedback action is most useful?",
        options: ["Compare each response to the success criteria and name one next improvement.", "Rank learners by response speed only.", "Give identical feedback without looking at the objective."],
        bestOption: "Compare each response to the success criteria and name one next improvement.",
        explanation: "Objective-linked feedback helps learners understand what they achieved and what to improve.",
      },
    ],
  },
  {
    id: "social-context-inquiry",
    packId: "social-sciences-foundations",
    title: "Develop a context-sensitive inquiry",
    eyebrow: "SOCIAL SCIENCES CASE",
    summary: "Use individual perspectives to form a careful question without overgeneralizing.",
    reflectionPrompt: "What extra context would you want before interpreting a similar set of comments?",
    steps: [
      {
        id: "interpret",
        title: "Interpret carefully",
        situation: "A learner reads three anonymous comments about long travel times to campus. There is no information about routes, work schedules, costs, or the wider student population.",
        prompt: "Which interpretation is most responsible?",
        options: ["Treat the comments as useful perspectives that suggest a broader question for study.", "Use the comments to prove every learner experiences the same problem.", "Identify the authors publicly to verify the comments."],
        bestOption: "Treat the comments as useful perspectives that suggest a broader question for study.",
        explanation: "Individual perspectives can inform inquiry, but responsible interpretation avoids overgeneralizing and respects privacy.",
        nextStepByOption: { "Treat the comments as useful perspectives that suggest a broader question for study.": "question", "Use the comments to prove every learner experiences the same problem.": "interpret-repair", "Identify the authors publicly to verify the comments.": "interpret-repair" },
      },
      {
        id: "interpret-repair",
        title: "Reframe the evidence",
        situation: "The learner notices that a few anonymous comments cannot establish the experience of an entire student population.",
        prompt: "How should the initial interpretation be repaired?",
        options: ["Keep the comments anonymous and treat them as perspectives that point to a broader contextual question.", "Publish the comments with guesses about who wrote them.", "State that every learner has the same travel experience."],
        bestOption: "Keep the comments anonymous and treat them as perspectives that point to a broader contextual question.",
        explanation: "The repair protects privacy and returns the inquiry to an evidence-appropriate claim.",
      },
      {
        id: "question",
        title: "Frame the next question",
        situation: "The learner now wants to investigate travel experiences in a respectful way.",
        prompt: "Which question best follows from the limited comments?",
        options: ["How do route availability, schedules, cost, and study commitments shape travel experiences for different learners?", "Which single learner is responsible for the travel problem?", "How can comments be used to label all learners the same way?"],
        bestOption: "How do route availability, schedules, cost, and study commitments shape travel experiences for different learners?",
        explanation: "The question seeks relevant context rather than treating a few comments as a complete explanation.",
      },
    ],
  },
  {
    id: "uganda-biology-garden-inquiry",
    packId: "uganda-high-school-biology",
    title: "Plan a garden observation inquiry",
    eyebrow: "HIGH SCHOOL BIOLOGY CASE",
    summary: "Turn a school-garden observation into a careful question and a recordable comparison.",
    boundaryNote: "Learning case only; follow school fieldwork, laboratory, and safeguarding guidance.",
    reflectionPrompt: "What condition would you record before comparing a similar biological observation?",
    steps: [
      {
        id: "observation",
        title: "Keep the observation separate",
        situation: "In a school garden, leaves from plants in one corner appear darker than leaves from similar plants elsewhere. The learner has not recorded soil moisture, plant age, or exact light conditions.",
        prompt: "What is the strongest first response?",
        options: ["Record the visible difference and identify the conditions that still need comparison.", "Conclude that shade alone caused the colour difference.", "Remove the darker leaves so the plants match."],
        bestOption: "Record the visible difference and identify the conditions that still need comparison.",
        explanation: "The visible difference is useful evidence, but the learner needs relevant conditions before selecting an explanation.",
        nextStepByOption: { "Record the visible difference and identify the conditions that still need comparison.": "comparison", "Conclude that shade alone caused the colour difference.": "observation-repair", "Remove the darker leaves so the plants match.": "observation-repair" },
      },
      {
        id: "observation-repair",
        title: "Rebuild the observation record",
        situation: "The learner notices that a quick explanation would go beyond the details that were actually recorded.",
        prompt: "What should happen before an explanation is chosen?",
        options: ["Write down the observation and list relevant conditions to compare before making a claim.", "Choose the explanation that sounds most familiar.", "Ignore all differences because one observation cannot matter."],
        bestOption: "Write down the observation and list relevant conditions to compare before making a claim.",
        explanation: "The repair keeps the record useful while avoiding an unsupported conclusion.",
      },
      {
        id: "comparison",
        title: "Plan a careful comparison",
        situation: "The learner has listed relevant conditions and wants a simple next observation plan.",
        prompt: "Which plan best supports a fair comparison?",
        options: ["Use the same observation method for similar plants and record the selected conditions consistently.", "Change several conditions at once without noting them.", "Record only leaves that match the expected pattern."],
        bestOption: "Use the same observation method for similar plants and record the selected conditions consistently.",
        explanation: "Consistent observations and clear notes make later reasoning more dependable.",
      },
    ],
  },
  {
    id: "uganda-chemistry-variable-plan",
    packId: "uganda-high-school-chemistry",
    title: "Plan a fair chemistry comparison",
    eyebrow: "HIGH SCHOOL CHEMISTRY CASE",
    summary: "Use a clear comparison question, stated conditions, and a transparent record.",
    boundaryNote: "Learning case only; teacher instructions and school laboratory rules take priority.",
    reflectionPrompt: "What would you keep consistent in a future classroom comparison?",
    steps: [
      {
        id: "focus",
        title: "Choose one focus",
        situation: "A learner is preparing a teacher-supervised classroom activity and proposes changing the amount of material, container, and observation time at the same time.",
        prompt: "What should the learner do first?",
        options: ["Choose one main condition to compare and state what will be observed consistently.", "Change every condition at once to make the result more interesting.", "Decide the expected result before recording anything."],
        bestOption: "Choose one main condition to compare and state what will be observed consistently.",
        explanation: "A focused comparison is easier to interpret when the learner identifies the main condition and a consistent observation method.",
        nextStepByOption: { "Choose one main condition to compare and state what will be observed consistently.": "record", "Change every condition at once to make the result more interesting.": "focus-repair", "Decide the expected result before recording anything.": "focus-repair" },
      },
      {
        id: "focus-repair",
        title: "Restore a useful question",
        situation: "The proposed activity would not make it clear which changed condition might relate to the observation.",
        prompt: "How should the plan be repaired?",
        options: ["State one comparison focus and plan a consistent way to record the observation.", "Keep every change because results are more important than the method.", "Avoid recording the conditions to save time."],
        bestOption: "State one comparison focus and plan a consistent way to record the observation.",
        explanation: "The repair makes the comparison question and record clear before the activity continues.",
      },
      {
        id: "record",
        title: "Use a transparent record",
        situation: "The learner has a focused comparison question and a teacher-approved classroom procedure.",
        prompt: "Which record supports careful interpretation?",
        options: ["Record the stated conditions and each observation, including an unexpected result.", "Keep only observations that match an expected pattern.", "Write a conclusion without noting the observations."],
        bestOption: "Record the stated conditions and each observation, including an unexpected result.",
        explanation: "A complete record supports discussion of the evidence instead of selecting only convenient results.",
      },
    ],
  },
  {
    id: "uganda-economics-budget-tradeoff",
    packId: "uganda-high-school-economics",
    title: "Compare a club-budget trade-off",
    eyebrow: "HIGH SCHOOL ECONOMICS CASE",
    summary: "Make a limited-resource choice by naming the alternatives, evidence, and trade-off.",
    boundaryNote: "Learning case only; this is not personal, business, or financial advice.",
    reflectionPrompt: "What information would you compare before explaining a similar budget choice?",
    steps: [
      {
        id: "tradeoff",
        title: "Make the alternatives visible",
        situation: "A school club has a limited amount left for the term. It can buy materials for one activity now or keep the funds for a planned future need, but cannot fully fund both choices.",
        prompt: "What should the group do first?",
        options: ["List the purpose, cost, and benefit of each option, then name what is given up with either choice.", "Choose the option suggested by the loudest group member.", "Say there is no trade-off because both options are useful."],
        bestOption: "List the purpose, cost, and benefit of each option, then name what is given up with either choice.",
        explanation: "A trade-off becomes clearer when the group compares the alternatives against its limited resources and stated purpose.",
        nextStepByOption: { "List the purpose, cost, and benefit of each option, then name what is given up with either choice.": "explain", "Choose the option suggested by the loudest group member.": "tradeoff-repair", "Say there is no trade-off because both options are useful.": "tradeoff-repair" },
      },
      {
        id: "tradeoff-repair",
        title: "Return to the recorded evidence",
        situation: "The group sees that an early choice would hide the limited budget and the alternative being forgone.",
        prompt: "What should be added before a decision is explained?",
        options: ["A comparison of the stated costs, purposes, and trade-offs for both options.", "A promise that one option will benefit every person equally.", "A rule that no one may ask about the budget."],
        bestOption: "A comparison of the stated costs, purposes, and trade-offs for both options.",
        explanation: "The repair reconnects the choice to the available evidence and the limited-resource constraint.",
      },
      {
        id: "explain",
        title: "Explain the chosen option",
        situation: "The group has compared both options and is ready to write a short decision note.",
        prompt: "Which note uses the comparison most responsibly?",
        options: ["State the selected option, the main reason, and the relevant trade-off that the group accepts.", "Claim the choice has no disadvantages for anyone.", "Hide the alternative so the decision seems automatic."],
        bestOption: "State the selected option, the main reason, and the relevant trade-off that the group accepts.",
        explanation: "A transparent explanation connects the decision to the evidence and acknowledges what is given up.",
      },
    ],
  },
  {
    id: "uganda-entrepreneurship-feedback-plan",
    packId: "uganda-high-school-entrepreneurship",
    title: "Test an idea respectfully",
    eyebrow: "HIGH SCHOOL ENTREPRENEURSHIP CASE",
    summary: "Turn an early learner idea into an ethical, evidence-seeking feedback plan.",
    boundaryNote: "Learning case only; this is not legal, business, or investment advice.",
    reflectionPrompt: "What would you ask people before using feedback about a future idea?",
    steps: [
      {
        id: "purpose",
        title: "State the feedback purpose",
        situation: "A learner wants feedback on a small school-based idea. A friend suggests collecting classmates’ contact details from a group chat and sending repeated messages without explaining the reason.",
        prompt: "What is the responsible first step?",
        options: ["Explain the learning purpose, invite voluntary feedback, and collect only what is needed.", "Use the contact details immediately because the idea is small.", "Share the contact details with more learners to get faster responses."],
        bestOption: "Explain the learning purpose, invite voluntary feedback, and collect only what is needed.",
        explanation: "Respectful feedback starts with a clear purpose, voluntary participation, and minimal personal information.",
        nextStepByOption: { "Explain the learning purpose, invite voluntary feedback, and collect only what is needed.": "review", "Use the contact details immediately because the idea is small.": "purpose-repair", "Share the contact details with more learners to get faster responses.": "purpose-repair" },
      },
      {
        id: "purpose-repair",
        title: "Reset the feedback plan",
        situation: "The learner recognises that the proposed contact method would not clearly respect classmates’ choices.",
        prompt: "What should change before feedback is requested?",
        options: ["Use a clear voluntary invitation that explains the purpose and avoids unnecessary personal details.", "Message people repeatedly until they answer.", "Record only positive opinions about the idea."],
        bestOption: "Use a clear voluntary invitation that explains the purpose and avoids unnecessary personal details.",
        explanation: "The repair protects people’s choice and makes the feedback process more trustworthy.",
      },
      {
        id: "review",
        title: "Use mixed feedback well",
        situation: "The learner now has a small set of voluntary comments, including positive questions and concerns.",
        prompt: "Which response makes the feedback useful?",
        options: ["Group the comments by recurring needs or concerns and identify one question to investigate next.", "Discard comments that do not praise the idea.", "Treat a few comments as proof that every customer will buy."],
        bestOption: "Group the comments by recurring needs or concerns and identify one question to investigate next.",
        explanation: "Mixed feedback can guide the next question without being treated as a final market conclusion.",
      },
    ],
  },
  {
    id: "uganda-english-source-draft",
    packId: "uganda-high-school-english",
    title: "Prepare a clear sourced paragraph",
    eyebrow: "HIGH SCHOOL ENGLISH CASE",
    summary: "Move from a useful online idea to a traceable, reader-friendly class paragraph.",
    boundaryNote: "Learning case only; use your school’s guidance for formal assignments and assessment.",
    reflectionPrompt: "What source detail will you capture before using an online idea in future writing?",
    steps: [
      {
        id: "source",
        title: "Capture the source first",
        situation: "A learner finds a useful online explanation while drafting a class paragraph. A sentence has been copied into the draft, but the page title, author, and link have not been recorded.",
        prompt: "What should happen before the draft is shared?",
        options: ["Record the source details and decide whether to quote or paraphrase the idea clearly.", "Keep the sentence because online writing does not need a source.", "Remove all source details so the paragraph looks more original."],
        bestOption: "Record the source details and decide whether to quote or paraphrase the idea clearly.",
        explanation: "Capturing details and making source use clear helps a reader understand where wording or ideas came from.",
        nextStepByOption: { "Record the source details and decide whether to quote or paraphrase the idea clearly.": "revision", "Keep the sentence because online writing does not need a source.": "source-repair", "Remove all source details so the paragraph looks more original.": "source-repair" },
      },
      {
        id: "source-repair",
        title: "Restore traceable source use",
        situation: "The learner notices that a copied sentence cannot be checked against the original page.",
        prompt: "What is the best repair before the paragraph continues?",
        options: ["Return to the original page, record its details, and revise the draft to show the source use clearly.", "Invent a source name so the paragraph looks complete.", "Submit the paragraph without a source check."],
        bestOption: "Return to the original page, record its details, and revise the draft to show the source use clearly.",
        explanation: "The repair restores a clear trail to the original context before the learner develops the paragraph.",
      },
      {
        id: "revision",
        title: "Check the paragraph for a reader",
        situation: "The learner has recorded the source and has drafted a clear claim with a supporting detail.",
        prompt: "Which revision check is most useful now?",
        options: ["Check that the claim is specific, the support relates to it, and the source use is clear to a reader.", "Add more dramatic words without checking the meaning.", "Remove the supporting detail so the paragraph becomes shorter."],
        bestOption: "Check that the claim is specific, the support relates to it, and the source use is clear to a reader.",
        explanation: "A focused revision check improves clarity, support, and responsible source use at the same time.",
      },
    ],
  },
  {
    id: "uganda-physics-measurement-inquiry",
    packId: "uganda-high-school-physics",
    title: "Compare a measurement record",
    eyebrow: "HIGH SCHOOL PHYSICS CASE",
    summary: "Move from a quick measurement claim to a consistent, checkable comparison plan.",
    boundaryNote: "Learning case only; school safety rules and teacher instructions always take priority.",
    reflectionPrompt: "What condition would you keep consistent in a future measurement comparison?",
    steps: [
      {
        id: "record",
        title: "Check the record first",
        situation: "A learner compares two motion records but notices that one distance was measured using a tape and the other was estimated by footsteps. The timing method is also not clearly stated.",
        prompt: "What should happen before the learner explains the difference?",
        options: ["Record the measurement methods and plan a consistent distance and timing comparison.", "Conclude that the faster-looking trial proves a force explanation.", "Keep only the record that matches the expected answer."],
        bestOption: "Record the measurement methods and plan a consistent distance and timing comparison.",
        explanation: "A clear record and a consistent method help separate a comparison of measurements from an unsupported explanation.",
        nextStepByOption: { "Record the measurement methods and plan a consistent distance and timing comparison.": "compare", "Conclude that the faster-looking trial proves a force explanation.": "record-repair", "Keep only the record that matches the expected answer.": "record-repair" },
      },
      {
        id: "record-repair",
        title: "Restore the comparison plan",
        situation: "The learner sees that the earlier claim would rely on records made in different ways.",
        prompt: "What is the strongest repair?",
        options: ["State a consistent distance and timing method, then record the relevant conditions before comparing results.", "Select the most dramatic value and treat it as final proof.", "Avoid writing down the measurement method."],
        bestOption: "State a consistent distance and timing method, then record the relevant conditions before comparing results.",
        explanation: "The repair makes the later comparison checkable and avoids deciding on a cause too early.",
      },
      {
        id: "compare",
        title: "Explain only the record",
        situation: "The learner has a consistent set of measurements and has calculated the distance per second for each trial.",
        prompt: "Which explanation is most responsible?",
        options: ["Describe the difference shown by the recorded values and identify any further evidence needed before explaining its cause.", "Say the values prove every object will move the same way.", "Ignore an unexpected value because it makes the pattern less tidy."],
        bestOption: "Describe the difference shown by the recorded values and identify any further evidence needed before explaining its cause.",
        explanation: "The record can support a careful description while leaving room for evidence before a broader causal claim.",
      },
    ],
  },
  {
    id: "uganda-mathematics-pattern-explanation",
    packId: "uganda-high-school-mathematics",
    title: "Explain a number pattern clearly",
    eyebrow: "HIGH SCHOOL MATHEMATICS CASE",
    summary: "Use stated rules, visible steps, and a checking strategy to explain a pattern.",
    boundaryNote: "Learning case only; this is not an official marking or examination prediction service.",
    reflectionPrompt: "What written step would help another learner check your next mathematical explanation?",
    steps: [
      {
        id: "rule",
        title: "State the rule",
        situation: "A learner sees the sequence 5, 9, 13, 17 and immediately writes that the next value is 22. The learner has not shown the rule used.",
        prompt: "What should the learner do first?",
        options: ["State the repeated change and apply it step by step before selecting the next value.", "Choose a number that looks close to the previous value.", "Copy a classmate’s answer without checking the pattern."],
        bestOption: "State the repeated change and apply it step by step before selecting the next value.",
        explanation: "Writing the repeated change makes the reasoning visible and lets the learner check the result.",
        nextStepByOption: { "State the repeated change and apply it step by step before selecting the next value.": "check", "Choose a number that looks close to the previous value.": "rule-repair", "Copy a classmate’s answer without checking the pattern.": "rule-repair" },
      },
      {
        id: "rule-repair",
        title: "Rebuild the reasoning",
        situation: "The learner recognises that a guessed next value cannot be justified from the sequence alone.",
        prompt: "What should be added to the explanation?",
        options: ["The repeated change between terms and the arithmetic step used to produce the next term.", "A statement that the answer feels correct.", "A different number without showing any method."],
        bestOption: "The repeated change between terms and the arithmetic step used to produce the next term.",
        explanation: "The repair replaces a guess with a method another learner can follow and check.",
      },
      {
        id: "check",
        title: "Verify the next term",
        situation: "The learner has identified that each term increases by 4 and is ready to check the next value.",
        prompt: "Which next term and explanation are correct?",
        options: ["21, because adding 4 to 17 continues the stated pattern.", "22, because the next number should be larger.", "20, because it is close to 17."],
        bestOption: "21, because adding 4 to 17 continues the stated pattern.",
        explanation: "Applying the stated rule of adding 4 to 17 gives 21. The written rule makes the conclusion checkable.",
      },
    ],
  },
  {
    id: "uganda-geography-place-evidence",
    packId: "uganda-high-school-geography",
    title: "Compare evidence about a changing place",
    eyebrow: "HIGH SCHOOL GEOGRAPHY CASE",
    summary: "Use dated place-based records before explaining a local environmental change.",
    boundaryNote: "Learning case only; this is not environmental, land-use, legal, or safety advice.",
    reflectionPrompt: "What date or place detail would you record before explaining a future geographic change?",
    steps: [
      { id: "claim", title: "Name what the record shows", situation: "Learners compare two images of the same hillside but do not know the dates, viewpoints, or conditions under which the images were made.", prompt: "What is the strongest first response?", options: ["Record the visible differences and identify the missing dates, viewpoints, and conditions before naming a cause.", "Name one cause immediately because the images look different.", "Ignore the images because place-based evidence is never useful."], bestOption: "Record the visible differences and identify the missing dates, viewpoints, and conditions before naming a cause.", explanation: "The images can support observation, but a cause requires clearer context and additional evidence.", nextStepByOption: { "Record the visible differences and identify the missing dates, viewpoints, and conditions before naming a cause.": "compare", "Name one cause immediately because the images look different.": "claim-repair", "Ignore the images because place-based evidence is never useful.": "claim-repair" } },
      { id: "claim-repair", title: "Restore the evidence plan", situation: "The learners recognise that the first explanation went beyond the available image details.", prompt: "What should be added before a cause is discussed?", options: ["Dated observations and relevant local information that can be compared with the images.", "A more confident statement about the first cause.", "A decision to remove records that do not match the claim."], bestOption: "Dated observations and relevant local information that can be compared with the images.", explanation: "The repair keeps observation and explanation separate while building a useful comparison plan." },
      { id: "compare", title: "Explain cautiously", situation: "The learners now have dates, comparable viewpoints, and additional relevant observations.", prompt: "Which conclusion is most responsible?", options: ["Describe the documented change and identify what evidence supports or limits a possible explanation.", "Claim that one image proves every future outcome.", "Ignore records that do not fit the preferred explanation."], bestOption: "Describe the documented change and identify what evidence supports or limits a possible explanation.", explanation: "A careful geographic explanation connects a claim to available place-based evidence and acknowledges limits." },
    ],
  },
  {
    id: "uganda-history-civics-source-dialogue",
    packId: "uganda-high-school-history-civics",
    title: "Build a fair source discussion",
    eyebrow: "HIGH SCHOOL HISTORY AND CIVICS CASE",
    summary: "Use multiple perspectives respectfully before reaching a historical or civic conclusion.",
    boundaryNote: "Learning case only; it is not political, legal, or civic authority guidance.",
    reflectionPrompt: "What would help you check a historical or civic claim before repeating it?",
    steps: [
      { id: "source", title: "Separate source from conclusion", situation: "A class has one remembered account of an event and a short written notice made later. Learners disagree about which account should end the discussion.", prompt: "What is the strongest first step?", options: ["Describe what each source says, note its context, and identify details that another source could help check.", "Choose the source from the most confident speaker.", "Discard sources that offer a different perspective."], bestOption: "Describe what each source says, note its context, and identify details that another source could help check.", explanation: "Historical and civic reasoning can take sources seriously without treating one perspective as automatic proof.", nextStepByOption: { "Describe what each source says, note its context, and identify details that another source could help check.": "dialogue", "Choose the source from the most confident speaker.": "source-repair", "Discard sources that offer a different perspective.": "source-repair" } },
      { id: "source-repair", title: "Return to the record", situation: "The class notices that selecting a source by confidence or preference would hide relevant questions about context.", prompt: "What should be repaired?", options: ["State each source’s information and context, then identify a detail that needs corroboration.", "Repeat the preferred source more loudly.", "Say no source can ever be useful."], bestOption: "State each source’s information and context, then identify a detail that needs corroboration.", explanation: "The repair creates a fair path from sources to a more evidence-aware discussion." },
      { id: "dialogue", title: "Reach a respectful conclusion", situation: "The class has identified what the sources agree on and where details remain uncertain.", prompt: "Which conclusion is most responsible?", options: ["State the supported point, note uncertainty clearly, and invite respectful reasons if classmates interpret the sources differently.", "Say disagreement means one learner must be excluded.", "Present an uncertain detail as certain to finish quickly."], bestOption: "State the supported point, note uncertainty clearly, and invite respectful reasons if classmates interpret the sources differently.", explanation: "A strong conclusion uses the evidence available and preserves respectful dialogue where interpretation remains open." },
    ],
  },
  {
    id: "uganda-ict-information-safety",
    packId: "uganda-high-school-ict",
    title: "Check and share digital information responsibly",
    eyebrow: "HIGH SCHOOL ICT CASE",
    summary: "Move from a forwarded digital claim to a checked, privacy-aware response.",
    boundaryNote: "Learning case only; this is not cybersecurity, legal, or data-protection advice.",
    reflectionPrompt: "What source detail would you check before sharing a future digital claim?",
    steps: [
      { id: "check", title: "Check before sharing", situation: "A learner receives a message claiming that a school activity has been cancelled. It has no named school office, date, or official link, but classmates are asking the learner to forward it.", prompt: "What is the strongest first response?", options: ["Check a named official school source or ask the responsible contact before treating the message as confirmed.", "Forward the message because several classmates requested it.", "Add classmates’ phone numbers to a public post so they can decide."], bestOption: "Check a named official school source or ask the responsible contact before treating the message as confirmed.", explanation: "A forwarded message needs a relevant named source before it is repeated as confirmed information.", nextStepByOption: { "Check a named official school source or ask the responsible contact before treating the message as confirmed.": "share", "Forward the message because several classmates requested it.": "check-repair", "Add classmates’ phone numbers to a public post so they can decide.": "check-repair" } },
      { id: "check-repair", title: "Reset the digital response", situation: "The learner sees that forwarding an unverified message or adding personal details could create avoidable harm.", prompt: "What should happen next?", options: ["Pause sharing, seek a named official confirmation, and avoid adding unnecessary personal information.", "Send the message repeatedly until someone replies.", "Assume every message in a group is official."], bestOption: "Pause sharing, seek a named official confirmation, and avoid adding unnecessary personal information.", explanation: "The repair combines information checking with respectful treatment of other people’s details." },
      { id: "share", title: "Share a checked update", situation: "The learner has received a clear response from an authorised school contact.", prompt: "Which share is most responsible?", options: ["Share only the confirmed update and point classmates to the named school source where appropriate.", "Add private contact details to make the message look official.", "Claim that the update applies beyond what the source states."], bestOption: "Share only the confirmed update and point classmates to the named school source where appropriate.", explanation: "A responsible share stays within the confirmed information and does not expose unnecessary personal details." },
    ],
  },
  {
    id: "uganda-agriculture-record-inquiry",
    packId: "uganda-high-school-agriculture",
    title: "Plan a careful production inquiry",
    eyebrow: "HIGH SCHOOL AGRICULTURE CASE",
    summary: "Use records and relevant conditions before explaining a production difference.",
    boundaryNote: "Learning case only; it is not farming, environmental, veterinary, or safety guidance.",
    reflectionPrompt: "What condition would you record before explaining a future production difference?",
    steps: [
      { id: "record", title: "Keep the production record clear", situation: "A school garden bed produced fewer recorded units in one week. The learner knows the count but has not recorded planting date, rainfall, soil condition, care routines, or pest observations.", prompt: "What should the learner do first?", options: ["Record the observed difference and identify relevant conditions that would need comparison before naming a cause.", "Announce that one cause has been proven.", "Remove the lower count from the record."], bestOption: "Record the observed difference and identify relevant conditions that would need comparison before naming a cause.", explanation: "The count is useful evidence, but an explanation needs more relevant records and comparison.", nextStepByOption: { "Record the observed difference and identify relevant conditions that would need comparison before naming a cause.": "compare", "Announce that one cause has been proven.": "record-repair", "Remove the lower count from the record.": "record-repair" } },
      { id: "record-repair", title: "Rebuild the observation plan", situation: "The learner recognises that a quick conclusion or removing a result would weaken the inquiry.", prompt: "What should be restored?", options: ["A complete record of the observation and relevant conditions for a fair later comparison.", "Only the result that appears strongest.", "A recommendation for every farm without further records."], bestOption: "A complete record of the observation and relevant conditions for a fair later comparison.", explanation: "The repair preserves useful observations and prepares a more reliable comparison." },
      { id: "compare", title: "Use the comparison responsibly", situation: "The learner has consistent records across similar observations and notices a possible pattern.", prompt: "Which statement is most responsible?", options: ["Describe the pattern in the records and identify what further evidence would be needed before a broad recommendation.", "Treat the pattern as proof for every location and season.", "Discard a record that does not match the pattern."], bestOption: "Describe the pattern in the records and identify what further evidence would be needed before a broad recommendation.", explanation: "A careful agricultural conclusion stays connected to the stated records and recognises its limits." },
    ],
  },
  {
    id: "uganda-ethics-respectful-dialogue",
    packId: "uganda-high-school-religion-ethics",
    title: "Plan a respectful ethical dialogue",
    eyebrow: "HIGH SCHOOL RELIGIOUS AND ETHICAL STUDIES CASE",
    summary: "Use values, reasons, and dignity to guide a classroom discussion about a community choice.",
    boundaryNote: "Learning case only; it is not religious authority, counselling, or legal advice.",
    reflectionPrompt: "What discussion rule would help you respect people during a future disagreement?",
    steps: [
      { id: "dialogue", title: "Protect respectful participation", situation: "Classmates disagree about how a school activity should recognise different community traditions. One learner proposes choosing a single view before listening to anyone else.", prompt: "What is the strongest first step?", options: ["Invite respectful perspectives, agree on a dignity-focused discussion rule, and identify shared needs.", "Choose one view immediately and stop the discussion.", "Ask classmates to reveal private details about their beliefs."], bestOption: "Invite respectful perspectives, agree on a dignity-focused discussion rule, and identify shared needs.", explanation: "Ethical dialogue can recognise difference while protecting people’s dignity and creating space for reasons.", nextStepByOption: { "Invite respectful perspectives, agree on a dignity-focused discussion rule, and identify shared needs.": "reason", "Choose one view immediately and stop the discussion.": "dialogue-repair", "Ask classmates to reveal private details about their beliefs.": "dialogue-repair" } },
      { id: "dialogue-repair", title: "Reset the discussion process", situation: "The class sees that excluding views or requesting private belief details would not create a respectful learning discussion.", prompt: "What should be restored?", options: ["A voluntary, respectful process that discusses ideas and shared needs without exposing private details.", "A rule that only one learner may speak.", "A personal attack on classmates who disagree."], bestOption: "A voluntary, respectful process that discusses ideas and shared needs without exposing private details.", explanation: "The repair focuses the conversation on ideas and community needs while protecting personal dignity." },
      { id: "reason", title: "Propose an inclusive next step", situation: "The class has heard several respectful perspectives and has identified a shared need for a school activity that treats learners fairly.", prompt: "Which next step is most responsible?", options: ["Use school guidance and the stated shared needs to propose an option, while noting where further consultation is needed.", "Claim that every learner must hold the same view.", "Share private discussion details outside the class."], bestOption: "Use school guidance and the stated shared needs to propose an option, while noting where further consultation is needed.", explanation: "A respectful ethical conclusion connects values, reasons, school guidance, and the limits of the class discussion." },
    ],
  },
  {
    id: "uganda-kiswahili-message-clarity",
    packId: "uganda-high-school-kiswahili",
    title: "Panga ujumbe wa wazi na wa heshima",
    eyebrow: "HIGH SCHOOL KISWAHILI CASE",
    summary: "Turn a rushed group message into a clear, respectful Kiswahili communication plan.",
    boundaryNote: "Learning case only; this is not an official language assessment or counselling guidance.",
    reflectionPrompt: "Ni sehemu gani ya ujumbe ungeikagua ili iwe wazi na yenye heshima?",
    steps: [
      { id: "audience", title: "Tambua hadhira na kusudi", situation: "Mwanafunzi anataka kutuma ujumbe kwa kikundi cha kusoma. Ujumbe una maneno mengi ya haraka lakini hausimami kwa kusudi, muda, au hatua inayofuata.", prompt: "Hatua ipi ni bora kwanza?", options: ["Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata kabla ya kutuma.", "Tuma ujumbe mrefu bila kuusoma tena.", "Tumia kejeli ili watu wajibu haraka."], bestOption: "Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata kabla ya kutuma.", explanation: "Ujumbe wenye kusudi na hatua wazi humsaidia msomaji kuelewa bila kubashiri.", nextStepByOption: { "Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata kabla ya kutuma.": "revision", "Tuma ujumbe mrefu bila kuusoma tena.": "audience-repair", "Tumia kejeli ili watu wajibu haraka.": "audience-repair" } },
      { id: "audience-repair", title: "Rekebisha mpango wa ujumbe", situation: "Mwanafunzi anatambua kwamba ujumbe wa haraka unaweza kuwachanganya au kuwadharau wasomaji.", prompt: "Nini kiongezwe kabla ya kutuma?", options: ["Kusudi wazi, maelezo yanayohitajika, na lugha ya heshima inayolingana na hadhira.", "Maneno mengi yasiyo na hatua inayofuata.", "Maelezo binafsi ya wanafunzi wengine."], bestOption: "Kusudi wazi, maelezo yanayohitajika, na lugha ya heshima inayolingana na hadhira.", explanation: "Marekebisho yanarudisha uwazi na heshima bila kufichua maelezo yasiyohitajika." },
      { id: "revision", title: "Kagua kwa msomaji", situation: "Ujumbe sasa una kusudi, maelezo muhimu, na mwaliko wa hatua inayofuata.", prompt: "Ukaguzi upi ni wa muhimu zaidi?", options: ["Kagua kama msomaji anaweza kuelewa kusudi na hatua inayofuata kwa lugha ya heshima.", "Ongeza maneno magumu bila sababu.", "Ondoa maelezo yote ili ujumbe ubaki wa siri."], bestOption: "Kagua kama msomaji anaweza kuelewa kusudi na hatua inayofuata kwa lugha ya heshima.", explanation: "Ukaguzi huu huunganisha uwazi, hadhira, na mawasiliano ya heshima." },
    ],
  },
  {
    id: "uganda-literature-textual-reading",
    packId: "uganda-high-school-literature",
    title: "Build a text-based interpretation",
    eyebrow: "HIGH SCHOOL LITERATURE CASE",
    summary: "Move from a quick reaction to an interpretation grounded in stated textual details.",
    boundaryNote: "Learning case only; this is not an official marking or examination prediction service.",
    reflectionPrompt: "What exact textual detail would you capture before making your next interpretation?",
    steps: [
      { id: "detail", title: "Start with the text", situation: "A learner says a character is ‘selfish’ after reading one short scene but cannot point to the character’s words, actions, or the wider situation.", prompt: "What is the strongest first step?", options: ["Return to the scene, identify a stated action or line, and explain what it may support.", "Treat the first reaction as enough evidence.", "Remove details that might support another reading."], bestOption: "Return to the scene, identify a stated action or line, and explain what it may support.", explanation: "Close reading starts by connecting an interpretation to a stated detail rather than a quick label.", nextStepByOption: { "Return to the scene, identify a stated action or line, and explain what it may support.": "interpret", "Treat the first reaction as enough evidence.": "detail-repair", "Remove details that might support another reading.": "detail-repair" } },
      { id: "detail-repair", title: "Restore the textual basis", situation: "The learner sees that a character label alone does not show how the text supports the claim.", prompt: "What should be added?", options: ["A precise line or action from the scene and a cautious explanation of its meaning.", "A stronger opinion without a detail.", "An assumption about the author’s private life."], bestOption: "A precise line or action from the scene and a cautious explanation of its meaning.", explanation: "The repair returns the response to the text while avoiding claims beyond the stated scene." },
      { id: "interpret", title: "Compare possible readings", situation: "The learner has identified a character action and a line of dialogue that can support a reading.", prompt: "Which response is most responsible?", options: ["State the interpretation, explain the supporting detail, and note that another reading may need its own textual support.", "Claim that no other reader can discuss the scene.", "Treat the detail as proof of every character trait."], bestOption: "State the interpretation, explain the supporting detail, and note that another reading may need its own textual support.", explanation: "A thoughtful interpretation is text-based and remains open to other supported readings." },
    ],
  },
  {
    id: "uganda-fine-art-critique-plan",
    packId: "uganda-high-school-fine-art",
    title: "Plan a respectful visual critique",
    eyebrow: "HIGH SCHOOL FINE ART CASE",
    summary: "Use visible choices and the artist’s stated purpose to guide a respectful classroom critique.",
    boundaryNote: "Learning case only; it is not professional art assessment or permission to share another learner’s work.",
    reflectionPrompt: "What visible design choice would you mention in a future respectful critique?",
    steps: [
      { id: "observe", title: "Observe before judging", situation: "A learner sees a classmate’s artwork and says it is ‘bad’ without describing any colour, line, placement, texture, or the artist’s stated purpose.", prompt: "What should happen first?", options: ["Describe one visible design choice and ask how it relates to the artist’s stated purpose.", "Use an insult to make the critique memorable.", "Share a photo outside class before speaking to the artist."], bestOption: "Describe one visible design choice and ask how it relates to the artist’s stated purpose.", explanation: "Respectful critique starts with what is visible and makes room for the artist’s purpose.", nextStepByOption: { "Describe one visible design choice and ask how it relates to the artist’s stated purpose.": "response", "Use an insult to make the critique memorable.": "observe-repair", "Share a photo outside class before speaking to the artist.": "observe-repair" } },
      { id: "observe-repair", title: "Reset the critique", situation: "The learner recognises that a personal attack or unapproved sharing would not help the classroom critique.", prompt: "What should the critique focus on?", options: ["Visible choices, the stated purpose, and a respectful question or suggestion.", "Rumours about the artist.", "A demand that every viewer feel the same way."], bestOption: "Visible choices, the stated purpose, and a respectful question or suggestion.", explanation: "The repair keeps the conversation focused on the work and protects the artist’s dignity." },
      { id: "response", title: "Offer a useful response", situation: "The learner can now identify a central colour contrast and has heard the artist’s stated purpose.", prompt: "Which response is most useful?", options: ["Explain how the contrast may support the purpose and ask one respectful revision question.", "Declare that the artwork has one fixed meaning for everyone.", "Judge the artist rather than the visible work."], bestOption: "Explain how the contrast may support the purpose and ask one respectful revision question.", explanation: "The response connects visible evidence to purpose and makes critique useful for the next creative step." },
    ],
  },
  {
    id: "uganda-technical-drawing-review",
    packId: "uganda-high-school-technical-drawing",
    title: "Prepare a clear drawing review",
    eyebrow: "HIGH SCHOOL TECHNICAL DRAWING CASE",
    summary: "Move from an unclear classroom drawing to a legible, reviewable technical communication plan.",
    boundaryNote: "Learning case only; it is not engineering, construction, manufacturing, or safety guidance.",
    reflectionPrompt: "What label, view, or scale detail would you check before sharing your next classroom drawing?",
    steps: [
      { id: "view", title: "State what the drawing shows", situation: "A learner draws an object outline but does not label the view, scale, or feature being shown. The learner wants classmates to guess the missing details.", prompt: "What is the strongest first step?", options: ["State the view and relevant drawing information, then check what is still missing before peer review.", "Assume every viewer will infer the same missing details.", "Add dimensions that were not measured just to fill the page."], bestOption: "State the view and relevant drawing information, then check what is still missing before peer review.", explanation: "Clear labels and stated information make a classroom drawing easier to review without inventing missing detail.", nextStepByOption: { "State the view and relevant drawing information, then check what is still missing before peer review.": "review", "Assume every viewer will infer the same missing details.": "view-repair", "Add dimensions that were not measured just to fill the page.": "view-repair" } },
      { id: "view-repair", title: "Restore clear communication", situation: "The learner sees that guessing or inventing details would make the drawing difficult to review responsibly.", prompt: "What should be restored?", options: ["Legible stated labels and a clear note of information that the drawing does not yet provide.", "More unlabelled lines.", "A claim that the drawing is ready for construction."], bestOption: "Legible stated labels and a clear note of information that the drawing does not yet provide.", explanation: "The repair makes the drawing’s communication limits visible rather than hiding them." },
      { id: "review", title: "Use peer feedback", situation: "The drawing now includes a stated view and clear labels, and the learner is ready for a classroom peer review.", prompt: "Which feedback question is most useful?", options: ["Can a reviewer identify the stated view and see which information remains to be checked or added?", "Can a reviewer guess the learner’s private intentions?", "Can the drawing be treated as a safety instruction without a teacher review?"], bestOption: "Can a reviewer identify the stated view and see which information remains to be checked or added?", explanation: "A review question should check clear communication and acknowledge that a classroom drawing is not a construction instruction." },
    ],
  },
];

export function caseChainForPack(packId: string): CourseCaseChain | null {
  return COURSE_CASE_CHAINS.find((chain) => chain.packId === packId) ?? null;
}

export function caseChainForId(chainId: string): CourseCaseChain | null {
  return COURSE_CASE_CHAINS.find((chain) => chain.id === chainId) ?? null;
}
