export type CaseChainStep = {
  id: string;
  title: string;
  situation: string;
  prompt: string;
  options: string[];
  bestOption: string;
  explanation: string;
  /** Optional, finite next-step map. Any option without a target proceeds to the next listed step or reflection. */
  nextStepByOption?: Record<string, string>;
};

export type CourseCaseChain = {
  id: string;
  packId: string;
  title: string;
  eyebrow: string;
  summary: string;
  boundaryNote?: string;
  reflectionPrompt: string;
  steps: CaseChainStep[];
};

export const COURSE_CASE_CHAINS: CourseCaseChain[] = [
  {
    id: "foundation-source-plan",
    packId: "university-foundation-year",
    title: "Prepare a traceable source plan",
    eyebrow: "ACADEMIC FOUNDATIONS CASE",
    summary: "Move from useful notes to an attributable, submission-ready draft.",
    reflectionPrompt: "What source-checking habit will you use before your next draft?",
    steps: [
      {
        id: "capture",
        title: "Capture the source details",
        situation: "You have copied useful wording from an online article into a private draft. The article remains open, but no author, date, title, or link has been recorded.",
        prompt: "What should you do first?",
        options: ["Record the source details and mark the borrowed wording for quotation or careful paraphrase.", "Leave the text unchanged because the page is public.", "Delete the browser history so no one can find the page."],
        bestOption: "Record the source details and mark the borrowed wording for quotation or careful paraphrase.",
        explanation: "Traceable source details support accurate attribution and allow you to check the original context later.",
        nextStepByOption: { "Record the source details and mark the borrowed wording for quotation or careful paraphrase.": "review", "Leave the text unchanged because the page is public.": "capture-repair", "Delete the browser history so no one can find the page.": "capture-repair" },
      },
      {
        id: "capture-repair",
        title: "Restore traceability",
        situation: "Before sharing the draft, you notice that borrowed wording cannot be traced back to its source.",
        prompt: "What should happen before the draft moves forward?",
        options: ["Return to the original source, record its details, and clearly mark or revise the borrowed wording.", "Keep the wording because it is only for private study.", "Replace the source with an invented citation."],
        bestOption: "Return to the original source, record its details, and clearly mark or revise the borrowed wording.",
        explanation: "A short repair step restores accountability before the source is used in a draft.",
      },
      {
        id: "review",
        title: "Check the draft before sharing",
        situation: "The source details are now recorded and the wording has been revised. You are preparing to share the draft with a study partner for feedback.",
        prompt: "Which final check best supports responsible academic work?",
        options: ["Make it clear which ideas are yours and which are sourced, then ask for feedback on the argument.", "Remove every citation so the draft looks more original.", "Ask the study partner to submit the draft under their name."],
        bestOption: "Make it clear which ideas are yours and which are sourced, then ask for feedback on the argument.",
        explanation: "Clear attribution and a focused feedback request help improve the work without hiding the origin of ideas.",
      },
    ],
  },
  {
    id: "computing-accessible-events",
    packId: "computing-foundations",
    title: "Plan an accessible events page",
    eyebrow: "COMPUTING CASE",
    summary: "Turn user needs into requirements and an early test plan.",
    reflectionPrompt: "What user need would you put into the first version’s acceptance criteria?",
    steps: [
      {
        id: "requirements",
        title: "Set the requirements",
        situation: "A student team is planning a campus-events page. Users mention keyboard navigation and readable contrast, and the team has limited time for a first version.",
        prompt: "How should the team treat these needs?",
        options: ["Include them as requirements for the first version.", "Treat them as decoration to add after launch.", "Ask affected users to use another website."],
        bestOption: "Include them as requirements for the first version.",
        explanation: "Accessibility needs belong in the problem definition, not as optional decoration.",
        nextStepByOption: { "Include them as requirements for the first version.": "test", "Treat them as decoration to add after launch.": "requirements-repair", "Ask affected users to use another website.": "requirements-repair" },
      },
      {
        id: "test",
        title: "Choose an early test",
        situation: "The first page prototype now includes labeled controls and visible focus order. The team needs a short test before building more features.",
        prompt: "Which test is most useful now?",
        options: ["Navigate the page using a keyboard and check whether each control has a clear label and visible focus.", "Add more animations before any interaction test.", "Assume that a page is accessible if it works with a mouse."],
        bestOption: "Navigate the page using a keyboard and check whether each control has a clear label and visible focus.",
        explanation: "A small task-based test checks the specific requirements the team identified.",
      },
      {
        id: "requirements-repair",
        title: "Reframe the first version",
        situation: "The team has paused before building the page. It now needs to turn the reported needs into a workable first-version plan.",
        prompt: "What should the team add to its plan before moving forward?",
        options: ["Clear accessibility requirements and a small keyboard-navigation test.", "A promise to consider access only after all features are finished.", "A note that users should adapt to the design."],
        bestOption: "Clear accessibility requirements and a small keyboard-navigation test.",
        explanation: "The repair step reconnects the plan to the needs that were originally reported.",
      },
    ],
  },
  {
    id: "business-consent-campaign",
    packId: "business-foundations",
    title: "Plan a consent-aware campaign",
    eyebrow: "BUSINESS CASE",
    summary: "Use customer contact details consistently with their stated purpose.",
    boundaryNote: "This is a learning case, not legal advice.",
    reflectionPrompt: "What would you state clearly on a future sign-up form?",
    steps: [
      {
        id: "purpose",
        title: "Check the collection purpose",
        situation: "A team collected email addresses for event attendance. It now wants to send a separate promotional message about a new idea.",
        prompt: "What should the team do first?",
        options: ["Check the stated purpose and seek clear permission for the promotional use.", "Send the promotion because addresses were collected at an event.", "Publish the address list for others to use."],
        bestOption: "Check the stated purpose and seek clear permission for the promotional use.",
        explanation: "New uses should be consistent with what people were told when their details were collected.",
        nextStepByOption: { "Check the stated purpose and seek clear permission for the promotional use.": "message", "Send the promotion because addresses were collected at an event.": "purpose-repair", "Publish the address list for others to use.": "purpose-repair" },
      },
      {
        id: "purpose-repair",
        title: "Reset the contact plan",
        situation: "The proposed promotion does not match the purpose communicated when the addresses were collected.",
        prompt: "What is the responsible next step?",
        options: ["Pause the promotion and seek a clear opt-in for the new purpose before sending it.", "Send it once and explain later if anyone objects.", "Share the list with more groups to make the event worthwhile."],
        bestOption: "Pause the promotion and seek a clear opt-in for the new purpose before sending it.",
        explanation: "The repair path protects the original expectation before any new communication is considered.",
      },
      {
        id: "message",
        title: "Write the invitation",
        situation: "The team has a list of people who have clearly opted in to receive updates. It is drafting the first message.",
        prompt: "Which message feature best supports a respectful campaign?",
        options: ["State why the recipient is receiving it and provide a clear way to stop future updates.", "Hide the sender’s identity so the message looks more urgent.", "Reuse the list for unrelated groups without explanation."],
        bestOption: "State why the recipient is receiving it and provide a clear way to stop future updates.",
        explanation: "Clear purpose and respectful control help recipients understand and manage the communication.",
      },
    ],
  },
  {
    id: "engineering-layout-evidence",
    packId: "engineering-foundations",
    title: "Compare a study-area layout",
    eyebrow: "ENGINEERING CASE",
    summary: "Use constraints and relevant evidence before choosing a design direction.",
    boundaryNote: "This is a learning case, not engineering or safety approval.",
    reflectionPrompt: "Which constraint would you verify first in a similar design decision?",
    steps: [
      {
        id: "constraints",
        title: "Name what matters",
        situation: "Two study-area layouts fit the wall space. One is cheaper, while the other may be easier for users to reach. The group has not checked maintenance needs.",
        prompt: "What is the strongest next step?",
        options: ["List access, cost, maintenance, and space constraints before comparing the layouts.", "Choose the cheaper layout immediately.", "Choose the layout with the most colors."],
        bestOption: "List access, cost, maintenance, and space constraints before comparing the layouts.",
        explanation: "A responsible decision begins with explicit constraints instead of a single preference.",
        nextStepByOption: { "List access, cost, maintenance, and space constraints before comparing the layouts.": "evidence", "Choose the cheaper layout immediately.": "constraints-repair", "Choose the layout with the most colors.": "constraints-repair" },
      },
      {
        id: "constraints-repair",
        title: "Re-establish the constraints",
        situation: "The group notices that an early choice would ignore access and maintenance implications.",
        prompt: "How should the comparison be repaired before a layout is selected?",
        options: ["Write the relevant access, cost, maintenance, and space constraints, then compare both layouts against them.", "Keep the first choice because changing direction is inefficient.", "Ask only the person who prefers the chosen layout."],
        bestOption: "Write the relevant access, cost, maintenance, and space constraints, then compare both layouts against them.",
        explanation: "The repair makes the criteria visible before evidence is gathered or a direction is chosen.",
      },
      {
        id: "evidence",
        title: "Gather a relevant check",
        situation: "The group has listed its constraints and needs one fast evidence step before selecting a layout.",
        prompt: "Which check best fits the stated constraints?",
        options: ["Ask relevant users about reach and ask facilities staff about maintenance implications.", "Build both permanent layouts before gathering feedback.", "Use a random choice to avoid bias."],
        bestOption: "Ask relevant users about reach and ask facilities staff about maintenance implications.",
        explanation: "Relevant input helps compare the options against the constraints the group has already stated.",
      },
    ],
  },
  {
    id: "science-observation-cycle",
    packId: "natural-sciences-foundations",
    title: "Handle an unexpected observation",
    eyebrow: "NATURAL SCIENCES CASE",
    summary: "Move from one unexpected value to a careful, documented next observation.",
    reflectionPrompt: "What condition would you record before repeating a classroom observation?",
    steps: [
      {
        id: "record",
        title: "Record the conditions",
        situation: "A classroom measurement includes one unexpected value. The learner cannot tell whether the reading was stable and the method notes are incomplete.",
        prompt: "What should happen before a conclusion is drawn?",
        options: ["Record the conditions and uncertainty surrounding the value.", "Treat the value as final proof of a new explanation.", "Delete the value without noting that it occurred."],
        bestOption: "Record the conditions and uncertainty surrounding the value.",
        explanation: "Transparent notes preserve the observation while avoiding an unsupported conclusion.",
        nextStepByOption: { "Record the conditions and uncertainty surrounding the value.": "repeat", "Treat the value as final proof of a new explanation.": "record-repair", "Delete the value without noting that it occurred.": "record-repair" },
      },
      {
        id: "record-repair",
        title: "Recover the observation record",
        situation: "The unexpected value has not been documented with enough context to interpret it responsibly.",
        prompt: "What should be recorded before repeating the classroom procedure?",
        options: ["Note the observed value, method conditions, and uncertainty instead of treating it as proof or erasing it.", "Change the recorded value so it matches the expected pattern.", "Conclude that the result is meaningless without keeping notes."],
        bestOption: "Note the observed value, method conditions, and uncertainty instead of treating it as proof or erasing it.",
        explanation: "Documenting both the value and the conditions preserves a transparent basis for a later repeat.",
      },
      {
        id: "repeat",
        title: "Repeat carefully",
        situation: "The method notes are now complete and the learner can repeat the same classroom procedure.",
        prompt: "What is the most useful next action?",
        options: ["Repeat the observation using the stated method and compare the recorded results.", "Choose the value that best matches an expected answer.", "Change several conditions at once without recording them."],
        bestOption: "Repeat the observation using the stated method and compare the recorded results.",
        explanation: "Careful repetition helps distinguish a one-time observation from a supported pattern.",
      },
    ],
  },
  {
    id: "education-inclusive-check",
    packId: "education-foundations",
    title: "Design an inclusive learning check",
    eyebrow: "EDUCATION CASE",
    summary: "Keep one learning objective while offering fair ways to show understanding.",
    reflectionPrompt: "How would you explain the same success criterion to learners using different response formats?",
    steps: [
      {
        id: "objective",
        title: "Keep the objective central",
        situation: "A tutor wants to check whether learners can explain the main idea from a lesson. Some learners prefer a short spoken response and others prefer writing.",
        prompt: "Which plan keeps the check connected to the objective?",
        options: ["Allow an appropriate spoken or written response using the same clear success criteria.", "Require one format only because different formats cannot show the same learning.", "Skip the learning check entirely."],
        bestOption: "Allow an appropriate spoken or written response using the same clear success criteria.",
        explanation: "Multiple response formats can be fair when they are evaluated against the same relevant objective.",
        nextStepByOption: { "Allow an appropriate spoken or written response using the same clear success criteria.": "feedback", "Require one format only because different formats cannot show the same learning.": "objective-repair", "Skip the learning check entirely.": "objective-repair" },
      },
      {
        id: "objective-repair",
        title: "Reconnect format and objective",
        situation: "The tutor recognizes that the planned response rule would measure format preference rather than the intended learning.",
        prompt: "What adjustment keeps the learning check fair and focused?",
        options: ["Use the same clear success criteria for an appropriate spoken or written response.", "Score learners only on how quickly they respond.", "Remove the criterion so any response receives the same result."],
        bestOption: "Use the same clear success criteria for an appropriate spoken or written response.",
        explanation: "The repair path restores a single objective while allowing a relevant way to demonstrate understanding.",
      },
      {
        id: "feedback",
        title: "Use the response well",
        situation: "Learners have responded in their chosen format. The tutor is deciding how to use the answers.",
        prompt: "What feedback action is most useful?",
        options: ["Compare each response to the success criteria and name one next improvement.", "Rank learners by response speed only.", "Give identical feedback without looking at the objective."],
        bestOption: "Compare each response to the success criteria and name one next improvement.",
        explanation: "Objective-linked feedback helps learners understand what they achieved and what to improve.",
      },
    ],
  },
  {
    id: "social-context-inquiry",
    packId: "social-sciences-foundations",
    title: "Develop a context-sensitive inquiry",
    eyebrow: "SOCIAL SCIENCES CASE",
    summary: "Use individual perspectives to form a careful question without overgeneralizing.",
    reflectionPrompt: "What extra context would you want before interpreting a similar set of comments?",
    steps: [
      {
        id: "interpret",
        title: "Interpret carefully",
        situation: "A learner reads three anonymous comments about long travel times to campus. There is no information about routes, work schedules, costs, or the wider student population.",
        prompt: "Which interpretation is most responsible?",
        options: ["Treat the comments as useful perspectives that suggest a broader question for study.", "Use the comments to prove every learner experiences the same problem.", "Identify the authors publicly to verify the comments."],
        bestOption: "Treat the comments as useful perspectives that suggest a broader question for study.",
        explanation: "Individual perspectives can inform inquiry, but responsible interpretation avoids overgeneralizing and respects privacy.",
        nextStepByOption: { "Treat the comments as useful perspectives that suggest a broader question for study.": "question", "Use the comments to prove every learner experiences the same problem.": "interpret-repair", "Identify the authors publicly to verify the comments.": "interpret-repair" },
      },
      {
        id: "interpret-repair",
        title: "Reframe the evidence",
        situation: "The learner notices that a few anonymous comments cannot establish the experience of an entire student population.",
        prompt: "How should the initial interpretation be repaired?",
        options: ["Keep the comments anonymous and treat them as perspectives that point to a broader contextual question.", "Publish the comments with guesses about who wrote them.", "State that every learner has the same travel experience."],
        bestOption: "Keep the comments anonymous and treat them as perspectives that point to a broader contextual question.",
        explanation: "The repair protects privacy and returns the inquiry to an evidence-appropriate claim.",
      },
      {
        id: "question",
        title: "Frame the next question",
        situation: "The learner now wants to investigate travel experiences in a respectful way.",
        prompt: "Which question best follows from the limited comments?",
        options: ["How do route availability, schedules, cost, and study commitments shape travel experiences for different learners?", "Which single learner is responsible for the travel problem?", "How can comments be used to label all learners the same way?"],
        bestOption: "How do route availability, schedules, cost, and study commitments shape travel experiences for different learners?",
        explanation: "The question seeks relevant context rather than treating a few comments as a complete explanation.",
      },
    ],
  },
  {
    id: "uganda-biology-garden-inquiry",
    packId: "uganda-high-school-biology",
    title: "Plan a garden observation inquiry",
    eyebrow: "HIGH SCHOOL BIOLOGY CASE",
    summary: "Turn a school-garden observation into a careful question and a recordable comparison.",
    boundaryNote: "Learning case only; follow school fieldwork, laboratory, and safeguarding guidance.",
    reflectionPrompt: "What condition would you record before comparing a similar biological observation?",
    steps: [
      {
        id: "observation",
        title: "Keep the observation separate",
        situation: "In a school garden, leaves from plants in one corner appear darker than leaves from similar plants elsewhere. The learner has not recorded soil moisture, plant age, or exact light conditions.",
        prompt: "What is the strongest first response?",
        options: ["Record the visible difference and identify the conditions that still need comparison.", "Conclude that shade alone caused the colour difference.", "Remove the darker leaves so the plants match."],
        bestOption: "Record the visible difference and identify the conditions that still need comparison.",
        explanation: "The visible difference is useful evidence, but the learner needs relevant conditions before selecting an explanation.",
        nextStepByOption: { "Record the visible difference and identify the conditions that still need comparison.": "comparison", "Conclude that shade alone caused the colour difference.": "observation-repair", "Remove the darker leaves so the plants match.": "observation-repair" },
      },
      {
        id: "observation-repair",
        title: "Rebuild the observation record",
        situation: "The learner notices that a quick explanation would go beyond the details that were actually recorded.",
        prompt: "What should happen before an explanation is chosen?",
        options: ["Write down the observation and list relevant conditions to compare before making a claim.", "Choose the explanation that sounds most familiar.", "Ignore all differences because one observation cannot matter."],
        bestOption: "Write down the observation and list relevant conditions to compare before making a claim.",
        explanation: "The repair keeps the record useful while avoiding an unsupported conclusion.",
      },
      {
        id: "comparison",
        title: "Plan a careful comparison",
        situation: "The learner has listed relevant conditions and wants a simple next observation plan.",
        prompt: "Which plan best supports a fair comparison?",
        options: ["Use the same observation method for similar plants and record the selected conditions consistently.", "Change several conditions at once without noting them.", "Record only leaves that match the expected pattern."],
        bestOption: "Use the same observation method for similar plants and record the selected conditions consistently.",
        explanation: "Consistent observations and clear notes make later reasoning more dependable.",
      },
    ],
  },
  {
    id: "uganda-chemistry-variable-plan",
    packId: "uganda-high-school-chemistry",
    title: "Plan a fair chemistry comparison",
    eyebrow: "HIGH SCHOOL CHEMISTRY CASE",
    summary: "Use a clear comparison question, stated conditions, and a transparent record.",
    boundaryNote: "Learning case only; teacher instructions and school laboratory rules take priority.",
    reflectionPrompt: "What would you keep consistent in a future classroom comparison?",
    steps: [
      {
        id: "focus",
        title: "Choose one focus",
        situation: "A learner is preparing a teacher-supervised classroom activity and proposes changing the amount of material, container, and observation time at the same time.",
        prompt: "What should the learner do first?",
        options: ["Choose one main condition to compare and state what will be observed consistently.", "Change every condition at once to make the result more interesting.", "Decide the expected result before recording anything."],
        bestOption: "Choose one main condition to compare and state what will be observed consistently.",
        explanation: "A focused comparison is easier to interpret when the learner identifies the main condition and a consistent observation method.",
        nextStepByOption: { "Choose one main condition to compare and state what will be observed consistently.": "record", "Change every condition at once to make the result more interesting.": "focus-repair", "Decide the expected result before recording anything.": "focus-repair" },
      },
      {
        id: "focus-repair",
        title: "Restore a useful question",
        situation: "The proposed activity would not make it clear which changed condition might relate to the observation.",
        prompt: "How should the plan be repaired?",
        options: ["State one comparison focus and plan a consistent way to record the observation.", "Keep every change because results are more important than the method.", "Avoid recording the conditions to save time."],
        bestOption: "State one comparison focus and plan a consistent way to record the observation.",
        explanation: "The repair makes the comparison question and record clear before the activity continues.",
      },
      {
        id: "record",
        title: "Use a transparent record",
        situation: "The learner has a focused comparison question and a teacher-approved classroom procedure.",
        prompt: "Which record supports careful interpretation?",
        options: ["Record the stated conditions and each observation, including an unexpected result.", "Keep only observations that match an expected pattern.", "Write a conclusion without noting the observations."],
        bestOption: "Record the stated conditions and each observation, including an unexpected result.",
        explanation: "A complete record supports discussion of the evidence instead of selecting only convenient results.",
      },
    ],
  },
  {
    id: "uganda-economics-budget-tradeoff",
    packId: "uganda-high-school-economics",
    title: "Compare a club-budget trade-off",
    eyebrow: "HIGH SCHOOL ECONOMICS CASE",
    summary: "Make a limited-resource choice by naming the alternatives, evidence, and trade-off.",
    boundaryNote: "Learning case only; this is not personal, business, or financial advice.",
    reflectionPrompt: "What information would you compare before explaining a similar budget choice?",
    steps: [
      {
        id: "tradeoff",
        title: "Make the alternatives visible",
        situation: "A school club has a limited amount left for the term. It can buy materials for one activity now or keep the funds for a planned future need, but cannot fully fund both choices.",
        prompt: "What should the group do first?",
        options: ["List the purpose, cost, and benefit of each option, then name what is given up with either choice.", "Choose the option suggested by the loudest group member.", "Say there is no trade-off because both options are useful."],
        bestOption: "List the purpose, cost, and benefit of each option, then name what is given up with either choice.",
        explanation: "A trade-off becomes clearer when the group compares the alternatives against its limited resources and stated purpose.",
        nextStepByOption: { "List the purpose, cost, and benefit of each option, then name what is given up with either choice.": "explain", "Choose the option suggested by the loudest group member.": "tradeoff-repair", "Say there is no trade-off because both options are useful.": "tradeoff-repair" },
      },
      {
        id: "tradeoff-repair",
        title: "Return to the recorded evidence",
        situation: "The group sees that an early choice would hide the limited budget and the alternative being forgone.",
        prompt: "What should be added before a decision is explained?",
        options: ["A comparison of the stated costs, purposes, and trade-offs for both options.", "A promise that one option will benefit every person equally.", "A rule that no one may ask about the budget."],
        bestOption: "A comparison of the stated costs, purposes, and trade-offs for both options.",
        explanation: "The repair reconnects the choice to the available evidence and the limited-resource constraint.",
      },
      {
        id: "explain",
        title: "Explain the chosen option",
        situation: "The group has compared both options and is ready to write a short decision note.",
        prompt: "Which note uses the comparison most responsibly?",
        options: ["State the selected option, the main reason, and the relevant trade-off that the group accepts.", "Claim the choice has no disadvantages for anyone.", "Hide the alternative so the decision seems automatic."],
        bestOption: "State the selected option, the main reason, and the relevant trade-off that the group accepts.",
        explanation: "A transparent explanation connects the decision to the evidence and acknowledges what is given up.",
      },
    ],
  },
  {
    id: "uganda-entrepreneurship-feedback-plan",
    packId: "uganda-high-school-entrepreneurship",
    title: "Test an idea respectfully",
    eyebrow: "HIGH SCHOOL ENTREPRENEURSHIP CASE",
    summary: "Turn an early learner idea into an ethical, evidence-seeking feedback plan.",
    boundaryNote: "Learning case only; this is not legal, business, or investment advice.",
    reflectionPrompt: "What would you ask people before using feedback about a future idea?",
    steps: [
      {
        id: "purpose",
        title: "State the feedback purpose",
        situation: "A learner wants feedback on a small school-based idea. A friend suggests collecting classmates’ contact details from a group chat and sending repeated messages without explaining the reason.",
        prompt: "What is the responsible first step?",
        options: ["Explain the learning purpose, invite voluntary feedback, and collect only what is needed.", "Use the contact details immediately because the idea is small.", "Share the contact details with more learners to get faster responses."],
        bestOption: "Explain the learning purpose, invite voluntary feedback, and collect only what is needed.",
        explanation: "Respectful feedback starts with a clear purpose, voluntary participation, and minimal personal information.",
        nextStepByOption: { "Explain the learning purpose, invite voluntary feedback, and collect only what is needed.": "review", "Use the contact details immediately because the idea is small.": "purpose-repair", "Share the contact details with more learners to get faster responses.": "purpose-repair" },
      },
      {
        id: "purpose-repair",
        title: "Reset the feedback plan",
        situation: "The learner recognises that the proposed contact method would not clearly respect classmates’ choices.",
        prompt: "What should change before feedback is requested?",
        options: ["Use a clear voluntary invitation that explains the purpose and avoids unnecessary personal details.", "Message people repeatedly until they answer.", "Record only positive opinions about the idea."],
        bestOption: "Use a clear voluntary invitation that explains the purpose and avoids unnecessary personal details.",
        explanation: "The repair protects people’s choice and makes the feedback process more trustworthy.",
      },
      {
        id: "review",
        title: "Use mixed feedback well",
        situation: "The learner now has a small set of voluntary comments, including positive questions and concerns.",
        prompt: "Which response makes the feedback useful?",
        options: ["Group the comments by recurring needs or concerns and identify one question to investigate next.", "Discard comments that do not praise the idea.", "Treat a few comments as proof that every customer will buy."],
        bestOption: "Group the comments by recurring needs or concerns and identify one question to investigate next.",
        explanation: "Mixed feedback can guide the next question without being treated as a final market conclusion.",
      },
    ],
  },
  {
    id: "uganda-english-source-draft",
    packId: "uganda-high-school-english",
    title: "Prepare a clear sourced paragraph",
    eyebrow: "HIGH SCHOOL ENGLISH CASE",
    summary: "Move from a useful online idea to a traceable, reader-friendly class paragraph.",
    boundaryNote: "Learning case only; use your school’s guidance for formal assignments and assessment.",
    reflectionPrompt: "What source detail will you capture before using an online idea in future writing?",
    steps: [
      {
        id: "source",
        title: "Capture the source first",
        situation: "A learner finds a useful online explanation while drafting a class paragraph. A sentence has been copied into the draft, but the page title, author, and link have not been recorded.",
        prompt: "What should happen before the draft is shared?",
        options: ["Record the source details and decide whether to quote or paraphrase the idea clearly.", "Keep the sentence because online writing does not need a source.", "Remove all source details so the paragraph looks more original."],
        bestOption: "Record the source details and decide whether to quote or paraphrase the idea clearly.",
        explanation: "Capturing details and making source use clear helps a reader understand where wording or ideas came from.",
        nextStepByOption: { "Record the source details and decide whether to quote or paraphrase the idea clearly.": "revision", "Keep the sentence because online writing does not need a source.": "source-repair", "Remove all source details so the paragraph looks more original.": "source-repair" },
      },
      {
        id: "source-repair",
        title: "Restore traceable source use",
        situation: "The learner notices that a copied sentence cannot be checked against the original page.",
        prompt: "What is the best repair before the paragraph continues?",
        options: ["Return to the original page, record its details, and revise the draft to show the source use clearly.", "Invent a source name so the paragraph looks complete.", "Submit the paragraph without a source check."],
        bestOption: "Return to the original page, record its details, and revise the draft to show the source use clearly.",
        explanation: "The repair restores a clear trail to the original context before the learner develops the paragraph.",
      },
      {
        id: "revision",
        title: "Check the paragraph for a reader",
        situation: "The learner has recorded the source and has drafted a clear claim with a supporting detail.",
        prompt: "Which revision check is most useful now?",
        options: ["Check that the claim is specific, the support relates to it, and the source use is clear to a reader.", "Add more dramatic words without checking the meaning.", "Remove the supporting detail so the paragraph becomes shorter."],
        bestOption: "Check that the claim is specific, the support relates to it, and the source use is clear to a reader.",
        explanation: "A focused revision check improves clarity, support, and responsible source use at the same time.",
      },
    ],
  },
];

export function caseChainForPack(packId: string): CourseCaseChain | null {
  return COURSE_CASE_CHAINS.find((chain) => chain.packId === packId) ?? null;
}

export function caseChainForId(chainId: string): CourseCaseChain | null {
  return COURSE_CASE_CHAINS.find((chain) => chain.id === chainId) ?? null;
}
