import type { HighSchoolLevel } from "../lib/high-school-store";

export type HighSchoolTopicBand = "foundation" | "development" | "extension" | "all_levels";
export type HighSchoolTopicMode = "evidence" | "reasoning" | "decision" | "reflection";

export type HighSchoolTopicUnit = {
  id: string;
  packId: string;
  topicId: string;
  title: string;
  band: HighSchoolTopicBand;
  mode: HighSchoolTopicMode;
  cue: string;
  prompt: string;
  options?: readonly string[];
  bestOption?: string;
  explanation: string;
  reflectionPrompt?: string;
  boundaryNote?: string;
};

/**
 * Original Rounds topic units are intentionally separate from the reviewed
 * starter activities. The catalogue is extended per subject without copying
 * external curriculum wording or claiming examination alignment.
 */
function topicUnit(
  id: string,
  packId: string,
  topicId: string,
  title: string,
  band: Exclude<HighSchoolTopicBand, "all_levels">,
  mode: Exclude<HighSchoolTopicMode, "reflection">,
  cue: string,
  prompt: string,
  options: readonly string[],
  bestOption: string,
  explanation: string,
  boundaryNote?: string,
): HighSchoolTopicUnit {
  return { id, packId, topicId, title, band, mode, cue, prompt, options, bestOption, explanation, boundaryNote };
}

function reflectionCompanion(unit: HighSchoolTopicUnit): HighSchoolTopicUnit {
  return {
    id: `${unit.id}-reflection`,
    packId: unit.packId,
    topicId: `${unit.topicId}-reflection`,
    title: `Reflect on ${unit.title.toLowerCase()}`,
    band: unit.band,
    mode: "reflection",
    cue: "PRIVATE REFLECTION",
    prompt: "Pause and write one short private note about the study move you would use next time.",
    explanation: "Private reflection helps you notice a useful study move without asking Rounds to judge a personal response.",
    reflectionPrompt: `What is one question, check, or strategy you would carry forward from “${unit.title}”?`,
    boundaryNote: unit.boundaryNote,
  };
}

const CORE_TOPIC_UNITS: readonly HighSchoolTopicUnit[] = [
  topicUnit("biology-living-systems-foundation", "uganda-high-school-biology", "living-systems", "Observe living systems", "foundation", "evidence", "BIOLOGY · FOUNDATION", "A classroom observation notes that a plant bends toward a window over several days. Which statement stays closest to the stated observation?", ["The plant changed its direction toward the window during the stated observation.", "The observation proves one cause in every setting.", "Plants never change direction.", "The observation gives no information at all."], "The plant changed its direction toward the window during the stated observation.", "The stated observation supports a careful description before a broader explanation is considered."),
  topicUnit("biology-variables-development", "uganda-high-school-biology", "variables-and-evidence", "Compare biological variables", "development", "reasoning", "BIOLOGY · DEVELOPMENT", "Two classroom groups observe the same kind of seedling but record different light conditions. What is the clearest next reasoning step?", ["Compare the stated light condition while keeping track of other recorded differences.", "Assume one observation proves every condition is irrelevant.", "Ignore the written records.", "Treat a guess as a measured result."], "Compare the stated light condition while keeping track of other recorded differences.", "Careful comparison identifies what differs and what else must be considered before drawing a conclusion."),
  topicUnit("biology-explanation-extension", "uganda-high-school-biology", "explanation-limits", "Explain with limits", "extension", "decision", "BIOLOGY · EXTENSION", "A learner wants to turn one short observation into a broad claim about every organism. What is the strongest response?", ["State the observation, explain a possible pattern, and name what further evidence would be needed.", "Declare the broad claim proven immediately.", "Remove any observation that seems different.", "Replace the record with a personal opinion."], "State the observation, explain a possible pattern, and name what further evidence would be needed.", "A stronger explanation connects evidence to a possible pattern and makes its limits visible."),

  topicUnit("chemistry-particle-description-foundation", "uganda-high-school-chemistry", "particle-descriptions", "Describe a stated change", "foundation", "evidence", "CHEMISTRY · FOUNDATION", "A classroom note says that a solid sample was warmed and later appeared as a liquid. Which statement is supported by the note?", ["The stated sample changed from the recorded solid appearance to a liquid appearance.", "The note proves the identity of every substance involved.", "Warming never changes observations.", "No change was recorded."], "The stated sample changed from the recorded solid appearance to a liquid appearance.", "The note supports a description of the recorded change without adding unstated details."),
  topicUnit("chemistry-pattern-comparison-development", "uganda-high-school-chemistry", "patterns-and-variables", "Compare a stated pattern", "development", "reasoning", "CHEMISTRY · DEVELOPMENT", "Two classroom samples are described with the same starting amount but different stated conditions. What should a learner do before explaining a difference?", ["Compare the recorded conditions and identify which details are missing.", "Assume the result has one cause without checking conditions.", "Ignore the starting information.", "Rename the samples instead of using the record."], "Compare the recorded conditions and identify which details are missing.", "A useful chemical explanation begins with the stated conditions and the limits of the available record."),
  topicUnit("chemistry-claim-check-extension", "uganda-high-school-chemistry", "claim-checking", "Check a chemistry claim", "extension", "decision", "CHEMISTRY · EXTENSION", "A message claims that a classroom observation proves a product is always safe in every circumstance. What is the strongest study response?", ["Separate the observation from the safety claim and ask what evidence the claim would require.", "Share the claim as a universal conclusion.", "Treat a label as a complete safety instruction.", "Ignore the difference between a class task and a real-world decision."], "Separate the observation from the safety claim and ask what evidence the claim would require.", "The response distinguishes classroom evidence from a broad safety claim and keeps practical decisions outside the activity."),

  topicUnit("economics-scarcity-foundation", "uganda-high-school-economics", "scarcity-and-choice", "Recognise a trade-off", "foundation", "evidence", "ECONOMICS · FOUNDATION", "A class club has a fixed amount of funds and lists two useful materials it cannot both buy in full. What does the situation show?", ["A choice is needed because the stated resources are limited.", "The club has unlimited resources.", "Both materials cost nothing.", "No decision is involved."], "A choice is needed because the stated resources are limited.", "Scarcity means a learner or group must make choices when stated resources are limited."),
  topicUnit("economics-comparison-development", "uganda-high-school-economics", "comparisons-and-reasons", "Compare stated choices", "development", "reasoning", "ECONOMICS · DEVELOPMENT", "A learner compares two class-project choices. Which approach gives the clearest economic reasoning?", ["Name the stated benefit and what is given up for each choice.", "Name only the preferred choice with no reason.", "Pretend one choice has no trade-off.", "Use a rumour instead of the project details."], "Name the stated benefit and what is given up for each choice.", "A comparison is stronger when it explains both a stated benefit and an acknowledged trade-off."),
  topicUnit("economics-claim-limits-extension", "uganda-high-school-economics", "claims-and-limits", "Limit an economic conclusion", "extension", "decision", "ECONOMICS · EXTENSION", "A class survey has a small stated response group. A learner wants to make a claim about all families. What is the strongest response?", ["Describe what the stated responses show and explain why a wider claim would need more evidence.", "Say the small group proves every family behaves the same way.", "Discard responses that differ.", "Turn the survey into personal financial advice."], "Describe what the stated responses show and explain why a wider claim would need more evidence.", "A responsible conclusion matches the claim to the evidence and avoids personal financial direction."),

  topicUnit("entrepreneurship-customer-foundation", "uganda-high-school-entrepreneurship", "customer-evidence", "Read customer feedback", "foundation", "evidence", "ENTREPRENEURSHIP · FOUNDATION", "A class project receives one comment asking for clearer collection times. Which statement is supported?", ["One stated commenter wants clearer collection-time information.", "Every customer wants exactly the same thing.", "The comment proves the project will succeed.", "The comment gives no information."], "One stated commenter wants clearer collection-time information.", "One comment can identify a possible question to explore without proving what every customer wants."),
  topicUnit("entrepreneurship-testing-development", "uganda-high-school-entrepreneurship", "testing-and-records", "Plan a simple test", "development", "reasoning", "ENTREPRENEURSHIP · DEVELOPMENT", "A learner wants to change a class-project message after two different comments. What is the strongest next step?", ["Record the comments, state a small test, and compare the response before making a broader change.", "Change everything without recording why.", "Ignore the comments because they differ.", "Promise a business outcome to classmates."], "Record the comments, state a small test, and compare the response before making a broader change.", "A small recorded test helps learners compare feedback without treating a class project as a guarantee."),
  topicUnit("entrepreneurship-ethical-choice-extension", "uganda-high-school-entrepreneurship", "ethical-choices", "Choose an ethical project response", "extension", "decision", "ENTREPRENEURSHIP · EXTENSION", "A class project can make a claim that sounds impressive but cannot be supported by its records. What is the strongest next step?", ["Use a clear, supportable description and name what the project still needs to check.", "Make the unsupported claim to attract attention.", "Hide the missing record.", "Tell classmates how to spend personal money."], "Use a clear, supportable description and name what the project still needs to check.", "Responsible project communication does not use unsupported claims or become personal financial advice."),

  topicUnit("english-main-idea-foundation", "uganda-high-school-english", "main-idea-and-detail", "Identify a supported main idea", "foundation", "evidence", "ENGLISH · FOUNDATION", "A short paragraph states that a reading group meets weekly, shares one question, and records one useful idea. Which main idea is best supported?", ["The group uses a regular process for shared reading and discussion.", "Every learner already agrees on every text.", "The group never records ideas.", "The paragraph proves reading is easy for everyone."], "The group uses a regular process for shared reading and discussion.", "A main idea connects the stated details without making a broader claim the paragraph does not support."),
  topicUnit("english-argument-development", "uganda-high-school-english", "claims-and-reasons", "Connect a claim to a reason", "development", "reasoning", "ENGLISH · DEVELOPMENT", "A learner writes, ‘The library should extend its opening time,’ but gives no stated reason. What would make the argument clearer?", ["Add a relevant reason and a detail that supports it.", "Repeat the claim more loudly.", "Add an unrelated personal attack.", "Remove the reader’s context."], "Add a relevant reason and a detail that supports it.", "An argument becomes clearer when the claim is connected to a relevant reason and support."),
  topicUnit("english-revision-extension", "uganda-high-school-english", "revision-and-audience", "Revise for an audience", "extension", "decision", "ENGLISH · EXTENSION", "A learner drafts a school notice with a clear purpose but no next step for readers. What is the strongest revision?", ["Add the specific action, time, or response the reader needs while keeping the purpose clear.", "Remove all useful details.", "Add complex words without a purpose.", "Use private details about other learners."], "Add the specific action, time, or response the reader needs while keeping the purpose clear.", "Audience-aware revision helps readers understand what matters and what they should do next."),

  topicUnit("physics-motion-foundation", "uganda-high-school-physics", "motion-observations", "Describe a motion record", "foundation", "evidence", "PHYSICS · FOUNDATION", "A classroom record says a trolley travelled 2 metres in one stated interval and 4 metres in the next equal interval. Which statement is supported?", ["The record shows different stated distances across the two equal intervals.", "The record proves every trolley behaves the same way.", "The trolley did not move.", "The distances are identical."], "The record shows different stated distances across the two equal intervals.", "A motion record supports a careful description of stated distances before explaining why they differ."),
  topicUnit("physics-measurement-development", "uganda-high-school-physics", "measurement-and-patterns", "Compare measurements", "development", "reasoning", "PHYSICS · DEVELOPMENT", "Two groups record different measurements for the same classroom object. What is the strongest first reasoning step?", ["Check the stated units, method, and recorded conditions before choosing an explanation.", "Select the larger number without checking.", "Assume one group was careless without evidence.", "Ignore units."], "Check the stated units, method, and recorded conditions before choosing an explanation.", "Measurement reasoning depends on units, method, and the limits of the stated record."),
  topicUnit("physics-model-limits-extension", "uganda-high-school-physics", "models-and-limits", "Limit a physical model", "extension", "decision", "PHYSICS · EXTENSION", "A learner uses a simple classroom model to explain a pattern and wants to claim that the model captures every real situation. What is the strongest response?", ["Explain what the model represents and name a feature it may not capture.", "Treat the model as identical to every real situation.", "Remove any difference from discussion.", "Use the model as a safety instruction."], "Explain what the model represents and name a feature it may not capture.", "Models can be useful while still having stated limits; a classroom model is not a safety instruction."),

  topicUnit("mathematics-pattern-foundation", "uganda-high-school-mathematics", "patterns-and-rules", "Read a stated pattern", "foundation", "evidence", "MATHEMATICS · FOUNDATION", "A number pattern is shown as 4, 7, 10, 13. Which next value follows the stated pattern?", ["16", "15", "17", "18"], "16", "The stated pattern increases by 3 each time, so 13 + 3 gives 16."),
  topicUnit("mathematics-representation-development", "uganda-high-school-mathematics", "representations-and-checks", "Choose a useful representation", "development", "reasoning", "MATHEMATICS · DEVELOPMENT", "A learner has a table of values and wants to see whether a change is steady. What is the strongest next step?", ["Organise the values clearly and compare the stated differences between consecutive entries.", "Choose an answer before looking at the table.", "Remove values that do not fit a guess.", "Treat a drawing as exact without a scale."], "Organise the values clearly and compare the stated differences between consecutive entries.", "A structured representation makes the stated pattern easier to check rather than guess."),
  topicUnit("mathematics-justification-extension", "uganda-high-school-mathematics", "justification-and-limits", "Justify a mathematical conclusion", "extension", "decision", "MATHEMATICS · EXTENSION", "A learner gets a numerical result but cannot explain the steps or units. What is the strongest response?", ["Show the stated steps, check the units, and explain what the result represents in the classroom problem.", "Keep only the final number.", "Change units to make the number look better.", "Use the result as professional financial advice."], "Show the stated steps, check the units, and explain what the result represents in the classroom problem.", "A justified result shows the calculation path, appropriate units, and the limits of its classroom context."),

  topicUnit("geography-map-foundation", "uganda-high-school-geography", "maps-and-place", "Read a stated map detail", "foundation", "evidence", "GEOGRAPHY · FOUNDATION", "A classroom map key marks a blue line as a river and a black line as a road. Which statement is supported?", ["The key identifies the stated blue line as a river and black line as a road.", "The map proves every nearby settlement is identical.", "The key gives no information.", "A road and river are the same feature."], "The key identifies the stated blue line as a river and black line as a road.", "A map key supports careful description of the symbols it defines."),
  topicUnit("geography-data-development", "uganda-high-school-geography", "data-and-comparison", "Compare geographic records", "development", "reasoning", "GEOGRAPHY · DEVELOPMENT", "Two stated rainfall records differ across months. What is the strongest next reasoning step?", ["Compare the recorded months, amounts, and any stated collection limits before explaining a pattern.", "Say one month proves a permanent climate rule.", "Ignore the time labels.", "Use the record to predict every future season with certainty."], "Compare the recorded months, amounts, and any stated collection limits before explaining a pattern.", "Geographic reasoning compares stated records and does not turn a small record into a permanent conclusion."),
  topicUnit("geography-environment-extension", "uganda-high-school-geography", "environmental-claims", "Check an environmental claim", "extension", "decision", "GEOGRAPHY · EXTENSION", "A learner sees a claim that one local observation proves an environmental change affects every place in the same way. What is the strongest response?", ["Describe the local evidence, ask what wider records are needed, and note that places may differ.", "Share the claim as a universal fact.", "Ignore all place differences.", "Use the observation as an official fieldwork instruction."], "Describe the local evidence, ask what wider records are needed, and note that places may differ.", "The response respects local evidence while recognising that wider geographic claims need wider support."),

  topicUnit("history-source-foundation", "uganda-high-school-history-civics", "sources-and-statements", "Read a historical source statement", "foundation", "evidence", "HISTORY AND CIVICS · FOUNDATION", "A classroom source says that a meeting was held in a stated year. Which statement is supported?", ["The source states that a meeting was held in that year.", "The source proves every person agreed at the meeting.", "The source gives no date information.", "The source proves all later events."], "The source states that a meeting was held in that year.", "A source can support what it states without proving every wider conclusion about the event."),
  topicUnit("history-corroboration-development", "uganda-high-school-history-civics", "corroboration-and-timelines", "Compare source accounts", "development", "reasoning", "HISTORY AND CIVICS · DEVELOPMENT", "Two classroom sources describe the same event from different viewpoints. What is the strongest next step?", ["Compare what each source states, who produced it, and what further evidence could clarify differences.", "Choose one source because it is shorter.", "Remove the source that differs.", "Assume viewpoint makes all evidence useless."], "Compare what each source states, who produced it, and what further evidence could clarify differences.", "Historical reasoning compares accounts and considers what each one can and cannot establish."),
  topicUnit("civics-process-extension", "uganda-high-school-history-civics", "civic-processes", "Choose a respectful civic process", "extension", "decision", "HISTORY AND CIVICS · EXTENSION", "A class wants to raise a school-community issue but learners disagree about the next step. What is the strongest response?", ["Use a respectful process, identify stated evidence, and follow school guidance for the next discussion step.", "Silence learners with a different view.", "Share private details about classmates.", "Treat a class discussion as political instruction."], "Use a respectful process, identify stated evidence, and follow school guidance for the next discussion step.", "Civic learning can practise respectful evidence-aware process without giving political direction."),

  topicUnit("ict-information-foundation", "uganda-high-school-ict", "digital-information", "Read a digital source detail", "foundation", "evidence", "ICT AND DIGITAL SKILLS · FOUNDATION", "A classroom webpage shows an author name, a date, and a claim. Which statement is supported?", ["The page provides a stated author name and date alongside its claim.", "The claim is automatically true because it is online.", "The page has no source details.", "Every online page has the same reliability."], "The page provides a stated author name and date alongside its claim.", "Digital literacy begins with noticing stated source details before judging a claim."),
  topicUnit("ict-data-development", "uganda-high-school-ict", "data-and-privacy", "Plan a responsible data check", "development", "reasoning", "ICT AND DIGITAL SKILLS · DEVELOPMENT", "A class survey includes names even though a summary can be made without them. What is the strongest next reasoning step?", ["Ask whether names are needed for the stated class purpose and use teacher guidance before collecting extra details.", "Collect every possible detail by default.", "Share responses in a group chat.", "Assume classmates have no privacy interests."], "Ask whether names are needed for the stated class purpose and use teacher guidance before collecting extra details.", "Responsible digital work considers what information is necessary and protects learner privacy."),
  topicUnit("ict-claim-extension", "uganda-high-school-ict", "digital-claims-and-actions", "Respond to a digital claim", "extension", "decision", "ICT AND DIGITAL SKILLS · EXTENSION", "A post urges learners to forward a dramatic claim immediately but gives no source. What is the strongest response?", ["Pause, identify the missing source, check with a reliable reference or teacher, and avoid forwarding unverified content.", "Forward it quickly because it is dramatic.", "Add personal details to make it seem reliable.", "Assume deleting a source makes a claim stronger."], "Pause, identify the missing source, check with a reliable reference or teacher, and avoid forwarding unverified content.", "The response supports careful source checking and avoids spreading unverified digital content."),

  topicUnit("agriculture-records-foundation", "uganda-high-school-agriculture", "records-and-observations", "Read a stated farm record", "foundation", "evidence", "AGRICULTURE AND FOOD SYSTEMS · FOUNDATION", "A classroom record lists a stated number of plants observed on two dates. Which statement is supported?", ["The record contains observations for the two stated dates.", "The record proves a production outcome for every setting.", "The record replaces practical guidance.", "The dates are irrelevant."], "The record contains observations for the two stated dates.", "A record supports careful description of what was noted without becoming practical production instruction."),
  topicUnit("agriculture-comparison-development", "uganda-high-school-agriculture", "conditions-and-patterns", "Compare stated conditions", "development", "reasoning", "AGRICULTURE AND FOOD SYSTEMS · DEVELOPMENT", "Two class plots have different stated observation records. What is the strongest next reasoning step?", ["Compare the recorded conditions and ask what additional information would be needed before explaining a difference.", "Give a farming instruction from one record.", "Assume one observation proves a universal rule.", "Ignore the record dates."], "Compare the recorded conditions and ask what additional information would be needed before explaining a difference.", "A careful classroom comparison remains within the records and does not become farming direction."),
  topicUnit("agriculture-sustainability-extension", "uganda-high-school-agriculture", "sustainability-claims", "Check a sustainability claim", "extension", "decision", "AGRICULTURE AND FOOD SYSTEMS · EXTENSION", "A learner claims that one classroom result proves a practice is sustainable everywhere. What is the strongest response?", ["State what the classroom record shows, identify the wider evidence needed, and avoid issuing a practical instruction.", "Present the result as a universal farming rule.", "Ignore local conditions.", "Promise an outcome to another learner."], "State what the classroom record shows, identify the wider evidence needed, and avoid issuing a practical instruction.", "Sustainability reasoning matches the strength of a claim to the available evidence and local context."),

  topicUnit("ethics-perspectives-foundation", "uganda-high-school-religion-ethics", "perspectives-and-respect", "Recognise a perspective", "foundation", "evidence", "RELIGIOUS AND ETHICAL STUDIES · FOUNDATION", "A learner says that a community tradition matters to their family. Which statement is most careful?", ["The learner has shared a value-based perspective that can be heard respectfully.", "The statement proves every family holds the same view.", "The learner must reveal private details.", "No respectful response is possible."], "The learner has shared a value-based perspective that can be heard respectfully.", "Ethical discussion can recognise a perspective while avoiding assumptions about everyone else."),
  topicUnit("ethics-reasons-development", "uganda-high-school-religion-ethics", "reasons-and-dialogue", "Compare respectful reasons", "development", "reasoning", "RELIGIOUS AND ETHICAL STUDIES · DEVELOPMENT", "Classmates suggest different ways to organise a school activity and give reasons connected to dignity and participation. What is the strongest next step?", ["Describe each stated reason fairly and identify any shared needs before proposing a response.", "Mock the view that differs.", "Demand private belief information.", "Pretend reasons are unnecessary."], "Describe each stated reason fairly and identify any shared needs before proposing a response.", "Respectful dialogue compares ideas and reasons while protecting personal dignity."),
  topicUnit("ethics-process-extension", "uganda-high-school-religion-ethics", "inclusive-processes", "Choose an inclusive process", "extension", "decision", "RELIGIOUS AND ETHICAL STUDIES · EXTENSION", "A class must discuss a sensitive community question. What is the strongest study process?", ["Use voluntary respectful discussion, school guidance, and shared needs while keeping personal details private.", "Choose one view before listening.", "Force learners to disclose beliefs.", "Treat the discussion as religious authority."], "Use voluntary respectful discussion, school guidance, and shared needs while keeping personal details private.", "The process keeps the activity focused on respectful learning rather than religious authority or private disclosure."),

  topicUnit("kiswahili-maana-foundation", "uganda-high-school-kiswahili", "maana-katika-muktadha", "Maana katika muktadha", "foundation", "evidence", "KISWAHILI · FOUNDATION", "Sentensi inasema: ‘Wanafunzi walikaa pamoja ili kusoma kabla ya mjadala.’ Jibu lipi linaungwa mkono?", ["Wanafunzi walikutana kusoma kabla ya mjadala.", "Kila mwanafunzi alisoma kitabu kilekile.", "Mjadala haukuwepo.", "Sentensi haielezi chochote."], "Wanafunzi walikutana kusoma kabla ya mjadala.", "Jibu bora hutumia maneno yaliyotolewa bila kuongeza maelezo ambayo sentensi haijasema."),
  topicUnit("kiswahili-ujumbe-development", "uganda-high-school-kiswahili", "ujumbe-na-hadhira", "Panga ujumbe kwa hadhira", "development", "reasoning", "KISWAHILI · DEVELOPMENT", "Mwanafunzi anaandika ujumbe kwa kikundi cha kusoma lakini hana kusudi wala hatua inayofuata. Hatua ipi ni bora?", ["Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata.", "Ongeza maneno mengi bila kusudi.", "Tumia kejeli ili watu wajibu.", "Ondoa maelezo yote."], "Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata.", "Ujumbe wazi huunganisha hadhira, kusudi, maelezo muhimu, na hatua inayofuata."),
  topicUnit("kiswahili-mawasiliano-extension", "uganda-high-school-kiswahili", "mawasiliano-ya-heshima", "Chagua mawasiliano ya heshima", "extension", "decision", "KISWAHILI · EXTENSION", "Katika kikundi cha kusoma, mtu anapendekeza kumdhalilisha mwandishi wa ujumbe wenye makosa. Hatua ipi inaonyesha heshima?", ["Eleza sehemu inayohitaji ufafanuzi kwa heshima na mwalike mwandishi kurekebisha ujumbe.", "Tumia kejeli ili wengine wacheke.", "Sambaza ujumbe bila sababu.", "Kataa kusoma ujumbe wowote."], "Eleza sehemu inayohitaji ufafanuzi kwa heshima na mwalike mwandishi kurekebisha ujumbe.", "Mawasiliano ya heshima hulenga ujumbe na ufafanuzi bila kumdhalilisha mtu."),

  topicUnit("literature-detail-foundation", "uganda-high-school-literature", "textual-details", "Start with a textual detail", "foundation", "evidence", "LITERATURE · FOUNDATION", "In a short scene, a character pauses, checks a note, and says, ‘I should confirm this first.’ Which interpretation is best supported?", ["The character is cautious before making a conclusion.", "The character has proved everyone else is wrong.", "The character will never act.", "The scene gives no detail."], "The character is cautious before making a conclusion.", "A stated action and line can support a careful interpretation without proving a broader trait."),
  topicUnit("literature-theme-development", "uganda-high-school-literature", "themes-and-support", "Connect a theme to support", "development", "reasoning", "LITERATURE · DEVELOPMENT", "A learner says a text is about trust but cannot point to a scene or line. What is the strongest next step?", ["Choose a stated detail and explain how it may support the possible theme.", "Repeat the theme claim without a detail.", "Assume the author’s private life proves the theme.", "Remove lines that suggest another reading."], "Choose a stated detail and explain how it may support the possible theme.", "Theme discussion is stronger when it connects an interpretation to a stated textual detail."),
  topicUnit("literature-readings-extension", "uganda-high-school-literature", "supported-readings", "Compare supported readings", "extension", "decision", "LITERATURE · EXTENSION", "Two readers give different interpretations of a character’s silence and cite different lines. What is the strongest response?", ["Compare the cited lines, explain each support, and note what the text does not settle.", "Declare one reader cannot discuss the text.", "Use personal attacks as evidence.", "Delete a different interpretation."], "Compare the cited lines, explain each support, and note what the text does not settle.", "Literary discussion can compare different readings when each remains connected to the text."),

  topicUnit("fine-art-observation-foundation", "uganda-high-school-fine-art", "visual-observation", "Describe a visible choice", "foundation", "evidence", "FINE ART · FOUNDATION", "A classroom artwork places a bright shape near the centre and darker tones around it. Which statement is most careful?", ["The contrast and placement make the shape visually noticeable.", "Every viewer must give the shape the same meaning.", "The artwork has no design choices.", "Darker tones cannot be used in art."], "The contrast and placement make the shape visually noticeable.", "Observation can describe visible choices without claiming that every viewer has the same interpretation."),
  topicUnit("fine-art-purpose-development", "uganda-high-school-fine-art", "purpose-and-process", "Connect purpose to a choice", "development", "reasoning", "FINE ART · DEVELOPMENT", "A learner plans a classroom artwork about a familiar place. What is the strongest planning step?", ["State an intended message, choose visible design features, and plan one revision check.", "Use random features without a purpose.", "Copy a classmate’s work without discussion.", "Treat the plan as professional assessment."], "State an intended message, choose visible design features, and plan one revision check.", "A creative process can connect purpose, design choices, and reflection without claiming a professional judgement."),
  topicUnit("fine-art-critique-extension", "uganda-high-school-fine-art", "respectful-critique", "Give a respectful critique", "extension", "decision", "FINE ART · EXTENSION", "A learner wants to call a classmate’s artwork ‘bad’ without referring to visible work or stated purpose. What is the strongest response?", ["Describe a visible choice, connect it to the stated purpose, and offer a respectful question.", "Use an insult because it is quicker.", "Share a photo outside class without permission.", "Judge the artist rather than the work."], "Describe a visible choice, connect it to the stated purpose, and offer a respectful question.", "Constructive critique focuses on visible work and stated purpose while protecting the artist’s dignity."),

  topicUnit("technical-drawing-views-foundation", "uganda-high-school-technical-drawing", "views-and-labels", "Read a stated drawing view", "foundation", "evidence", "TECHNICAL DRAWING · FOUNDATION", "A classroom drawing is labelled ‘front view’ and shows a rectangle with a centred circle. Which statement is supported?", ["The front view shows a rectangular outline with a centred circular feature.", "The drawing proves the object’s exact depth.", "The drawing gives every material detail.", "A front view shows nothing."], "The front view shows a rectangular outline with a centred circular feature.", "A stated view supports description of what is shown while leaving missing details unresolved."),
  topicUnit("technical-drawing-communication-development", "uganda-high-school-technical-drawing", "communication-and-scale", "Plan clear drawing communication", "development", "reasoning", "TECHNICAL DRAWING · DEVELOPMENT", "A learner has drawn an outline but omitted the stated view and scale information. What is the strongest next step?", ["Add clear labels and note information that the classroom drawing does not yet provide.", "Ask every reader to guess missing details.", "Invent dimensions to fill the page.", "Treat the drawing as a construction instruction."], "Add clear labels and note information that the classroom drawing does not yet provide.", "Clear labels make a class drawing reviewable without inventing details or turning it into an instruction."),
  topicUnit("technical-drawing-review-extension", "uganda-high-school-technical-drawing", "peer-review", "Choose a peer-review question", "extension", "decision", "TECHNICAL DRAWING · EXTENSION", "A drawing now has a stated view and labels. Which review question is most useful?", ["Can a reviewer identify the view and see which information remains to be checked?", "Can a reviewer guess the learner’s private intention?", "Can the drawing be used without teacher review for construction?", "Can missing labels be ignored?"], "Can a reviewer identify the view and see which information remains to be checked?", "A useful review checks clear communication and acknowledges the limits of a classroom drawing."),

  topicUnit("food-nutrition-label-foundation", "uganda-high-school-food-nutrition", "food-information", "Read stated food information", "foundation", "evidence", "FOOD AND NUTRITION · FOUNDATION", "A classroom label exercise lists a serving amount and one ingredient. Which statement is most careful?", ["The label provides stated information about that product.", "The label proves one choice is best for every person.", "The label replaces professional guidance.", "The label contains no information."], "The label provides stated information about that product.", "A classroom label can be read carefully without becoming personal food or health guidance."),
  topicUnit("food-nutrition-claims-development", "uganda-high-school-food-nutrition", "claims-and-sources", "Check a food-information claim", "development", "reasoning", "FOOD AND NUTRITION · DEVELOPMENT", "A post says one ingredient will solve everyone’s study-energy problems but gives no source. What is the strongest next step?", ["Name the claim, note the missing source, and ask a teacher to help check relevant reliable information.", "Repeat the claim as a guarantee.", "Tell classmates to make personal changes immediately.", "Assume popularity is evidence."], "Name the claim, note the missing source, and ask a teacher to help check relevant reliable information.", "The study move is source checking, not a personal dietary decision or a medical recommendation."),
  topicUnit("food-nutrition-limits-extension", "uganda-high-school-food-nutrition", "evidence-limits", "State evidence limits", "extension", "decision", "FOOD AND NUTRITION · EXTENSION", "After checking a source, a learner wants to make a universal conclusion for classmates. What is the strongest response?", ["Describe what the source supports, what remains uncertain, and why personal questions belong with an appropriate adult or professional.", "Promise the same outcome for every learner.", "Ignore source limits.", "Turn a class activity into food-preparation guidance."], "Describe what the source supports, what remains uncertain, and why personal questions belong with an appropriate adult or professional.", "A responsible conclusion keeps source limits visible and leaves personal matters outside the learning activity."),

  topicUnit("music-listening-foundation", "uganda-high-school-music", "listening-patterns", "Describe a listening pattern", "foundation", "evidence", "MUSIC · FOUNDATION", "A classroom excerpt repeats a steady hand-clap pattern while a higher sound enters later. Which statement is most careful?", ["The excerpt has a repeated pattern and a later higher sound.", "Every listener must feel the same emotion.", "The excerpt proves the performer’s private intention.", "Patterns cannot be described in music."], "The excerpt has a repeated pattern and a later higher sound.", "Listening evidence can describe audible features without claiming identical feelings or intentions."),
  topicUnit("music-rehearsal-development", "uganda-high-school-music", "rehearsal-and-roles", "Plan a rehearsal adjustment", "development", "reasoning", "MUSIC · DEVELOPMENT", "A group loses a repeated pattern at one transition during rehearsal. What is the strongest next step?", ["Name the transition, agree on a short shared practice step, and keep roles inclusive.", "Exclude a learner after one attempt.", "Mock the group.", "Share a recording outside class."], "Name the transition, agree on a short shared practice step, and keep roles inclusive.", "A useful rehearsal adjustment focuses on an observable point and shared practice rather than judgement."),
  topicUnit("music-feedback-extension", "uganda-high-school-music", "respectful-feedback", "Choose respectful musical feedback", "extension", "decision", "MUSIC · EXTENSION", "A learner wants to give feedback after a group rehearsal. What is the strongest response?", ["Name one observable point, connect it to the group goal, and suggest a respectful next practice step.", "Use an insult so the feedback is memorable.", "Judge the learner instead of the rehearsal.", "Share another learner’s recording without permission."], "Name one observable point, connect it to the group goal, and suggest a respectful next practice step.", "Respectful feedback supports the next rehearsal without becoming professional assessment or unapproved sharing."),

  topicUnit("physical-education-observation-foundation", "uganda-high-school-physical-education", "participation-observations", "Read a participation observation", "foundation", "evidence", "PHYSICAL EDUCATION · FOUNDATION", "A teacher-supervised activity record notes that one learner paused twice. Which statement is most careful?", ["The record notes two pauses but does not explain why they happened.", "The pauses prove the learner is unwilling.", "Classmates should give personal activity instructions.", "The record predicts every future activity."], "The record notes two pauses but does not explain why they happened.", "An observation should not be turned into a personal judgement or activity instruction without teacher guidance."),
  topicUnit("physical-education-roles-development", "uganda-high-school-physical-education", "fair-participation", "Plan fair participation", "development", "reasoning", "PHYSICAL EDUCATION · DEVELOPMENT", "In a teacher-supervised activity, the same learners receive every turn. What is the strongest next step?", ["Pause, invite respectful role preferences, and use teacher guidance to share participation fairly.", "Keep the same roles because they are faster.", "Pressure a learner who pauses.", "Make assumptions about classmates."], "Pause, invite respectful role preferences, and use teacher guidance to share participation fairly.", "Fair participation uses dignity, choice, and teacher guidance rather than pressure or assumptions."),
  topicUnit("physical-education-reflection-extension", "uganda-high-school-physical-education", "guided-reflection", "Reflect on fair participation", "extension", "decision", "PHYSICAL EDUCATION · EXTENSION", "After a teacher-guided activity, which reflection is most useful?", ["Identify whether roles were shared fairly and what the group can discuss with the teacher next time.", "Decide which learner is naturally best.", "Tell classmates to follow an activity plan outside teacher guidance.", "Make a personal health judgement."], "Identify whether roles were shared fairly and what the group can discuss with the teacher next time.", "The reflection stays focused on fair participation and teacher-guided improvement, not performance or medical judgement."),
];

function pathwayUnit(
  id: string,
  packId: string,
  topicId: string,
  title: string,
  band: Exclude<HighSchoolTopicBand, "all_levels">,
  mode: Exclude<HighSchoolTopicMode, "reflection">,
  cue: string,
  prompt: string,
  bestOption: string,
  explanation: string,
  boundaryNote?: string,
): HighSchoolTopicUnit {
  return topicUnit(id, packId, topicId, title, band, mode, cue, prompt, [bestOption, "Make a broader conclusion than the stated information allows.", "Ignore the stated record or detail.", "Replace the evidence with an unsupported personal claim."], bestOption, explanation, boundaryNote);
}

const PATHWAY_TWO_UNITS: readonly HighSchoolTopicUnit[] = [
  pathwayUnit("biology-cells-pathway-foundation", "uganda-high-school-biology", "cells-and-organisation", "Notice cellular organisation", "foundation", "evidence", "BIOLOGY · PATHWAY TWO", "A classroom diagram labels cells, tissues, and an organ. What is the most careful study note?", "The diagram shows stated levels of organisation that can be described before a wider explanation.", "A careful note names the shown organisation without claiming more than the diagram provides."),
  pathwayUnit("biology-inheritance-pathway-development", "uganda-high-school-biology", "inheritance-patterns", "Compare inheritance evidence", "development", "reasoning", "BIOLOGY · PATHWAY TWO", "Two class examples show a trait appearing in different family records. What is the strongest next reasoning step?", "Compare the stated records and identify what additional evidence would be needed before explaining a pattern.", "Inheritance reasoning compares stated records and keeps explanation limits visible."),
  pathwayUnit("biology-ecosystems-pathway-extension", "uganda-high-school-biology", "ecosystem-relationships", "Limit an ecosystem claim", "extension", "decision", "BIOLOGY · PATHWAY TWO", "A learner observes one change in a school garden and wants to explain every ecosystem. What is the strongest response?", "Describe the local relationship observed and state what wider evidence would be needed.", "An ecosystem conclusion should match the scale of the stated evidence."),

  pathwayUnit("chemistry-particles-pathway-foundation", "uganda-high-school-chemistry", "particle-arrangements", "Read a particle model", "foundation", "evidence", "CHEMISTRY · PATHWAY TWO", "A class model uses closely spaced dots for one sample and widely spaced dots for another. What can be described safely?", "The model shows different stated dot arrangements without proving every property of the samples.", "A model can be described for what it shows without being treated as a complete real-world account."),
  pathwayUnit("chemistry-patterns-pathway-development", "uganda-high-school-chemistry", "substance-patterns", "Compare a substance pattern", "development", "reasoning", "CHEMISTRY · PATHWAY TWO", "Two classroom records list different observed properties for samples. What is the strongest next step?", "Compare each stated property and identify which observations need further checking.", "A chemical comparison starts with stated properties and names its missing information."),
  pathwayUnit("chemistry-reaction-pathway-extension", "uganda-high-school-chemistry", "reaction-evidence", "Check reaction evidence", "extension", "decision", "CHEMISTRY · PATHWAY TWO", "A learner sees a class note about a visible change and wants to announce a product outcome. What is the strongest response?", "Separate the recorded visible change from any conclusion that would require further evidence.", "Classroom evidence supports cautious interpretation, not a practical chemical instruction."),

  pathwayUnit("economics-demand-pathway-foundation", "uganda-high-school-economics", "needs-and-demand", "Read a stated demand pattern", "foundation", "evidence", "ECONOMICS · PATHWAY TWO", "A class chart shows that more learners selected one shared resource than another. What is supported?", "The chart records a stated selection pattern for that class context.", "A class pattern can be described without assuming it represents every community."),
  pathwayUnit("economics-markets-pathway-development", "uganda-high-school-economics", "markets-and-information", "Compare market information", "development", "reasoning", "ECONOMICS · PATHWAY TWO", "Two classroom examples give different information about a product choice. What is the strongest reasoning step?", "Compare the stated information, the possible trade-offs, and what has not been recorded.", "Economic reasoning compares available information rather than assuming a single answer."),
  pathwayUnit("economics-policy-pathway-extension", "uganda-high-school-economics", "policy-claims", "Limit a policy claim", "extension", "decision", "ECONOMICS · PATHWAY TWO", "A learner reads one short report and wants to predict how every household will respond. What is the strongest response?", "State what the report supports and explain why wider household claims need wider evidence.", "Evidence-aware economics avoids turning a short report into personal financial direction."),

  pathwayUnit("entrepreneurship-opportunity-pathway-foundation", "uganda-high-school-entrepreneurship", "opportunities-and-needs", "Spot a project need", "foundation", "evidence", "ENTREPRENEURSHIP · PATHWAY TWO", "A class notice lists a repeated problem with a school event. What is the most careful first observation?", "The notice identifies a stated problem that could be explored as a class-project question.", "A project need can be noticed without promising a commercial outcome."),
  pathwayUnit("entrepreneurship-resources-pathway-development", "uganda-high-school-entrepreneurship", "resources-and-planning", "Compare project resources", "development", "reasoning", "ENTREPRENEURSHIP · PATHWAY TWO", "A group has a limited time and two proposed tasks. What is the strongest planning step?", "List the stated resources, compare the tasks, and record what would be deferred.", "A clear plan makes constraints and trade-offs visible."),
  pathwayUnit("entrepreneurship-responsibility-pathway-extension", "uganda-high-school-entrepreneurship", "responsible-projects", "Choose responsible project language", "extension", "decision", "ENTREPRENEURSHIP · PATHWAY TWO", "A project poster could make a claim that the group cannot verify. What is the strongest response?", "Use a supportable description and name what the group is still testing.", "Responsible project language avoids guarantees and personal financial advice."),

  pathwayUnit("english-language-pathway-foundation", "uganda-high-school-english", "language-and-effect", "Notice a language choice", "foundation", "evidence", "ENGLISH · PATHWAY TWO", "A school notice repeats the word ‘together’ in its opening and closing lines. What is a careful observation?", "The word is repeated in the stated positions and may help connect the notice.", "Language observation begins with the wording actually present in the text."),
  pathwayUnit("english-summary-pathway-development", "uganda-high-school-english", "summaries-and-structure", "Build a faithful summary", "development", "reasoning", "ENGLISH · PATHWAY TWO", "A learner summarizes a paragraph but includes an idea not stated in it. What is the strongest revision step?", "Keep the central stated ideas and remove the unsupported addition.", "A faithful summary preserves the source meaning without adding a new claim."),
  pathwayUnit("english-research-pathway-extension", "uganda-high-school-english", "research-and-attribution", "Check a research claim", "extension", "decision", "ENGLISH · PATHWAY TWO", "A draft uses a striking fact but does not name where it came from. What is the strongest response?", "Identify the source, check whether it supports the wording, and revise the claim if needed.", "Research writing connects a claim to a checkable source and its limits."),

  pathwayUnit("physics-forces-pathway-foundation", "uganda-high-school-physics", "forces-and-interactions", "Describe a stated interaction", "foundation", "evidence", "PHYSICS · PATHWAY TWO", "A class sketch shows two objects touching and arrows labelled in opposite directions. What can be described?", "The sketch shows stated opposite-direction arrows for the interaction.", "A diagram can be described before it is used to make a wider physical explanation."),
  pathwayUnit("physics-energy-pathway-development", "uganda-high-school-physics", "energy-representations", "Compare energy representations", "development", "reasoning", "PHYSICS · PATHWAY TWO", "Two class diagrams represent the same event in different ways. What is the strongest next step?", "Compare what each diagram explicitly represents and identify what neither diagram shows.", "Representations support reasoning when their stated scope is compared."),
  pathwayUnit("physics-waves-pathway-extension", "uganda-high-school-physics", "waves-and-evidence", "Limit a wave conclusion", "extension", "decision", "PHYSICS · PATHWAY TWO", "One classroom example shows a repeated pattern. What is the strongest way to explain it?", "State the repeated pattern, name an evidence limit, and avoid treating it as a universal safety rule.", "A physical pattern can be explained cautiously within the limits of a classroom example."),

  pathwayUnit("mathematics-equivalence-pathway-foundation", "uganda-high-school-mathematics", "equivalence-and-structure", "Check equivalent forms", "foundation", "evidence", "MATHEMATICS · PATHWAY TWO", "A learner writes two expressions and says they represent the same value for a stated input. What is the strongest check?", "Substitute the stated input into both expressions and compare the results.", "A direct check tests the stated equivalence instead of relying on appearance."),
  pathwayUnit("mathematics-functions-pathway-development", "uganda-high-school-mathematics", "functions-and-tables", "Read a function table", "development", "reasoning", "MATHEMATICS · PATHWAY TWO", "A table pairs inputs with outputs. What is the strongest first reasoning move?", "Read the stated input-output pairs and check whether one consistent relation is supported.", "A table should be interpreted from its stated entries before a rule is claimed."),
  pathwayUnit("mathematics-probability-pathway-extension", "uganda-high-school-mathematics", "probability-and-claims", "Limit a probability claim", "extension", "decision", "MATHEMATICS · PATHWAY TWO", "A short class trial gives one outcome more often than another. What is the strongest conclusion?", "Describe the trial result and state that more trials would strengthen any broader claim.", "A probability observation should not be turned into certainty from a small trial."),

  pathwayUnit("geography-settlement-pathway-foundation", "uganda-high-school-geography", "settlement-patterns", "Read a settlement pattern", "foundation", "evidence", "GEOGRAPHY · PATHWAY TWO", "A class map shows several labelled places near a road. What is a careful observation?", "The stated places are shown near the road on that map.", "A map observation does not by itself explain every reason for settlement."),
  pathwayUnit("geography-resources-pathway-development", "uganda-high-school-geography", "resources-and-place", "Compare place information", "development", "reasoning", "GEOGRAPHY · PATHWAY TWO", "Two classroom maps show different labelled features for two places. What is the strongest next step?", "Compare the map keys, stated features, and information that is not shown.", "Place comparison works from map evidence and recognises missing context."),
  pathwayUnit("geography-scale-pathway-extension", "uganda-high-school-geography", "scale-and-claims", "Check a spatial claim", "extension", "decision", "GEOGRAPHY · PATHWAY TWO", "A learner wants to make a broad conclusion from a small-scale classroom map. What is the strongest response?", "Explain what the map can show at its stated scale and what would need other evidence.", "Map scale helps a learner state what a representation can and cannot support."),

  pathwayUnit("history-chronology-pathway-foundation", "uganda-high-school-history-civics", "chronology-and-order", "Read a stated sequence", "foundation", "evidence", "HISTORY AND CIVICS · PATHWAY TWO", "A timeline lists three events in dated order. What is supported?", "The timeline presents the stated events in its recorded sequence.", "Sequence alone does not prove every cause or effect."),
  pathwayUnit("history-causes-pathway-development", "uganda-high-school-history-civics", "causes-and-consequences", "Compare possible causes", "development", "reasoning", "HISTORY AND CIVICS · PATHWAY TWO", "Two sources name different reasons for an event. What is the strongest next step?", "Compare the stated reasons, the source contexts, and what evidence could support each one.", "Historical explanation can compare causes without forcing one source to answer every question."),
  pathwayUnit("civics-inclusion-pathway-extension", "uganda-high-school-history-civics", "inclusive-civic-process", "Choose an inclusive process", "extension", "decision", "HISTORY AND CIVICS · PATHWAY TWO", "A class is planning a shared decision and some voices have not been heard. What is the strongest response?", "Use a respectful process that invites participation and follows school guidance.", "Civic learning can practise inclusive process without giving political instruction."),

  pathwayUnit("ict-algorithms-pathway-foundation", "uganda-high-school-ict", "algorithms-and-steps", "Read a stated sequence", "foundation", "evidence", "ICT AND DIGITAL SKILLS · PATHWAY TWO", "A class flowchart gives three ordered steps for checking a file name. What is supported?", "The flowchart presents the stated ordered steps for that class task.", "A sequence can be described without assuming it solves every digital task."),
  pathwayUnit("ict-communication-pathway-development", "uganda-high-school-ict", "digital-communication", "Compare digital messages", "development", "reasoning", "ICT AND DIGITAL SKILLS · PATHWAY TWO", "Two messages share the same claim but one names a source and date. What is the strongest next step?", "Compare the stated source details before deciding how much confidence the messages deserve.", "Digital communication is stronger when source details can be checked."),
  pathwayUnit("ict-data-claims-pathway-extension", "uganda-high-school-ict", "data-claims-and-consent", "Check a data claim", "extension", "decision", "ICT AND DIGITAL SKILLS · PATHWAY TWO", "A class chart has no explanation of how responses were collected. What is the strongest response?", "Ask what was collected, with what permission, and what the chart can actually support.", "Data reasoning protects privacy and keeps claims aligned with stated collection details."),

  pathwayUnit("agriculture-systems-pathway-foundation", "uganda-high-school-agriculture", "food-system-observations", "Read a food-system record", "foundation", "evidence", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY TWO", "A classroom diagram labels growing, transport, and use as parts of a food system. What is supported?", "The diagram presents those stated parts of the class model.", "A class model can be read without becoming production instruction."),
  pathwayUnit("agriculture-soil-pathway-development", "uganda-high-school-agriculture", "soil-record-comparison", "Compare soil records", "development", "reasoning", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY TWO", "Two class records use different descriptions for observed soil samples. What is the strongest next step?", "Compare the stated descriptions and identify what was not recorded before explaining a difference.", "A classroom comparison stays with records and does not issue practical farming direction."),
  pathwayUnit("agriculture-systems-pathway-extension", "uganda-high-school-agriculture", "systems-claims", "Limit a food-system claim", "extension", "decision", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY TWO", "A learner wants to prescribe a practice from one classroom model. What is the strongest response?", "State what the model illustrates and avoid turning it into a practical instruction.", "A model can guide questions while wider practical decisions need appropriate local guidance."),

  pathwayUnit("ethics-values-pathway-foundation", "uganda-high-school-religion-ethics", "values-in-action", "Recognise a stated value", "foundation", "evidence", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY TWO", "A learner says that fairness matters in a class decision. What is the most careful observation?", "The learner has named fairness as a value in the stated discussion.", "A value statement can be heard respectfully without assuming everyone uses the same reasoning."),
  pathwayUnit("ethics-dilemmas-pathway-development", "uganda-high-school-religion-ethics", "ethical-reasons", "Compare ethical reasons", "development", "reasoning", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY TWO", "Classmates suggest different fair responses to a shared problem. What is the strongest next step?", "Describe the stated reasons and identify a respectful question that could clarify them.", "Ethical reasoning compares reasons while protecting people from personal disclosure."),
  pathwayUnit("ethics-disagreement-pathway-extension", "uganda-high-school-religion-ethics", "respectful-disagreement", "Choose respectful disagreement", "extension", "decision", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY TWO", "A disagreement becomes tense in a class discussion. What is the strongest response?", "Return to the stated ideas, use respectful language, and seek school guidance if needed.", "Respectful disagreement focuses on ideas rather than personal belief claims or authority."),

  pathwayUnit("kiswahili-msamiati-pathway-foundation", "uganda-high-school-kiswahili", "msamiati-katika-muktadha", "Msamiati katika muktadha", "foundation", "evidence", "KISWAHILI · PATHWAY TWO", "Neno ‘haraka’ linaonekana katika sentensi inayosema mwanafunzi aliandika haraka kabla ya muda kuisha. Jibu lipi linaungwa mkono?", "Neno linaeleza namna ya kuandika katika sentensi iliyotolewa.", "Maana sahihi huanza na muktadha wa sentensi iliyotolewa."),
  pathwayUnit("kiswahili-muundo-pathway-development", "uganda-high-school-kiswahili", "muundo-wa-maandishi", "Panga muundo wa maandishi", "development", "reasoning", "KISWAHILI · PATHWAY TWO", "Mwanafunzi ana ujumbe wenye wazo zuri lakini aya hazina mpangilio wazi. Hatua ipi ni bora?", "Panga wazo kuu, maelezo yanayoliunga mkono, na hitimisho linalofaa hadhira.", "Muundo wazi husaidia msomaji kufuatilia ujumbe bila kubadilisha kusudi lake."),
  pathwayUnit("kiswahili-hadhira-pathway-extension", "uganda-high-school-kiswahili", "hadhira-na-heshima", "Chagua lugha inayomfaa hadhira", "extension", "decision", "KISWAHILI · PATHWAY TWO", "Ujumbe wa shule unahitaji kuwajulisha wanafunzi na wazazi. Hatua ipi inaonyesha mawasiliano bora?", "Tumia lugha wazi na yenye heshima, kisha eleza hatua inayofuata kwa hadhira.", "Mawasiliano bora huunganisha hadhira, heshima, na hatua iliyo wazi."),

  pathwayUnit("literature-character-pathway-foundation", "uganda-high-school-literature", "character-patterns", "Notice a character pattern", "foundation", "evidence", "LITERATURE · PATHWAY TWO", "A character returns a borrowed item after being reminded. What is a careful interpretation?", "The stated action can support a limited observation about the character’s choice.", "A literary interpretation begins with what the text actually shows."),
  pathwayUnit("literature-structure-pathway-development", "uganda-high-school-literature", "structure-and-effect", "Compare structural choices", "development", "reasoning", "LITERATURE · PATHWAY TWO", "A text begins with an unanswered question and ends by returning to it. What is the strongest next step?", "Describe the stated structural pattern and explain one possible effect with support from the text.", "Structure can be connected to effect when the explanation remains text-based."),
  pathwayUnit("literature-symbol-pathway-extension", "uganda-high-school-literature", "symbols-and-readings", "Limit a symbolic reading", "extension", "decision", "LITERATURE · PATHWAY TWO", "A learner sees a repeated object and wants to assign one fixed meaning to it. What is the strongest response?", "Offer a supported possible meaning and note that another text-based reading may be possible.", "Literary symbols invite supported interpretations rather than one unsupported certainty."),

  pathwayUnit("fine-art-elements-pathway-foundation", "uganda-high-school-fine-art", "visual-elements", "Notice visual elements", "foundation", "evidence", "FINE ART · PATHWAY TWO", "A classroom work uses repeated curved lines and two contrasting colours. What is a careful observation?", "The work contains those stated line and colour choices.", "Visual observation begins with visible features before interpretation."),
  pathwayUnit("fine-art-composition-pathway-development", "uganda-high-school-fine-art", "composition-and-purpose", "Compare composition choices", "development", "reasoning", "FINE ART · PATHWAY TWO", "A learner moves one shape closer to the centre while revising a classroom work. What is the strongest next step?", "Explain the intended visual effect and compare it with the earlier arrangement.", "Creative reasoning links a visible revision to a stated purpose."),
  pathwayUnit("fine-art-sharing-pathway-extension", "uganda-high-school-fine-art", "sharing-and-consent", "Choose respectful art sharing", "extension", "decision", "FINE ART · PATHWAY TWO", "A learner wants to post a classmate’s artwork online after a display. What is the strongest response?", "Ask for appropriate permission and follow school guidance before sharing the work.", "Creative sharing should protect the maker’s dignity and consent."),

  pathwayUnit("technical-drawing-symbols-pathway-foundation", "uganda-high-school-technical-drawing", "symbols-and-conventions", "Read a drawing symbol", "foundation", "evidence", "TECHNICAL DRAWING · PATHWAY TWO", "A classroom drawing key labels one line style as hidden detail. What is supported?", "The key gives that stated meaning to the line style in the classroom drawing.", "A drawing key supports careful reading without providing construction direction."),
  pathwayUnit("technical-drawing-scale-pathway-development", "uganda-high-school-technical-drawing", "scale-and-clarity", "Compare scale information", "development", "reasoning", "TECHNICAL DRAWING · PATHWAY TWO", "Two classroom drawings show the same outline but use different stated scales. What is the strongest next step?", "Read the scale labels and explain what information must remain clear to a reviewer.", "Scale information supports communication when it is read with the drawing’s stated limits."),
  pathwayUnit("technical-drawing-revision-pathway-extension", "uganda-high-school-technical-drawing", "revision-and-limits", "Choose a drawing revision", "extension", "decision", "TECHNICAL DRAWING · PATHWAY TWO", "A reviewer cannot identify the intended view from a classroom sketch. What is the strongest response?", "Add a clear view label and identify what still needs teacher review.", "A drawing revision improves communication without becoming a construction instruction."),

  pathwayUnit("food-nutrition-storage-pathway-foundation", "uganda-high-school-food-nutrition", "food-information-records", "Read stated food information", "foundation", "evidence", "FOOD AND NUTRITION · PATHWAY TWO", "A classroom source lists a date, a storage statement, and an ingredient list. What is supported?", "The source presents those stated details for that product or example.", "Food information can be read critically without becoming personal dietary or medical guidance."),
  pathwayUnit("food-nutrition-sources-pathway-development", "uganda-high-school-food-nutrition", "information-sources", "Compare food-information sources", "development", "reasoning", "FOOD AND NUTRITION · PATHWAY TWO", "Two posts make different claims about a food item, but only one names a source. What is the strongest next step?", "Compare the stated source details and ask a teacher for help checking any important claim.", "Source comparison is a study skill, not a personal food decision."),
  pathwayUnit("food-nutrition-communication-pathway-extension", "uganda-high-school-food-nutrition", "responsible-communication", "Choose responsible food communication", "extension", "decision", "FOOD AND NUTRITION · PATHWAY TWO", "A group wants to make a poster promising one food choice will work for everyone. What is the strongest response?", "Use source-aware language, name uncertainty, and avoid universal personal claims.", "Responsible communication keeps study claims separate from individual guidance."),

  pathwayUnit("music-rhythm-pathway-foundation", "uganda-high-school-music", "rhythm-patterns", "Read a rhythm pattern", "foundation", "evidence", "MUSIC · PATHWAY TWO", "A class notation repeats two short marks followed by one longer mark. What is a careful observation?", "The notation shows a repeated stated pattern of marks.", "A music pattern can be described without assuming one emotional meaning."),
  pathwayUnit("music-ensemble-pathway-development", "uganda-high-school-music", "ensemble-coordination", "Compare ensemble roles", "development", "reasoning", "MUSIC · PATHWAY TWO", "Two groups perform the same class pattern but enter at different points. What is the strongest next step?", "Identify the stated entry points and agree on a respectful shared practice check.", "Ensemble reasoning focuses on observable coordination and inclusive rehearsal."),
  pathwayUnit("music-audience-pathway-extension", "uganda-high-school-music", "audience-and-feedback", "Choose responsible music feedback", "extension", "decision", "MUSIC · PATHWAY TWO", "A learner wants to describe a performance for an audience. What is the strongest response?", "Use observable details, respect the performers, and avoid claiming professional assessment.", "Music feedback can be useful when it is respectful and tied to observable work."),

  pathwayUnit("physical-education-rules-pathway-foundation", "uganda-high-school-physical-education", "rules-and-participation", "Read a participation rule", "foundation", "evidence", "PHYSICAL EDUCATION · PATHWAY TWO", "A teacher-guided activity rule says each group takes turns after a signal. What is supported?", "The stated rule describes how turns are organised for that activity.", "A participation rule can be read without giving personal activity or health advice."),
  pathwayUnit("physical-education-teamwork-pathway-development", "uganda-high-school-physical-education", "teamwork-and-access", "Plan inclusive teamwork", "development", "reasoning", "PHYSICAL EDUCATION · PATHWAY TWO", "A group notices that one role prevents some learners from taking part. What is the strongest next step?", "Discuss a fair role adjustment with the teacher and invite respectful preferences.", "Inclusive participation uses teacher guidance rather than pressure or assumptions."),
  pathwayUnit("physical-education-access-pathway-extension", "uganda-high-school-physical-education", "access-and-dignity", "Choose a dignified participation response", "extension", "decision", "PHYSICAL EDUCATION · PATHWAY TWO", "A learner asks for a different role during a teacher-guided activity. What is the strongest response?", "Respect the request, involve the teacher, and focus on fair participation.", "A dignified response supports access without making health, fitness, or coaching judgements."),
];

const PATHWAY_THREE_UNITS: readonly HighSchoolTopicUnit[] = [
  pathwayUnit("biology-cell-functions-pathway-three-foundation", "uganda-high-school-biology", "cell-functions", "Read a cell-function diagram", "foundation", "evidence", "BIOLOGY · PATHWAY THREE", "A classroom diagram labels one part as taking in materials and another as moving materials. What is a careful study note?", "The diagram assigns stated roles to the labelled parts without proving every process in a living system.", "A biological diagram can support a careful description before a wider explanation is made."),
  pathwayUnit("biology-populations-pathway-three-development", "uganda-high-school-biology", "population-records", "Compare population records", "development", "reasoning", "BIOLOGY · PATHWAY THREE", "Two class records show different counts of one observed organism at two stated times. What is the strongest next step?", "Compare the stated times and recording conditions, then identify what further observations would be needed.", "Population reasoning uses the recorded conditions and avoids turning a small record into a complete explanation."),
  pathwayUnit("biology-diversity-pathway-three-extension", "uganda-high-school-biology", "diversity-claims", "Limit a diversity claim", "extension", "decision", "BIOLOGY · PATHWAY THREE", "A learner sees one classroom collection of observations and wants to describe every habitat. What is the strongest response?", "State what the collection shows and name the wider evidence needed for a broader habitat claim.", "A conclusion about diversity should match the scale of the stated observation."),

  pathwayUnit("chemistry-mixtures-pathway-three-foundation", "uganda-high-school-chemistry", "mixtures-and-observations", "Describe a mixture record", "foundation", "evidence", "CHEMISTRY · PATHWAY THREE", "A classroom note describes two visible materials placed together in one container. What is supported by the note?", "The note records the stated materials together without proving an unseen change or a practical procedure.", "A chemistry record supports description of what is stated and keeps unrecorded details separate."),
  pathwayUnit("chemistry-measurement-pathway-three-development", "uganda-high-school-chemistry", "measurement-comparisons", "Compare measured records", "development", "reasoning", "CHEMISTRY · PATHWAY THREE", "Two groups record different values for a classroom sample using labelled units. What is the strongest next step?", "Check the stated units, method, and conditions before deciding what the difference means.", "Measurement reasoning depends on the record, units, and limitations of the comparison."),
  pathwayUnit("chemistry-materials-pathway-three-extension", "uganda-high-school-chemistry", "materials-claims", "Check a materials claim", "extension", "decision", "CHEMISTRY · PATHWAY THREE", "A message says a classroom material observation proves a product will always behave the same way. What is the strongest response?", "Separate the observation from the broad product claim and identify the evidence the wider claim would require.", "Classroom chemistry evidence should not become a product or safety conclusion."),

  pathwayUnit("economics-production-pathway-three-foundation", "uganda-high-school-economics", "production-and-resources", "Read a resource record", "foundation", "evidence", "ECONOMICS · PATHWAY THREE", "A class project lists time, materials, and shared effort used for one output. What is a careful observation?", "The list identifies stated resources used for the class output.", "A resource record can be described without making a business or personal financial conclusion."),
  pathwayUnit("economics-data-pathway-three-development", "uganda-high-school-economics", "economic-data-comparison", "Compare an economic chart", "development", "reasoning", "ECONOMICS · PATHWAY THREE", "Two bars in a classroom chart show different stated amounts for two periods. What is the strongest next step?", "Compare the labels, units, and period definitions before explaining a difference.", "Economic charts need careful reading of their stated labels and scope."),
  pathwayUnit("economics-price-pathway-three-extension", "uganda-high-school-economics", "price-claims", "Limit a price conclusion", "extension", "decision", "ECONOMICS · PATHWAY THREE", "A short classroom example shows one price change and a learner wants to predict every household response. What is the strongest response?", "Describe the stated example and explain why wider response claims need more evidence.", "Economic study supports evidence-aware reasoning, not personal financial direction."),

  pathwayUnit("entrepreneurship-records-pathway-three-foundation", "uganda-high-school-entrepreneurship", "project-records", "Read a project record", "foundation", "evidence", "ENTREPRENEURSHIP · PATHWAY THREE", "A class project log lists one goal, two tasks, and a result still to be checked. What is supported?", "The log shows the stated project plan and its unresolved check.", "A project record makes work visible without guaranteeing an outcome."),
  pathwayUnit("entrepreneurship-feedback-pathway-three-development", "uganda-high-school-entrepreneurship", "feedback-and-revision", "Compare project feedback", "development", "reasoning", "ENTREPRENEURSHIP · PATHWAY THREE", "Two classmates give different comments on a project message. What is the strongest next step?", "Record both comments, identify the stated question behind them, and plan one small comparison.", "Different feedback can inform a limited class test without becoming a commercial promise."),
  pathwayUnit("entrepreneurship-trust-pathway-three-extension", "uganda-high-school-entrepreneurship", "trust-and-claims", "Choose trustworthy project language", "extension", "decision", "ENTREPRENEURSHIP · PATHWAY THREE", "A group wants to omit an uncertainty from a class-project poster. What is the strongest response?", "Use clear supportable language and include what the group still needs to verify.", "Trustworthy communication avoids guarantees and protects learners from unsupported claims."),

  pathwayUnit("english-purpose-pathway-three-foundation", "uganda-high-school-english", "purpose-and-genre", "Identify a text purpose", "foundation", "evidence", "ENGLISH · PATHWAY THREE", "A school text gives a date, location, and invitation to attend. What purpose is best supported?", "The text appears designed to inform readers about a stated event and invite a response.", "Purpose is identified from stated features rather than assumptions about every reader."),
  pathwayUnit("english-cohesion-pathway-three-development", "uganda-high-school-english", "paragraph-cohesion", "Improve paragraph links", "development", "reasoning", "ENGLISH · PATHWAY THREE", "A paragraph has relevant sentences but the links between ideas are unclear. What is the strongest revision step?", "Check the order of ideas and add clear connecting language where it reflects the stated relationship.", "Coherent writing helps readers follow how one supported idea relates to the next."),
  pathwayUnit("english-editing-pathway-three-extension", "uganda-high-school-english", "editing-and-evidence", "Edit an evidence-based claim", "extension", "decision", "ENGLISH · PATHWAY THREE", "A draft includes a strong conclusion but its supporting detail is vague. What is the strongest response?", "Revise the claim or add a specific relevant detail that can be checked in the stated text.", "Editing strengthens the connection between wording, support, and audience."),

  pathwayUnit("physics-circuits-pathway-three-foundation", "uganda-high-school-physics", "circuit-representations", "Read a circuit representation", "foundation", "evidence", "PHYSICS · PATHWAY THREE", "A classroom diagram uses symbols and connecting lines to represent an electrical arrangement. What can be described?", "The diagram shows the stated symbols and connections in a representation.", "A representation can be read for its visible features without becoming a construction or safety instruction."),
  pathwayUnit("physics-estimates-pathway-three-development", "uganda-high-school-physics", "estimates-and-uncertainty", "Compare physical estimates", "development", "reasoning", "PHYSICS · PATHWAY THREE", "Two learners estimate the same classroom distance and give different values. What is the strongest next step?", "Compare the stated unit, reference point, and measurement approach before explaining the difference.", "Estimation is stronger when the method and possible uncertainty are made visible."),
  pathwayUnit("physics-systems-pathway-three-extension", "uganda-high-school-physics", "system-model-claims", "Limit a system model", "extension", "decision", "PHYSICS · PATHWAY THREE", "A simple class model shows one system pattern. What is the strongest conclusion?", "Explain the pattern represented and name a feature the model may leave out.", "A physical model is useful when its scope and limits remain visible."),

  pathwayUnit("mathematics-ratio-pathway-three-foundation", "uganda-high-school-mathematics", "ratios-and-comparison", "Read a stated ratio", "foundation", "evidence", "MATHEMATICS · PATHWAY THREE", "A class record compares 2 blue counters with 3 green counters. Which statement is supported?", "The stated comparison is 2 blue counters for every 3 green counters.", "A ratio describes the relationship in the stated set without adding information not present."),
  pathwayUnit("mathematics-graphs-pathway-three-development", "uganda-high-school-mathematics", "graphs-and-trends", "Compare a graph trend", "development", "reasoning", "MATHEMATICS · PATHWAY THREE", "A graph rises across several labelled points and then stays level. What is the strongest next step?", "Describe the stated change across the labelled points and check the scale before explaining it.", "Graph reasoning begins with labels, scale, and the visible pattern."),
  pathwayUnit("mathematics-context-pathway-three-extension", "uganda-high-school-mathematics", "context-and-reasonableness", "Check a contextual result", "extension", "decision", "MATHEMATICS · PATHWAY THREE", "A calculation gives a very large result for a small classroom collection. What is the strongest response?", "Review the stated steps and units, then explain whether the result fits the classroom context.", "A justified mathematical conclusion checks both the method and the meaning of the result."),

  pathwayUnit("geography-landforms-pathway-three-foundation", "uganda-high-school-geography", "landforms-and-symbols", "Read a landform representation", "foundation", "evidence", "GEOGRAPHY · PATHWAY THREE", "A classroom profile labels a high area, a low area, and a river. What is supported?", "The profile identifies those stated features in that representation.", "A geographic representation can be described without claiming every feature of a real place."),
  pathwayUnit("geography-population-pathway-three-development", "uganda-high-school-geography", "population-records", "Compare population records", "development", "reasoning", "GEOGRAPHY · PATHWAY THREE", "Two class tables list different population values for stated places and years. What is the strongest next step?", "Compare the place names, years, and source notes before explaining a pattern.", "Population reasoning depends on the stated time, place, and collection context."),
  pathwayUnit("geography-risk-pathway-three-extension", "uganda-high-school-geography", "risk-communication", "Check a place-based claim", "extension", "decision", "GEOGRAPHY · PATHWAY THREE", "A post uses one local photograph to make a broad claim about a whole region. What is the strongest response?", "Describe the local evidence and identify what wider records would be needed for the regional claim.", "Place-based conclusions should match the location and scope of their evidence."),

  pathwayUnit("history-artifacts-pathway-three-foundation", "uganda-high-school-history-civics", "artifacts-and-evidence", "Read an artifact description", "foundation", "evidence", "HISTORY AND CIVICS · PATHWAY THREE", "A classroom source describes an object with a date and place label. What is supported?", "The source gives stated date and place information for the described object.", "An artifact description can support careful observation without settling every historical question."),
  pathwayUnit("history-perspective-pathway-three-development", "uganda-high-school-history-civics", "perspective-and-language", "Compare historical language", "development", "reasoning", "HISTORY AND CIVICS · PATHWAY THREE", "Two sources use different words to describe the same event. What is the strongest next step?", "Compare the wording, source context, and other evidence that could clarify the difference.", "Historical reasoning considers how source perspective and language shape an account."),
  pathwayUnit("civics-dialogue-pathway-three-extension", "uganda-high-school-history-civics", "community-dialogue", "Choose a respectful community dialogue", "extension", "decision", "HISTORY AND CIVICS · PATHWAY THREE", "A class is discussing a shared school concern and several views remain unresolved. What is the strongest response?", "Summarise the stated views fairly, identify common needs, and use school guidance for the next step.", "Civic learning can practise respectful participation without giving political direction."),

  pathwayUnit("ict-files-pathway-three-foundation", "uganda-high-school-ict", "files-and-labels", "Read a file label", "foundation", "evidence", "ICT AND DIGITAL SKILLS · PATHWAY THREE", "A class folder contains files with stated names, dates, and formats. What is supported?", "The folder provides those stated file details for the class task.", "Digital information starts with carefully reading the visible record."),
  pathwayUnit("ict-patterns-pathway-three-development", "uganda-high-school-ict", "data-patterns", "Compare a digital pattern", "development", "reasoning", "ICT AND DIGITAL SKILLS · PATHWAY THREE", "A small class dataset shows a repeated value and one different entry. What is the strongest next step?", "Check the stated entries, labels, and collection context before explaining the pattern.", "Data reasoning checks a record before treating a pattern as a conclusion."),
  pathwayUnit("ict-safety-pathway-three-extension", "uganda-high-school-ict", "digital-safety-choices", "Choose a safer digital response", "extension", "decision", "ICT AND DIGITAL SKILLS · PATHWAY THREE", "A message asks a learner to share another person’s details to unlock a class resource. What is the strongest response?", "Do not share the details; check the request with a trusted teacher or appropriate school channel.", "Responsible digital choices protect privacy and seek support when a request is unclear."),

  pathwayUnit("agriculture-seasons-pathway-three-foundation", "uganda-high-school-agriculture", "seasonal-records", "Read a seasonal record", "foundation", "evidence", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY THREE", "A class table lists observation notes for two stated periods. What is supported?", "The table records observations for the two stated periods.", "A seasonal record can be described without becoming practical agricultural instruction."),
  pathwayUnit("agriculture-flow-pathway-three-development", "uganda-high-school-agriculture", "system-flow-comparison", "Compare a system flow", "development", "reasoning", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY THREE", "Two class diagrams show different paths between stated food-system stages. What is the strongest next step?", "Compare the labelled stages and identify what information each diagram does not show.", "System diagrams support classroom reasoning while preserving limits and local context."),
  pathwayUnit("agriculture-evidence-pathway-three-extension", "uganda-high-school-agriculture", "agricultural-evidence-limits", "Limit an agriculture claim", "extension", "decision", "AGRICULTURE AND FOOD SYSTEMS · PATHWAY THREE", "A learner wants to turn one class observation into a recommendation for every farm. What is the strongest response?", "State what the observation shows and avoid issuing a practical recommendation from the limited record.", "Agriculture learning uses evidence-aware reasoning without giving production direction."),

  pathwayUnit("ethics-scenarios-pathway-three-foundation", "uganda-high-school-religion-ethics", "ethical-scenarios", "Recognise a shared concern", "foundation", "evidence", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY THREE", "A class scenario says that two learners want equal speaking time. What is a careful observation?", "The scenario identifies a stated concern about fair participation.", "Ethical learning can name a shared concern without assuming private beliefs."),
  pathwayUnit("ethics-common-ground-pathway-three-development", "uganda-high-school-religion-ethics", "common-ground", "Compare shared reasons", "development", "reasoning", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY THREE", "Different classmates give reasons for a fair class rule. What is the strongest next step?", "Describe the reasons fairly and identify any shared need they point toward.", "Reasoning can find common ground while protecting dignity and voluntary participation."),
  pathwayUnit("ethics-respect-pathway-three-extension", "uganda-high-school-religion-ethics", "respectful-response", "Choose a respectful response", "extension", "decision", "RELIGIOUS AND ETHICAL STUDIES · PATHWAY THREE", "A discussion includes a view that a learner does not share. What is the strongest response?", "Respond to the stated idea respectfully, avoid personal demands, and seek school guidance if needed.", "Respectful dialogue keeps learning separate from personal disclosure or authority claims."),

  pathwayUnit("kiswahili-uhusiano-pathway-three-foundation", "uganda-high-school-kiswahili", "uhusiano-wa-maneno", "Tambua uhusiano wa maneno", "foundation", "evidence", "KISWAHILI · PATHWAY THREE", "Sentensi inaeleza: ‘Mwalimu alitoa mfano, kisha wanafunzi wakauliza swali.’ Jibu lipi linaungwa mkono?", "Mfano ulitolewa kabla ya wanafunzi kuuliza swali.", "Uhusiano wa matukio unaanza na maneno yaliyotolewa katika sentensi."),
  pathwayUnit("kiswahili-hoja-pathway-three-development", "uganda-high-school-kiswahili", "hoja-na-ushahidi", "Unganisha hoja na ushahidi", "development", "reasoning", "KISWAHILI · PATHWAY THREE", "Mwanafunzi ana hoja kuhusu maktaba lakini sababu yake haijaelezwa. Hatua ipi ni bora?", "Ongeza sababu inayofaa na maelezo yanayoiunga mkono.", "Hoja wazi huunganisha dai, sababu, na ushahidi unaoweza kuchunguzwa."),
  pathwayUnit("kiswahili-uhariri-pathway-three-extension", "uganda-high-school-kiswahili", "uhariri-na-heshima", "Chagua uhariri wa heshima", "extension", "decision", "KISWAHILI · PATHWAY THREE", "Rasimu ya ujumbe ina maneno yanayoweza kumdhalilisha msomaji. Hatua ipi ni bora?", "Rekebisha lugha iwe wazi na yenye heshima huku ukihifadhi kusudi la ujumbe.", "Uhariri wa heshima hulinda hadhira na huweka kusudi la maandishi wazi."),

  pathwayUnit("literature-setting-pathway-three-foundation", "uganda-high-school-literature", "setting-and-detail", "Notice a setting detail", "foundation", "evidence", "LITERATURE · PATHWAY THREE", "A scene names a quiet road, late afternoon, and a character waiting. What is a careful observation?", "The scene gives stated setting details that frame the character’s waiting.", "Literary observation begins with textual details before a broader interpretation."),
  pathwayUnit("literature-narration-pathway-three-development", "uganda-high-school-literature", "narration-and-viewpoint", "Compare narrative viewpoint", "development", "reasoning", "LITERATURE · PATHWAY THREE", "A narrator reports one character’s thoughts but not another’s. What is the strongest next step?", "Describe the stated viewpoint and consider how it shapes the information available to the reader.", "Narrative reasoning connects viewpoint to the evidence a text provides."),
  pathwayUnit("literature-comparison-pathway-three-extension", "uganda-high-school-literature", "comparative-readings", "Choose a supported comparison", "extension", "decision", "LITERATURE · PATHWAY THREE", "Two short texts use different images for a similar idea. What is the strongest response?", "Compare the stated images and explain one supported similarity or difference.", "Comparative reading remains grounded in the features of each text."),

  pathwayUnit("fine-art-texture-pathway-three-foundation", "uganda-high-school-fine-art", "texture-and-mark", "Describe a visual texture", "foundation", "evidence", "FINE ART · PATHWAY THREE", "A classroom image uses short repeated marks in one area and smooth colour in another. What is a careful observation?", "The image uses different stated mark and colour treatments across the two areas.", "Visual description names observable choices without imposing one interpretation."),
  pathwayUnit("fine-art-revision-pathway-three-development", "uganda-high-school-fine-art", "revision-and-intent", "Compare an art revision", "development", "reasoning", "FINE ART · PATHWAY THREE", "A learner changes the size of one focal shape after feedback. What is the strongest next step?", "Explain the intended visual effect and compare the revised work with the earlier choice.", "Creative revision connects an observable change to a stated intention."),
  pathwayUnit("fine-art-display-pathway-three-extension", "uganda-high-school-fine-art", "display-and-context", "Choose a respectful display response", "extension", "decision", "FINE ART · PATHWAY THREE", "A group plans to display classroom artwork with comments from viewers. What is the strongest response?", "Use respectful feedback prompts and follow school guidance about names, images, and sharing.", "Art display can support learning while protecting maker dignity and consent."),

  pathwayUnit("technical-drawing-dimensions-pathway-three-foundation", "uganda-high-school-technical-drawing", "dimension-labels", "Read dimension labels", "foundation", "evidence", "TECHNICAL DRAWING · PATHWAY THREE", "A classroom drawing includes stated dimension labels beside two edges. What is supported?", "The labels provide the stated measurements for those drawing edges.", "Dimension labels can be read carefully without turning a classroom drawing into a construction instruction."),
  pathwayUnit("technical-drawing-projection-pathway-three-development", "uganda-high-school-technical-drawing", "projection-comparison", "Compare drawing views", "development", "reasoning", "TECHNICAL DRAWING · PATHWAY THREE", "Two labelled views show different faces of one classroom object model. What is the strongest next step?", "Compare the stated views and identify which feature is visible in each one.", "Multiple views improve communication when their labels and limits remain clear."),
  pathwayUnit("technical-drawing-checks-pathway-three-extension", "uganda-high-school-technical-drawing", "accuracy-checks", "Choose a drawing accuracy check", "extension", "decision", "TECHNICAL DRAWING · PATHWAY THREE", "A reviewer finds that one drawing label and one shown feature do not agree. What is the strongest response?", "Identify the mismatch, revise the classroom communication, and seek teacher review where needed.", "A careful drawing check improves clarity without providing construction direction."),

  pathwayUnit("food-nutrition-menu-pathway-three-foundation", "uganda-high-school-food-nutrition", "menu-information", "Read stated menu information", "foundation", "evidence", "FOOD AND NUTRITION · PATHWAY THREE", "A classroom menu example lists a meal name, ingredients, and a source note. What is supported?", "The example provides those stated menu details and source information.", "Food-information learning can read a source without becoming personal nutrition guidance."),
  pathwayUnit("food-nutrition-data-pathway-three-development", "uganda-high-school-food-nutrition", "food-information-comparison", "Compare food information", "development", "reasoning", "FOOD AND NUTRITION · PATHWAY THREE", "Two classroom sources make different claims about a food item. What is the strongest next step?", "Compare what each source states, what evidence it names, and what remains uncertain.", "Source comparison supports learning without directing personal food choices."),
  pathwayUnit("food-nutrition-boundaries-pathway-three-extension", "uganda-high-school-food-nutrition", "health-claim-boundaries", "Limit a food-related claim", "extension", "decision", "FOOD AND NUTRITION · PATHWAY THREE", "A learner wants to tell classmates a source result will apply equally to everyone. What is the strongest response?", "State the source limit and keep personal questions with an appropriate adult or professional.", "Responsible learning keeps general information separate from personal dietary or health guidance."),

  pathwayUnit("music-texture-pathway-three-foundation", "uganda-high-school-music", "musical-texture", "Describe a musical layer", "foundation", "evidence", "MUSIC · PATHWAY THREE", "A classroom excerpt begins with one repeated sound and later adds a second pattern. What is a careful observation?", "The excerpt contains a stated repeated layer and a later added pattern.", "Music listening can describe audible layers without assigning one required feeling."),
  pathwayUnit("music-structure-pathway-three-development", "uganda-high-school-music", "form-and-repetition", "Compare a musical structure", "development", "reasoning", "MUSIC · PATHWAY THREE", "A group notices that one section returns after a contrasting section. What is the strongest next step?", "Describe the stated return and agree on a respectful shared way to check it in rehearsal.", "Musical reasoning focuses on observable form and inclusive class practice."),
  pathwayUnit("music-sharing-pathway-three-extension", "uganda-high-school-music", "performance-sharing", "Choose respectful performance sharing", "extension", "decision", "MUSIC · PATHWAY THREE", "A learner wants to share a class performance recording beyond the lesson. What is the strongest response?", "Check permission and school guidance before sharing, and respect the performers involved.", "Music sharing should protect consent and avoid claims of professional assessment."),

  pathwayUnit("physical-education-observation-pathway-three-foundation", "uganda-high-school-physical-education", "role-change-observations", "Read a participation observation", "foundation", "evidence", "PHYSICAL EDUCATION · PATHWAY THREE", "A teacher-guided class note says groups changed roles after a signal. What is supported?", "The note records the stated role change during that activity.", "Participation observations can be read without making fitness, health, or coaching judgements."),
  pathwayUnit("physical-education-access-pathway-three-development", "uganda-high-school-physical-education", "access-and-choice", "Compare participation choices", "development", "reasoning", "PHYSICAL EDUCATION · PATHWAY THREE", "A class activity offers two teacher-approved roles and learners choose different ones. What is the strongest next step?", "Notice the stated choices, invite respectful preferences, and use teacher guidance for access questions.", "Inclusive participation recognises choice and dignity without making assumptions about learners."),
  pathwayUnit("physical-education-reflection-pathway-three-extension", "uganda-high-school-physical-education", "fair-participation-next-step", "Choose a fair participation reflection", "extension", "decision", "PHYSICAL EDUCATION · PATHWAY THREE", "After a teacher-guided activity, which reflection is most useful?", "Identify one participation pattern and one respectful question the group can discuss with the teacher.", "Reflection stays focused on fair participation rather than performance, health, or coaching judgement."),
];

export const HIGH_SCHOOL_TOPIC_UNITS: readonly HighSchoolTopicUnit[] = [...CORE_TOPIC_UNITS, ...PATHWAY_TWO_UNITS, ...PATHWAY_THREE_UNITS].flatMap((unit) => [unit, reflectionCompanion(unit)]);

export function topicUnitsForPack(packId: string): HighSchoolTopicUnit[] {
  return HIGH_SCHOOL_TOPIC_UNITS.filter((unit) => unit.packId === packId);
}

export function topicUnitForId(unitId: string): HighSchoolTopicUnit | null {
  return HIGH_SCHOOL_TOPIC_UNITS.find((unit) => unit.id === unitId) ?? null;
}

export function learningBandForLevel(level: HighSchoolLevel): Exclude<HighSchoolTopicBand, "all_levels"> {
  if (level === "s1" || level === "s2") return "foundation";
  if (level === "s3" || level === "s4") return "development";
  return "extension";
}

export function isUnitRecommendedForLevel(unit: HighSchoolTopicUnit, level: HighSchoolLevel): boolean {
  return unit.band === "all_levels" || unit.band === learningBandForLevel(level);
}

export function topicUnitModesLabel(mode: HighSchoolTopicMode): string {
  return ({ evidence: "Read evidence", reasoning: "Reason it through", decision: "Choose a next step", reflection: "Reflect privately" })[mode];
}
