import type { HighSchoolLevel } from "../lib/high-school-store";

export type HighSchoolTopicBand = "foundation" | "development" | "extension" | "all_levels";
export type HighSchoolTopicMode = "evidence" | "reasoning" | "decision" | "reflection";

export type HighSchoolTopicUnit = {
  id: string;
  packId: string;
  topicId: string;
  title: string;
  band: HighSchoolTopicBand;
  mode: HighSchoolTopicMode;
  cue: string;
  prompt: string;
  options?: readonly string[];
  bestOption?: string;
  explanation: string;
  reflectionPrompt?: string;
  boundaryNote?: string;
};

/**
 * Original Rounds topic units are intentionally separate from the reviewed
 * starter activities. The catalogue is extended per subject without copying
 * external curriculum wording or claiming examination alignment.
 */
function topicUnit(
  id: string,
  packId: string,
  topicId: string,
  title: string,
  band: Exclude<HighSchoolTopicBand, "all_levels">,
  mode: Exclude<HighSchoolTopicMode, "reflection">,
  cue: string,
  prompt: string,
  options: readonly string[],
  bestOption: string,
  explanation: string,
  boundaryNote?: string,
): HighSchoolTopicUnit {
  return { id, packId, topicId, title, band, mode, cue, prompt, options, bestOption, explanation, boundaryNote };
}

function reflectionCompanion(unit: HighSchoolTopicUnit): HighSchoolTopicUnit {
  return {
    id: `${unit.id}-reflection`,
    packId: unit.packId,
    topicId: `${unit.topicId}-reflection`,
    title: `Reflect on ${unit.title.toLowerCase()}`,
    band: unit.band,
    mode: "reflection",
    cue: "PRIVATE REFLECTION",
    prompt: "Pause and write one short private note about the study move you would use next time.",
    explanation: "Private reflection helps you notice a useful study move without asking Rounds to judge a personal response.",
    reflectionPrompt: `What is one question, check, or strategy you would carry forward from “${unit.title}”?`,
    boundaryNote: unit.boundaryNote,
  };
}

const CORE_TOPIC_UNITS: readonly HighSchoolTopicUnit[] = [
  topicUnit("biology-living-systems-foundation", "uganda-high-school-biology", "living-systems", "Observe living systems", "foundation", "evidence", "BIOLOGY · FOUNDATION", "A classroom observation notes that a plant bends toward a window over several days. Which statement stays closest to the stated observation?", ["The plant changed its direction toward the window during the stated observation.", "The observation proves one cause in every setting.", "Plants never change direction.", "The observation gives no information at all."], "The plant changed its direction toward the window during the stated observation.", "The stated observation supports a careful description before a broader explanation is considered."),
  topicUnit("biology-variables-development", "uganda-high-school-biology", "variables-and-evidence", "Compare biological variables", "development", "reasoning", "BIOLOGY · DEVELOPMENT", "Two classroom groups observe the same kind of seedling but record different light conditions. What is the clearest next reasoning step?", ["Compare the stated light condition while keeping track of other recorded differences.", "Assume one observation proves every condition is irrelevant.", "Ignore the written records.", "Treat a guess as a measured result."], "Compare the stated light condition while keeping track of other recorded differences.", "Careful comparison identifies what differs and what else must be considered before drawing a conclusion."),
  topicUnit("biology-explanation-extension", "uganda-high-school-biology", "explanation-limits", "Explain with limits", "extension", "decision", "BIOLOGY · EXTENSION", "A learner wants to turn one short observation into a broad claim about every organism. What is the strongest response?", ["State the observation, explain a possible pattern, and name what further evidence would be needed.", "Declare the broad claim proven immediately.", "Remove any observation that seems different.", "Replace the record with a personal opinion."], "State the observation, explain a possible pattern, and name what further evidence would be needed.", "A stronger explanation connects evidence to a possible pattern and makes its limits visible."),

  topicUnit("chemistry-particle-description-foundation", "uganda-high-school-chemistry", "particle-descriptions", "Describe a stated change", "foundation", "evidence", "CHEMISTRY · FOUNDATION", "A classroom note says that a solid sample was warmed and later appeared as a liquid. Which statement is supported by the note?", ["The stated sample changed from the recorded solid appearance to a liquid appearance.", "The note proves the identity of every substance involved.", "Warming never changes observations.", "No change was recorded."], "The stated sample changed from the recorded solid appearance to a liquid appearance.", "The note supports a description of the recorded change without adding unstated details."),
  topicUnit("chemistry-pattern-comparison-development", "uganda-high-school-chemistry", "patterns-and-variables", "Compare a stated pattern", "development", "reasoning", "CHEMISTRY · DEVELOPMENT", "Two classroom samples are described with the same starting amount but different stated conditions. What should a learner do before explaining a difference?", ["Compare the recorded conditions and identify which details are missing.", "Assume the result has one cause without checking conditions.", "Ignore the starting information.", "Rename the samples instead of using the record."], "Compare the recorded conditions and identify which details are missing.", "A useful chemical explanation begins with the stated conditions and the limits of the available record."),
  topicUnit("chemistry-claim-check-extension", "uganda-high-school-chemistry", "claim-checking", "Check a chemistry claim", "extension", "decision", "CHEMISTRY · EXTENSION", "A message claims that a classroom observation proves a product is always safe in every circumstance. What is the strongest study response?", ["Separate the observation from the safety claim and ask what evidence the claim would require.", "Share the claim as a universal conclusion.", "Treat a label as a complete safety instruction.", "Ignore the difference between a class task and a real-world decision."], "Separate the observation from the safety claim and ask what evidence the claim would require.", "The response distinguishes classroom evidence from a broad safety claim and keeps practical decisions outside the activity."),

  topicUnit("economics-scarcity-foundation", "uganda-high-school-economics", "scarcity-and-choice", "Recognise a trade-off", "foundation", "evidence", "ECONOMICS · FOUNDATION", "A class club has a fixed amount of funds and lists two useful materials it cannot both buy in full. What does the situation show?", ["A choice is needed because the stated resources are limited.", "The club has unlimited resources.", "Both materials cost nothing.", "No decision is involved."], "A choice is needed because the stated resources are limited.", "Scarcity means a learner or group must make choices when stated resources are limited."),
  topicUnit("economics-comparison-development", "uganda-high-school-economics", "comparisons-and-reasons", "Compare stated choices", "development", "reasoning", "ECONOMICS · DEVELOPMENT", "A learner compares two class-project choices. Which approach gives the clearest economic reasoning?", ["Name the stated benefit and what is given up for each choice.", "Name only the preferred choice with no reason.", "Pretend one choice has no trade-off.", "Use a rumour instead of the project details."], "Name the stated benefit and what is given up for each choice.", "A comparison is stronger when it explains both a stated benefit and an acknowledged trade-off."),
  topicUnit("economics-claim-limits-extension", "uganda-high-school-economics", "claims-and-limits", "Limit an economic conclusion", "extension", "decision", "ECONOMICS · EXTENSION", "A class survey has a small stated response group. A learner wants to make a claim about all families. What is the strongest response?", ["Describe what the stated responses show and explain why a wider claim would need more evidence.", "Say the small group proves every family behaves the same way.", "Discard responses that differ.", "Turn the survey into personal financial advice."], "Describe what the stated responses show and explain why a wider claim would need more evidence.", "A responsible conclusion matches the claim to the evidence and avoids personal financial direction."),

  topicUnit("entrepreneurship-customer-foundation", "uganda-high-school-entrepreneurship", "customer-evidence", "Read customer feedback", "foundation", "evidence", "ENTREPRENEURSHIP · FOUNDATION", "A class project receives one comment asking for clearer collection times. Which statement is supported?", ["One stated commenter wants clearer collection-time information.", "Every customer wants exactly the same thing.", "The comment proves the project will succeed.", "The comment gives no information."], "One stated commenter wants clearer collection-time information.", "One comment can identify a possible question to explore without proving what every customer wants."),
  topicUnit("entrepreneurship-testing-development", "uganda-high-school-entrepreneurship", "testing-and-records", "Plan a simple test", "development", "reasoning", "ENTREPRENEURSHIP · DEVELOPMENT", "A learner wants to change a class-project message after two different comments. What is the strongest next step?", ["Record the comments, state a small test, and compare the response before making a broader change.", "Change everything without recording why.", "Ignore the comments because they differ.", "Promise a business outcome to classmates."], "Record the comments, state a small test, and compare the response before making a broader change.", "A small recorded test helps learners compare feedback without treating a class project as a guarantee."),
  topicUnit("entrepreneurship-ethical-choice-extension", "uganda-high-school-entrepreneurship", "ethical-choices", "Choose an ethical project response", "extension", "decision", "ENTREPRENEURSHIP · EXTENSION", "A class project can make a claim that sounds impressive but cannot be supported by its records. What is the strongest next step?", ["Use a clear, supportable description and name what the project still needs to check.", "Make the unsupported claim to attract attention.", "Hide the missing record.", "Tell classmates how to spend personal money."], "Use a clear, supportable description and name what the project still needs to check.", "Responsible project communication does not use unsupported claims or become personal financial advice."),

  topicUnit("english-main-idea-foundation", "uganda-high-school-english", "main-idea-and-detail", "Identify a supported main idea", "foundation", "evidence", "ENGLISH · FOUNDATION", "A short paragraph states that a reading group meets weekly, shares one question, and records one useful idea. Which main idea is best supported?", ["The group uses a regular process for shared reading and discussion.", "Every learner already agrees on every text.", "The group never records ideas.", "The paragraph proves reading is easy for everyone."], "The group uses a regular process for shared reading and discussion.", "A main idea connects the stated details without making a broader claim the paragraph does not support."),
  topicUnit("english-argument-development", "uganda-high-school-english", "claims-and-reasons", "Connect a claim to a reason", "development", "reasoning", "ENGLISH · DEVELOPMENT", "A learner writes, ‘The library should extend its opening time,’ but gives no stated reason. What would make the argument clearer?", ["Add a relevant reason and a detail that supports it.", "Repeat the claim more loudly.", "Add an unrelated personal attack.", "Remove the reader’s context."], "Add a relevant reason and a detail that supports it.", "An argument becomes clearer when the claim is connected to a relevant reason and support."),
  topicUnit("english-revision-extension", "uganda-high-school-english", "revision-and-audience", "Revise for an audience", "extension", "decision", "ENGLISH · EXTENSION", "A learner drafts a school notice with a clear purpose but no next step for readers. What is the strongest revision?", ["Add the specific action, time, or response the reader needs while keeping the purpose clear.", "Remove all useful details.", "Add complex words without a purpose.", "Use private details about other learners."], "Add the specific action, time, or response the reader needs while keeping the purpose clear.", "Audience-aware revision helps readers understand what matters and what they should do next."),

  topicUnit("physics-motion-foundation", "uganda-high-school-physics", "motion-observations", "Describe a motion record", "foundation", "evidence", "PHYSICS · FOUNDATION", "A classroom record says a trolley travelled 2 metres in one stated interval and 4 metres in the next equal interval. Which statement is supported?", ["The record shows different stated distances across the two equal intervals.", "The record proves every trolley behaves the same way.", "The trolley did not move.", "The distances are identical."], "The record shows different stated distances across the two equal intervals.", "A motion record supports a careful description of stated distances before explaining why they differ."),
  topicUnit("physics-measurement-development", "uganda-high-school-physics", "measurement-and-patterns", "Compare measurements", "development", "reasoning", "PHYSICS · DEVELOPMENT", "Two groups record different measurements for the same classroom object. What is the strongest first reasoning step?", ["Check the stated units, method, and recorded conditions before choosing an explanation.", "Select the larger number without checking.", "Assume one group was careless without evidence.", "Ignore units."], "Check the stated units, method, and recorded conditions before choosing an explanation.", "Measurement reasoning depends on units, method, and the limits of the stated record."),
  topicUnit("physics-model-limits-extension", "uganda-high-school-physics", "models-and-limits", "Limit a physical model", "extension", "decision", "PHYSICS · EXTENSION", "A learner uses a simple classroom model to explain a pattern and wants to claim that the model captures every real situation. What is the strongest response?", ["Explain what the model represents and name a feature it may not capture.", "Treat the model as identical to every real situation.", "Remove any difference from discussion.", "Use the model as a safety instruction."], "Explain what the model represents and name a feature it may not capture.", "Models can be useful while still having stated limits; a classroom model is not a safety instruction."),

  topicUnit("mathematics-pattern-foundation", "uganda-high-school-mathematics", "patterns-and-rules", "Read a stated pattern", "foundation", "evidence", "MATHEMATICS · FOUNDATION", "A number pattern is shown as 4, 7, 10, 13. Which next value follows the stated pattern?", ["16", "15", "17", "18"], "16", "The stated pattern increases by 3 each time, so 13 + 3 gives 16."),
  topicUnit("mathematics-representation-development", "uganda-high-school-mathematics", "representations-and-checks", "Choose a useful representation", "development", "reasoning", "MATHEMATICS · DEVELOPMENT", "A learner has a table of values and wants to see whether a change is steady. What is the strongest next step?", ["Organise the values clearly and compare the stated differences between consecutive entries.", "Choose an answer before looking at the table.", "Remove values that do not fit a guess.", "Treat a drawing as exact without a scale."], "Organise the values clearly and compare the stated differences between consecutive entries.", "A structured representation makes the stated pattern easier to check rather than guess."),
  topicUnit("mathematics-justification-extension", "uganda-high-school-mathematics", "justification-and-limits", "Justify a mathematical conclusion", "extension", "decision", "MATHEMATICS · EXTENSION", "A learner gets a numerical result but cannot explain the steps or units. What is the strongest response?", ["Show the stated steps, check the units, and explain what the result represents in the classroom problem.", "Keep only the final number.", "Change units to make the number look better.", "Use the result as professional financial advice."], "Show the stated steps, check the units, and explain what the result represents in the classroom problem.", "A justified result shows the calculation path, appropriate units, and the limits of its classroom context."),

  topicUnit("geography-map-foundation", "uganda-high-school-geography", "maps-and-place", "Read a stated map detail", "foundation", "evidence", "GEOGRAPHY · FOUNDATION", "A classroom map key marks a blue line as a river and a black line as a road. Which statement is supported?", ["The key identifies the stated blue line as a river and black line as a road.", "The map proves every nearby settlement is identical.", "The key gives no information.", "A road and river are the same feature."], "The key identifies the stated blue line as a river and black line as a road.", "A map key supports careful description of the symbols it defines."),
  topicUnit("geography-data-development", "uganda-high-school-geography", "data-and-comparison", "Compare geographic records", "development", "reasoning", "GEOGRAPHY · DEVELOPMENT", "Two stated rainfall records differ across months. What is the strongest next reasoning step?", ["Compare the recorded months, amounts, and any stated collection limits before explaining a pattern.", "Say one month proves a permanent climate rule.", "Ignore the time labels.", "Use the record to predict every future season with certainty."], "Compare the recorded months, amounts, and any stated collection limits before explaining a pattern.", "Geographic reasoning compares stated records and does not turn a small record into a permanent conclusion."),
  topicUnit("geography-environment-extension", "uganda-high-school-geography", "environmental-claims", "Check an environmental claim", "extension", "decision", "GEOGRAPHY · EXTENSION", "A learner sees a claim that one local observation proves an environmental change affects every place in the same way. What is the strongest response?", ["Describe the local evidence, ask what wider records are needed, and note that places may differ.", "Share the claim as a universal fact.", "Ignore all place differences.", "Use the observation as an official fieldwork instruction."], "Describe the local evidence, ask what wider records are needed, and note that places may differ.", "The response respects local evidence while recognising that wider geographic claims need wider support."),

  topicUnit("history-source-foundation", "uganda-high-school-history-civics", "sources-and-statements", "Read a historical source statement", "foundation", "evidence", "HISTORY AND CIVICS · FOUNDATION", "A classroom source says that a meeting was held in a stated year. Which statement is supported?", ["The source states that a meeting was held in that year.", "The source proves every person agreed at the meeting.", "The source gives no date information.", "The source proves all later events."], "The source states that a meeting was held in that year.", "A source can support what it states without proving every wider conclusion about the event."),
  topicUnit("history-corroboration-development", "uganda-high-school-history-civics", "corroboration-and-timelines", "Compare source accounts", "development", "reasoning", "HISTORY AND CIVICS · DEVELOPMENT", "Two classroom sources describe the same event from different viewpoints. What is the strongest next step?", ["Compare what each source states, who produced it, and what further evidence could clarify differences.", "Choose one source because it is shorter.", "Remove the source that differs.", "Assume viewpoint makes all evidence useless."], "Compare what each source states, who produced it, and what further evidence could clarify differences.", "Historical reasoning compares accounts and considers what each one can and cannot establish."),
  topicUnit("civics-process-extension", "uganda-high-school-history-civics", "civic-processes", "Choose a respectful civic process", "extension", "decision", "HISTORY AND CIVICS · EXTENSION", "A class wants to raise a school-community issue but learners disagree about the next step. What is the strongest response?", ["Use a respectful process, identify stated evidence, and follow school guidance for the next discussion step.", "Silence learners with a different view.", "Share private details about classmates.", "Treat a class discussion as political instruction."], "Use a respectful process, identify stated evidence, and follow school guidance for the next discussion step.", "Civic learning can practise respectful evidence-aware process without giving political direction."),

  topicUnit("ict-information-foundation", "uganda-high-school-ict", "digital-information", "Read a digital source detail", "foundation", "evidence", "ICT AND DIGITAL SKILLS · FOUNDATION", "A classroom webpage shows an author name, a date, and a claim. Which statement is supported?", ["The page provides a stated author name and date alongside its claim.", "The claim is automatically true because it is online.", "The page has no source details.", "Every online page has the same reliability."], "The page provides a stated author name and date alongside its claim.", "Digital literacy begins with noticing stated source details before judging a claim."),
  topicUnit("ict-data-development", "uganda-high-school-ict", "data-and-privacy", "Plan a responsible data check", "development", "reasoning", "ICT AND DIGITAL SKILLS · DEVELOPMENT", "A class survey includes names even though a summary can be made without them. What is the strongest next reasoning step?", ["Ask whether names are needed for the stated class purpose and use teacher guidance before collecting extra details.", "Collect every possible detail by default.", "Share responses in a group chat.", "Assume classmates have no privacy interests."], "Ask whether names are needed for the stated class purpose and use teacher guidance before collecting extra details.", "Responsible digital work considers what information is necessary and protects learner privacy."),
  topicUnit("ict-claim-extension", "uganda-high-school-ict", "digital-claims-and-actions", "Respond to a digital claim", "extension", "decision", "ICT AND DIGITAL SKILLS · EXTENSION", "A post urges learners to forward a dramatic claim immediately but gives no source. What is the strongest response?", ["Pause, identify the missing source, check with a reliable reference or teacher, and avoid forwarding unverified content.", "Forward it quickly because it is dramatic.", "Add personal details to make it seem reliable.", "Assume deleting a source makes a claim stronger."], "Pause, identify the missing source, check with a reliable reference or teacher, and avoid forwarding unverified content.", "The response supports careful source checking and avoids spreading unverified digital content."),

  topicUnit("agriculture-records-foundation", "uganda-high-school-agriculture", "records-and-observations", "Read a stated farm record", "foundation", "evidence", "AGRICULTURE AND FOOD SYSTEMS · FOUNDATION", "A classroom record lists a stated number of plants observed on two dates. Which statement is supported?", ["The record contains observations for the two stated dates.", "The record proves a production outcome for every setting.", "The record replaces practical guidance.", "The dates are irrelevant."], "The record contains observations for the two stated dates.", "A record supports careful description of what was noted without becoming practical production instruction."),
  topicUnit("agriculture-comparison-development", "uganda-high-school-agriculture", "conditions-and-patterns", "Compare stated conditions", "development", "reasoning", "AGRICULTURE AND FOOD SYSTEMS · DEVELOPMENT", "Two class plots have different stated observation records. What is the strongest next reasoning step?", ["Compare the recorded conditions and ask what additional information would be needed before explaining a difference.", "Give a farming instruction from one record.", "Assume one observation proves a universal rule.", "Ignore the record dates."], "Compare the recorded conditions and ask what additional information would be needed before explaining a difference.", "A careful classroom comparison remains within the records and does not become farming direction."),
  topicUnit("agriculture-sustainability-extension", "uganda-high-school-agriculture", "sustainability-claims", "Check a sustainability claim", "extension", "decision", "AGRICULTURE AND FOOD SYSTEMS · EXTENSION", "A learner claims that one classroom result proves a practice is sustainable everywhere. What is the strongest response?", ["State what the classroom record shows, identify the wider evidence needed, and avoid issuing a practical instruction.", "Present the result as a universal farming rule.", "Ignore local conditions.", "Promise an outcome to another learner."], "State what the classroom record shows, identify the wider evidence needed, and avoid issuing a practical instruction.", "Sustainability reasoning matches the strength of a claim to the available evidence and local context."),

  topicUnit("ethics-perspectives-foundation", "uganda-high-school-religion-ethics", "perspectives-and-respect", "Recognise a perspective", "foundation", "evidence", "RELIGIOUS AND ETHICAL STUDIES · FOUNDATION", "A learner says that a community tradition matters to their family. Which statement is most careful?", ["The learner has shared a value-based perspective that can be heard respectfully.", "The statement proves every family holds the same view.", "The learner must reveal private details.", "No respectful response is possible."], "The learner has shared a value-based perspective that can be heard respectfully.", "Ethical discussion can recognise a perspective while avoiding assumptions about everyone else."),
  topicUnit("ethics-reasons-development", "uganda-high-school-religion-ethics", "reasons-and-dialogue", "Compare respectful reasons", "development", "reasoning", "RELIGIOUS AND ETHICAL STUDIES · DEVELOPMENT", "Classmates suggest different ways to organise a school activity and give reasons connected to dignity and participation. What is the strongest next step?", ["Describe each stated reason fairly and identify any shared needs before proposing a response.", "Mock the view that differs.", "Demand private belief information.", "Pretend reasons are unnecessary."], "Describe each stated reason fairly and identify any shared needs before proposing a response.", "Respectful dialogue compares ideas and reasons while protecting personal dignity."),
  topicUnit("ethics-process-extension", "uganda-high-school-religion-ethics", "inclusive-processes", "Choose an inclusive process", "extension", "decision", "RELIGIOUS AND ETHICAL STUDIES · EXTENSION", "A class must discuss a sensitive community question. What is the strongest study process?", ["Use voluntary respectful discussion, school guidance, and shared needs while keeping personal details private.", "Choose one view before listening.", "Force learners to disclose beliefs.", "Treat the discussion as religious authority."], "Use voluntary respectful discussion, school guidance, and shared needs while keeping personal details private.", "The process keeps the activity focused on respectful learning rather than religious authority or private disclosure."),

  topicUnit("kiswahili-maana-foundation", "uganda-high-school-kiswahili", "maana-katika-muktadha", "Maana katika muktadha", "foundation", "evidence", "KISWAHILI · FOUNDATION", "Sentensi inasema: ‘Wanafunzi walikaa pamoja ili kusoma kabla ya mjadala.’ Jibu lipi linaungwa mkono?", ["Wanafunzi walikutana kusoma kabla ya mjadala.", "Kila mwanafunzi alisoma kitabu kilekile.", "Mjadala haukuwepo.", "Sentensi haielezi chochote."], "Wanafunzi walikutana kusoma kabla ya mjadala.", "Jibu bora hutumia maneno yaliyotolewa bila kuongeza maelezo ambayo sentensi haijasema."),
  topicUnit("kiswahili-ujumbe-development", "uganda-high-school-kiswahili", "ujumbe-na-hadhira", "Panga ujumbe kwa hadhira", "development", "reasoning", "KISWAHILI · DEVELOPMENT", "Mwanafunzi anaandika ujumbe kwa kikundi cha kusoma lakini hana kusudi wala hatua inayofuata. Hatua ipi ni bora?", ["Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata.", "Ongeza maneno mengi bila kusudi.", "Tumia kejeli ili watu wajibu.", "Ondoa maelezo yote."], "Taja hadhira, kusudi, maelezo muhimu, na hatua inayofuata.", "Ujumbe wazi huunganisha hadhira, kusudi, maelezo muhimu, na hatua inayofuata."),
  topicUnit("kiswahili-mawasiliano-extension", "uganda-high-school-kiswahili", "mawasiliano-ya-heshima", "Chagua mawasiliano ya heshima", "extension", "decision", "KISWAHILI · EXTENSION", "Katika kikundi cha kusoma, mtu anapendekeza kumdhalilisha mwandishi wa ujumbe wenye makosa. Hatua ipi inaonyesha heshima?", ["Eleza sehemu inayohitaji ufafanuzi kwa heshima na mwalike mwandishi kurekebisha ujumbe.", "Tumia kejeli ili wengine wacheke.", "Sambaza ujumbe bila sababu.", "Kataa kusoma ujumbe wowote."], "Eleza sehemu inayohitaji ufafanuzi kwa heshima na mwalike mwandishi kurekebisha ujumbe.", "Mawasiliano ya heshima hulenga ujumbe na ufafanuzi bila kumdhalilisha mtu."),

  topicUnit("literature-detail-foundation", "uganda-high-school-literature", "textual-details", "Start with a textual detail", "foundation", "evidence", "LITERATURE · FOUNDATION", "In a short scene, a character pauses, checks a note, and says, ‘I should confirm this first.’ Which interpretation is best supported?", ["The character is cautious before making a conclusion.", "The character has proved everyone else is wrong.", "The character will never act.", "The scene gives no detail."], "The character is cautious before making a conclusion.", "A stated action and line can support a careful interpretation without proving a broader trait."),
  topicUnit("literature-theme-development", "uganda-high-school-literature", "themes-and-support", "Connect a theme to support", "development", "reasoning", "LITERATURE · DEVELOPMENT", "A learner says a text is about trust but cannot point to a scene or line. What is the strongest next step?", ["Choose a stated detail and explain how it may support the possible theme.", "Repeat the theme claim without a detail.", "Assume the author’s private life proves the theme.", "Remove lines that suggest another reading."], "Choose a stated detail and explain how it may support the possible theme.", "Theme discussion is stronger when it connects an interpretation to a stated textual detail."),
  topicUnit("literature-readings-extension", "uganda-high-school-literature", "supported-readings", "Compare supported readings", "extension", "decision", "LITERATURE · EXTENSION", "Two readers give different interpretations of a character’s silence and cite different lines. What is the strongest response?", ["Compare the cited lines, explain each support, and note what the text does not settle.", "Declare one reader cannot discuss the text.", "Use personal attacks as evidence.", "Delete a different interpretation."], "Compare the cited lines, explain each support, and note what the text does not settle.", "Literary discussion can compare different readings when each remains connected to the text."),

  topicUnit("fine-art-observation-foundation", "uganda-high-school-fine-art", "visual-observation", "Describe a visible choice", "foundation", "evidence", "FINE ART · FOUNDATION", "A classroom artwork places a bright shape near the centre and darker tones around it. Which statement is most careful?", ["The contrast and placement make the shape visually noticeable.", "Every viewer must give the shape the same meaning.", "The artwork has no design choices.", "Darker tones cannot be used in art."], "The contrast and placement make the shape visually noticeable.", "Observation can describe visible choices without claiming that every viewer has the same interpretation."),
  topicUnit("fine-art-purpose-development", "uganda-high-school-fine-art", "purpose-and-process", "Connect purpose to a choice", "development", "reasoning", "FINE ART · DEVELOPMENT", "A learner plans a classroom artwork about a familiar place. What is the strongest planning step?", ["State an intended message, choose visible design features, and plan one revision check.", "Use random features without a purpose.", "Copy a classmate’s work without discussion.", "Treat the plan as professional assessment."], "State an intended message, choose visible design features, and plan one revision check.", "A creative process can connect purpose, design choices, and reflection without claiming a professional judgement."),
  topicUnit("fine-art-critique-extension", "uganda-high-school-fine-art", "respectful-critique", "Give a respectful critique", "extension", "decision", "FINE ART · EXTENSION", "A learner wants to call a classmate’s artwork ‘bad’ without referring to visible work or stated purpose. What is the strongest response?", ["Describe a visible choice, connect it to the stated purpose, and offer a respectful question.", "Use an insult because it is quicker.", "Share a photo outside class without permission.", "Judge the artist rather than the work."], "Describe a visible choice, connect it to the stated purpose, and offer a respectful question.", "Constructive critique focuses on visible work and stated purpose while protecting the artist’s dignity."),

  topicUnit("technical-drawing-views-foundation", "uganda-high-school-technical-drawing", "views-and-labels", "Read a stated drawing view", "foundation", "evidence", "TECHNICAL DRAWING · FOUNDATION", "A classroom drawing is labelled ‘front view’ and shows a rectangle with a centred circle. Which statement is supported?", ["The front view shows a rectangular outline with a centred circular feature.", "The drawing proves the object’s exact depth.", "The drawing gives every material detail.", "A front view shows nothing."], "The front view shows a rectangular outline with a centred circular feature.", "A stated view supports description of what is shown while leaving missing details unresolved."),
  topicUnit("technical-drawing-communication-development", "uganda-high-school-technical-drawing", "communication-and-scale", "Plan clear drawing communication", "development", "reasoning", "TECHNICAL DRAWING · DEVELOPMENT", "A learner has drawn an outline but omitted the stated view and scale information. What is the strongest next step?", ["Add clear labels and note information that the classroom drawing does not yet provide.", "Ask every reader to guess missing details.", "Invent dimensions to fill the page.", "Treat the drawing as a construction instruction."], "Add clear labels and note information that the classroom drawing does not yet provide.", "Clear labels make a class drawing reviewable without inventing details or turning it into an instruction."),
  topicUnit("technical-drawing-review-extension", "uganda-high-school-technical-drawing", "peer-review", "Choose a peer-review question", "extension", "decision", "TECHNICAL DRAWING · EXTENSION", "A drawing now has a stated view and labels. Which review question is most useful?", ["Can a reviewer identify the view and see which information remains to be checked?", "Can a reviewer guess the learner’s private intention?", "Can the drawing be used without teacher review for construction?", "Can missing labels be ignored?"], "Can a reviewer identify the view and see which information remains to be checked?", "A useful review checks clear communication and acknowledges the limits of a classroom drawing."),

  topicUnit("food-nutrition-label-foundation", "uganda-high-school-food-nutrition", "food-information", "Read stated food information", "foundation", "evidence", "FOOD AND NUTRITION · FOUNDATION", "A classroom label exercise lists a serving amount and one ingredient. Which statement is most careful?", ["The label provides stated information about that product.", "The label proves one choice is best for every person.", "The label replaces professional guidance.", "The label contains no information."], "The label provides stated information about that product.", "A classroom label can be read carefully without becoming personal food or health guidance."),
  topicUnit("food-nutrition-claims-development", "uganda-high-school-food-nutrition", "claims-and-sources", "Check a food-information claim", "development", "reasoning", "FOOD AND NUTRITION · DEVELOPMENT", "A post says one ingredient will solve everyone’s study-energy problems but gives no source. What is the strongest next step?", ["Name the claim, note the missing source, and ask a teacher to help check relevant reliable information.", "Repeat the claim as a guarantee.", "Tell classmates to make personal changes immediately.", "Assume popularity is evidence."], "Name the claim, note the missing source, and ask a teacher to help check relevant reliable information.", "The study move is source checking, not a personal dietary decision or a medical recommendation."),
  topicUnit("food-nutrition-limits-extension", "uganda-high-school-food-nutrition", "evidence-limits", "State evidence limits", "extension", "decision", "FOOD AND NUTRITION · EXTENSION", "After checking a source, a learner wants to make a universal conclusion for classmates. What is the strongest response?", ["Describe what the source supports, what remains uncertain, and why personal questions belong with an appropriate adult or professional.", "Promise the same outcome for every learner.", "Ignore source limits.", "Turn a class activity into food-preparation guidance."], "Describe what the source supports, what remains uncertain, and why personal questions belong with an appropriate adult or professional.", "A responsible conclusion keeps source limits visible and leaves personal matters outside the learning activity."),

  topicUnit("music-listening-foundation", "uganda-high-school-music", "listening-patterns", "Describe a listening pattern", "foundation", "evidence", "MUSIC · FOUNDATION", "A classroom excerpt repeats a steady hand-clap pattern while a higher sound enters later. Which statement is most careful?", ["The excerpt has a repeated pattern and a later higher sound.", "Every listener must feel the same emotion.", "The excerpt proves the performer’s private intention.", "Patterns cannot be described in music."], "The excerpt has a repeated pattern and a later higher sound.", "Listening evidence can describe audible features without claiming identical feelings or intentions."),
  topicUnit("music-rehearsal-development", "uganda-high-school-music", "rehearsal-and-roles", "Plan a rehearsal adjustment", "development", "reasoning", "MUSIC · DEVELOPMENT", "A group loses a repeated pattern at one transition during rehearsal. What is the strongest next step?", ["Name the transition, agree on a short shared practice step, and keep roles inclusive.", "Exclude a learner after one attempt.", "Mock the group.", "Share a recording outside class."], "Name the transition, agree on a short shared practice step, and keep roles inclusive.", "A useful rehearsal adjustment focuses on an observable point and shared practice rather than judgement."),
  topicUnit("music-feedback-extension", "uganda-high-school-music", "respectful-feedback", "Choose respectful musical feedback", "extension", "decision", "MUSIC · EXTENSION", "A learner wants to give feedback after a group rehearsal. What is the strongest response?", ["Name one observable point, connect it to the group goal, and suggest a respectful next practice step.", "Use an insult so the feedback is memorable.", "Judge the learner instead of the rehearsal.", "Share another learner’s recording without permission."], "Name one observable point, connect it to the group goal, and suggest a respectful next practice step.", "Respectful feedback supports the next rehearsal without becoming professional assessment or unapproved sharing."),

  topicUnit("physical-education-observation-foundation", "uganda-high-school-physical-education", "participation-observations", "Read a participation observation", "foundation", "evidence", "PHYSICAL EDUCATION · FOUNDATION", "A teacher-supervised activity record notes that one learner paused twice. Which statement is most careful?", ["The record notes two pauses but does not explain why they happened.", "The pauses prove the learner is unwilling.", "Classmates should give personal activity instructions.", "The record predicts every future activity."], "The record notes two pauses but does not explain why they happened.", "An observation should not be turned into a personal judgement or activity instruction without teacher guidance."),
  topicUnit("physical-education-roles-development", "uganda-high-school-physical-education", "fair-participation", "Plan fair participation", "development", "reasoning", "PHYSICAL EDUCATION · DEVELOPMENT", "In a teacher-supervised activity, the same learners receive every turn. What is the strongest next step?", ["Pause, invite respectful role preferences, and use teacher guidance to share participation fairly.", "Keep the same roles because they are faster.", "Pressure a learner who pauses.", "Make assumptions about classmates."], "Pause, invite respectful role preferences, and use teacher guidance to share participation fairly.", "Fair participation uses dignity, choice, and teacher guidance rather than pressure or assumptions."),
  topicUnit("physical-education-reflection-extension", "uganda-high-school-physical-education", "guided-reflection", "Reflect on fair participation", "extension", "decision", "PHYSICAL EDUCATION · EXTENSION", "After a teacher-guided activity, which reflection is most useful?", ["Identify whether roles were shared fairly and what the group can discuss with the teacher next time.", "Decide which learner is naturally best.", "Tell classmates to follow an activity plan outside teacher guidance.", "Make a personal health judgement."], "Identify whether roles were shared fairly and what the group can discuss with the teacher next time.", "The reflection stays focused on fair participation and teacher-guided improvement, not performance or medical judgement."),
];

export const HIGH_SCHOOL_TOPIC_UNITS: readonly HighSchoolTopicUnit[] = CORE_TOPIC_UNITS.flatMap((unit) => [unit, reflectionCompanion(unit)]);

export function topicUnitsForPack(packId: string): HighSchoolTopicUnit[] {
  return HIGH_SCHOOL_TOPIC_UNITS.filter((unit) => unit.packId === packId);
}

export function topicUnitForId(unitId: string): HighSchoolTopicUnit | null {
  return HIGH_SCHOOL_TOPIC_UNITS.find((unit) => unit.id === unitId) ?? null;
}

export function learningBandForLevel(level: HighSchoolLevel): Exclude<HighSchoolTopicBand, "all_levels"> {
  if (level === "s1" || level === "s2") return "foundation";
  if (level === "s3" || level === "s4") return "development";
  return "extension";
}

export function isUnitRecommendedForLevel(unit: HighSchoolTopicUnit, level: HighSchoolLevel): boolean {
  return unit.band === "all_levels" || unit.band === learningBandForLevel(level);
}

export function topicUnitModesLabel(mode: HighSchoolTopicMode): string {
  return ({ evidence: "Read evidence", reasoning: "Reason it through", decision: "Choose a next step", reflection: "Reflect privately" })[mode];
}
