export type UniversityTopicMode = "focus" | "apply" | "reflection";
export type UniversityTopicUnit = {
  id: string;
  packId: string;
  topicId: string;
  pathway: "foundation" | "application" | "reflection";
  mode: UniversityTopicMode;
  title: string;
  cue: string;
  prompt: string;
  options?: string[];
  bestOption?: string;
  explanation: string;
  reflectionPrompt?: string;
  boundaryNote?: string;
};

type TopicSeed = {
  id: string;
  title: string;
  cue: string;
  focusPrompt: string;
  applyPrompt: string;
  options: [string, string, string, string];
  bestOption: string;
  explanation: string;
  boundaryNote?: string;
};

function unitsForSeed(packId: string, seed: TopicSeed): UniversityTopicUnit[] {
  const topicId = `${packId}:${seed.id}`;
  return [
    { id: `${topicId}:focus`, packId, topicId, pathway: "foundation", mode: "focus", title: seed.title, cue: seed.cue, prompt: seed.focusPrompt, options: seed.options, bestOption: seed.bestOption, explanation: seed.explanation, boundaryNote: seed.boundaryNote },
    { id: `${topicId}:apply`, packId, topicId, pathway: "application", mode: "apply", title: `Apply ${seed.title}`, cue: seed.cue, prompt: seed.applyPrompt, options: seed.options, bestOption: seed.bestOption, explanation: seed.explanation, boundaryNote: seed.boundaryNote },
    { id: `${topicId}:reflect`, packId, topicId, pathway: "reflection", mode: "reflection", title: `Reflect on ${seed.title}`, cue: seed.cue, prompt: `Use ${seed.cue.toLowerCase()} to explain one careful next step in your own words.`, reflectionPrompt: `Write a private note: what evidence, constraint, or question would you check before acting on this topic?`, explanation: `This private reflection is for your own learning. ${seed.explanation}`, boundaryNote: seed.boundaryNote },
  ];
}

const universityTopicSeeds: Record<string, TopicSeed[]> = {
  "university-foundation-year": [
    { id: "traceable-claim", title: "Traceable Academic Claim", cue: "claim, evidence, source", focusPrompt: "What makes a short academic claim easier for another reader to check?", applyPrompt: "Before submitting a paragraph with a source-based claim, which step is strongest?", options: ["State a cautious claim and record the evidence source clearly.", "Use confident wording without recording the source.", "Remove all evidence so the paragraph is shorter.", "Treat a first search result as proof without checking it."], bestOption: "State a cautious claim and record the evidence source clearly.", explanation: "A clear claim is stronger when its evidence and source can be traced, checked, and represented accurately." },
    { id: "quantitative-context", title: "Quantitative Context", cue: "numbers, denominator, context", focusPrompt: "What should a learner check before interpreting a percentage in a report?", applyPrompt: "A report says 40% responded to a survey. Which conclusion stays within the evidence?", options: ["Check what the denominator and response group represent before drawing a conclusion.", "Assume the percentage represents everyone in the institution.", "Ignore the number because percentages have no context.", "Choose the conclusion that sounds most impressive."], bestOption: "Check what the denominator and response group represent before drawing a conclusion.", explanation: "Numbers describe the particular data collected. The denominator, group, and method matter before a wider claim can be made." },
    { id: "research-question", title: "Research Question and Method", cue: "question, method, ethics", focusPrompt: "What is the most useful starting point when planning a small research activity?", applyPrompt: "Which plan keeps a research question connected to an appropriate first method?", options: ["State a focused question, identify needed evidence, and consider respectful participation.", "Collect every available detail before deciding what the question is.", "Choose a conclusion first and search only for support.", "Use personal details without explaining the purpose."], bestOption: "State a focused question, identify needed evidence, and consider respectful participation.", explanation: "A focused question guides appropriate evidence gathering and gives ethical choices a place in the plan." },
    { id: "digital-trust", title: "Digital Trust and Privacy", cue: "source, route, permission", focusPrompt: "What is a safe first response to an unexpected message requesting a sign-in?", applyPrompt: "Which choice respects another person’s digital information?", options: ["Use a known official route and check the stated purpose before sharing information.", "Follow the message link immediately because it sounds urgent.", "Share another person’s details with a group to get opinions.", "Reuse information for a new purpose without asking."], bestOption: "Use a known official route and check the stated purpose before sharing information.", explanation: "Known routes and clear purpose checks reduce reliance on unverified messages and support responsible information use." },
    { id: "study-cycle", title: "Deliberate Study Cycle", cue: "retrieve, check, revise", focusPrompt: "Which study routine gives useful evidence about what needs more attention?", applyPrompt: "After missing a practice item, what is the most constructive next step?", options: ["Retrieve from memory, check the result, and plan a focused revisit.", "Read the same notes repeatedly without checking recall.", "Hide the missed item so it does not affect confidence.", "Assume one attempt defines permanent ability."], bestOption: "Retrieve from memory, check the result, and plan a focused revisit.", explanation: "A deliberate cycle uses retrieval and feedback to decide what to revisit instead of treating mistakes as fixed labels." },
    { id: "professional-message", title: "Professional Communication", cue: "audience, purpose, clarity", focusPrompt: "What makes a short academic or professional message easier to act on?", applyPrompt: "Before sending a request to a group, which revision is most useful?", options: ["State the purpose, relevant context, requested action, and respectful closing clearly.", "Use vague wording so the reader must infer the action.", "Include unrelated personal details to make it longer.", "Send the message without considering the reader’s role."], bestOption: "State the purpose, relevant context, requested action, and respectful closing clearly.", explanation: "Clear communication helps readers understand the purpose and respond appropriately without unnecessary assumptions." },
  ],
  "computing-foundations": [
    { id: "user-requirements", title: "User Requirements", cue: "users, needs, success", focusPrompt: "What should a team clarify before choosing a tool for a new digital product?", applyPrompt: "Which first step keeps a product idea connected to the people who may use it?", options: ["Clarify users, needs, accessibility requirements, data source, and success criteria.", "Choose the team’s favourite technology before reading the brief.", "Assume all users have identical devices and access needs.", "Build the first screen before identifying what it must do."], bestOption: "Clarify users, needs, accessibility requirements, data source, and success criteria.", explanation: "A usable solution begins with a clear problem, users, constraints, and evidence of success." },
    { id: "logic-path", title: "Logic Path", cue: "condition, outcome, trace", focusPrompt: "What is the most reliable way to understand a simple conditional rule?", applyPrompt: "When a rule has a stated condition, what should be checked before predicting the result?", options: ["Follow the stated condition step by step and identify the matching outcome.", "Skip the condition and choose the most familiar result.", "Assume every input produces the same output.", "Change the rule while tracing it."], bestOption: "Follow the stated condition step by step and identify the matching outcome.", explanation: "Tracing a rule in order prevents assumptions from replacing the conditions actually stated." },
    { id: "data-purpose", title: "Data Purpose and Minimisation", cue: "purpose, minimum, permission", focusPrompt: "What is a responsible question before collecting information in a student project?", applyPrompt: "Which data choice is most appropriate for a small local prototype?", options: ["Collect only what is needed for the stated purpose and explain that purpose clearly.", "Collect every available detail in case it becomes useful later.", "Reuse data for unrelated purposes without notice.", "Publish raw entries to make the project look transparent."], bestOption: "Collect only what is needed for the stated purpose and explain that purpose clearly.", explanation: "Purpose and minimisation help a team avoid unnecessary collection and communicate clearly with participants." },
    { id: "accessible-interface", title: "Accessible Interface", cue: "keyboard, contrast, labels", focusPrompt: "Which feature belongs in an inclusive first version of a digital interface?", applyPrompt: "What should a team test before calling a simple interface complete?", options: ["Readable text, clear labels, keyboard use, and a task a user can complete.", "Only decorative graphics and the team’s preferred colour.", "A layout that requires precise tapping without alternatives.", "Whether the team can finish the page quickly."], bestOption: "Readable text, clear labels, keyboard use, and a task a user can complete.", explanation: "Accessibility needs are product requirements, not decoration added after the basic work is finished." },
    { id: "test-evidence", title: "Testing with Evidence", cue: "task, observation, revision", focusPrompt: "What makes a first product test informative?", applyPrompt: "After a learner struggles with a prototype task, which response is most useful?", options: ["Observe a clear task, record what happened, and revise the requirement or design from evidence.", "Assume the user used the product incorrectly without checking.", "Remove the difficult task from the test notes.", "Keep the same design because a first version should not change."], bestOption: "Observe a clear task, record what happened, and revise the requirement or design from evidence.", explanation: "Testing produces useful learning when a team observes real task use and turns the evidence into a careful revision." },
    { id: "digital-explanation", title: "Technical Explanation", cue: "input, process, outcome", focusPrompt: "How can a learner explain a simple system without using vague technical language?", applyPrompt: "Which explanation gives another learner a useful way to check a digital process?", options: ["Describe the input, stated process, outcome, and one limit or assumption.", "Use complex words without naming what the system does.", "Describe only the final screen and omit the process.", "Claim that every system works the same way."], bestOption: "Describe the input, stated process, outcome, and one limit or assumption.", explanation: "A clear technical explanation identifies what enters a system, what happens, what results, and what remains uncertain." },
  ],
  "business-foundations": [
    { id: "customer-evidence", title: "Customer Evidence", cue: "observation, sample, question", focusPrompt: "What can a few customer conversations support at an early stage?", applyPrompt: "Which response treats a small observation responsibly when planning an idea?", options: ["A question worth investigating with a broader, careful sample.", "Proof that every customer will buy immediately.", "A final price for an entire market.", "A reason to ignore all other evidence."], bestOption: "A question worth investigating with a broader, careful sample.", explanation: "Early observations can reveal a possible need, but they do not prove demand, price, or a universal conclusion." },
    { id: "value-and-cost", title: "Value and Cost", cue: "value, cost, assumption", focusPrompt: "What should a simple project cost calculation make explicit?", applyPrompt: "Before using a break-even example to make a decision, what should a learner check?", options: ["The stated costs, contribution, assumptions, and limits of the example.", "Only the largest number in the calculation.", "A guarantee that the result predicts real business performance.", "Personal financial details from unrelated people."], bestOption: "The stated costs, contribution, assumptions, and limits of the example.", explanation: "A simplified calculation supports learning when its assumptions are visible; it is not financial, investment, or business advice." },
    { id: "small-experiment", title: "Small Learning Experiment", cue: "hypothesis, observation, revision", focusPrompt: "What makes an early project experiment useful?", applyPrompt: "A learner receives mixed feedback about an idea. What is a responsible next step?", options: ["State what was tested, record the feedback, and refine the next question.", "Treat one positive comment as final proof.", "Change the feedback so it matches the original idea.", "Promise a result before any observation."], bestOption: "State what was tested, record the feedback, and refine the next question.", explanation: "A small experiment is for learning from evidence, not for proving a conclusion before the evidence exists." },
    { id: "responsible-contact", title: "Responsible Contact Use", cue: "purpose, consent, respect", focusPrompt: "What should a team check before using contact details for a new message?", applyPrompt: "Which choice respects the people behind a project’s contact list?", options: ["Check the original purpose and seek clear permission for a new use.", "Send any message because the details were collected once.", "Share the list publicly to make promotion easier.", "Assume silence means permission."], bestOption: "Check the original purpose and seek clear permission for a new use.", explanation: "Using contact information consistently with the stated purpose and permission supports respectful project communication." },
    { id: "tradeoff-decision", title: "Trade-off Decision", cue: "criteria, evidence, trade-off", focusPrompt: "How can a learner compare two project options without relying on a single preference?", applyPrompt: "Which comparison is most useful before selecting between two simple options?", options: ["Compare both options against stated criteria and evidence, then note the trade-off.", "Choose the option with the most attractive name.", "Ignore the constraints because both ideas are interesting.", "Assume the cheaper option is always the right option."], bestOption: "Compare both options against stated criteria and evidence, then note the trade-off.", explanation: "Transparent criteria make a choice easier to explain and revise when new evidence appears." },
    { id: "clear-offer", title: "Clear Offer Communication", cue: "audience, claim, evidence", focusPrompt: "What makes a short description of a learner project more trustworthy?", applyPrompt: "Before sharing an offer, which revision best avoids an unsupported promise?", options: ["Describe the intended value, intended audience, and evidence still needed honestly.", "Promise a result for every customer without evidence.", "Hide all limits so the message sounds stronger.", "Use another project’s claim as if it were original."], bestOption: "Describe the intended value, intended audience, and evidence still needed honestly.", explanation: "Clear project communication distinguishes an intended value from a claim already supported by evidence." },
  ],
  "engineering-foundations": [
    { id: "design-constraints", title: "Design Constraints", cue: "goal, limits, evidence", focusPrompt: "What should be identified before selecting a design response?", applyPrompt: "Which step keeps a simple design proposal accountable to its context?", options: ["State the goal, constraints, user needs, and evidence still required.", "Choose a preferred design before reading the limits.", "Treat a visual preference as the only requirement.", "Claim that a proposal is safe without review."], bestOption: "State the goal, constraints, user needs, and evidence still required.", explanation: "Engineering learning begins with a clear problem and constraints; this is not engineering approval or safety instruction.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
    { id: "measurement-evidence", title: "Measurement Evidence", cue: "record, unit, comparison", focusPrompt: "What makes a recorded measurement useful in a design discussion?", applyPrompt: "Before comparing two recorded values, what should a learner confirm?", options: ["The unit, method, conditions, and what each value represents.", "Only which value appears larger.", "That an estimate can replace every measurement.", "That one value proves a design will work everywhere."], bestOption: "The unit, method, conditions, and what each value represents.", explanation: "Measurements are most useful when their units, method, and context are visible for careful comparison.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
    { id: "design-tradeoff", title: "Design Trade-off", cue: "criteria, access, maintenance", focusPrompt: "How should a learner compare two design ideas that both meet one stated limit?", applyPrompt: "Which next step is most responsible before selecting a layout?", options: ["Compare access, maintenance, cost, and user evidence against the stated criteria.", "Select the first idea because it was proposed first.", "Build both permanently before asking questions.", "Ignore user access because it is difficult to measure."], bestOption: "Compare access, maintenance, cost, and user evidence against the stated criteria.", explanation: "A careful choice considers multiple stated constraints and evidence instead of a single preference.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
    { id: "iteration", title: "Design Iteration", cue: "test, observe, revise", focusPrompt: "What is the purpose of an early design iteration?", applyPrompt: "After evidence challenges a first idea, what should happen next?", options: ["Record the evidence and revise the idea or question transparently.", "Hide the result so the first idea remains unchanged.", "Assume a prototype proves a final design is ready.", "Remove the constraint from the brief."], bestOption: "Record the evidence and revise the idea or question transparently.", explanation: "Iteration is a way to learn from evidence, not a failure to defend the first idea.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
    { id: "technical-communication", title: "Technical Communication", cue: "view, label, assumption", focusPrompt: "What helps another reader interpret a simple technical sketch or description?", applyPrompt: "Which addition makes a design note more checkable?", options: ["Clear labels, stated scale or assumptions, and the purpose of the view.", "Unlabelled details that the original author can remember.", "A claim that every reader will interpret the sketch the same way.", "A decorative title without a description."], bestOption: "Clear labels, stated scale or assumptions, and the purpose of the view.", explanation: "Clear technical communication identifies what is shown and the assumptions that shape the interpretation.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
    { id: "stakeholder-check", title: "Stakeholder Check", cue: "user, maintainer, approval", focusPrompt: "Who may provide relevant evidence before a shared-space design is chosen?", applyPrompt: "Which step respects the people affected by a simple design proposal?", options: ["Seek relevant user, maintenance, and local approval perspectives before selection.", "Assume the design team speaks for everyone.", "Exclude users because their needs are subjective.", "Proceed without checking whether the space can be changed."], bestOption: "Seek relevant user, maintenance, and local approval perspectives before selection.", explanation: "Relevant perspectives can reveal requirements and limits that are not visible in an early proposal.", boundaryNote: "For learning only; do not use this topic as engineering or safety approval." },
  ],
  "natural-sciences-foundations": [
    { id: "observation-explanation", title: "Observation and Explanation", cue: "observe, compare, explain", focusPrompt: "What is the difference between a recorded observation and an explanation?", applyPrompt: "After noticing a pattern in a classroom investigation, what should happen before claiming a cause?", options: ["Record relevant conditions and compare evidence before choosing an explanation.", "Treat the first pattern as proof of one cause.", "Delete unexpected observations.", "Choose the explanation that feels most familiar."], bestOption: "Record relevant conditions and compare evidence before choosing an explanation.", explanation: "An observation can raise a useful question, but relevant evidence is needed before selecting a causal explanation." },
    { id: "variable-control", title: "Variables and Comparison", cue: "change, compare, record", focusPrompt: "What supports a fair comparison in a simple classroom investigation?", applyPrompt: "Which plan makes it easier to interpret a difference between two observations?", options: ["State what changes, what is compared, and what conditions are recorded.", "Change several conditions without noting them.", "Use only a preferred result from the comparison.", "Assume every difference has one obvious cause."], bestOption: "State what changes, what is compared, and what conditions are recorded.", explanation: "Clear comparison conditions help a learner distinguish what was observed from what still needs explanation." },
    { id: "measurement-pattern", title: "Measurement Pattern", cue: "unit, repeat, pattern", focusPrompt: "What is a careful way to treat a surprising recorded value?", applyPrompt: "Before describing a pattern from several measurements, what should a learner check?", options: ["Check units and recording, repeat the observation where appropriate, and keep the record transparent.", "Remove a value because it does not match expectation.", "Assume one number speaks for every situation.", "Change the unit after calculating to make the pattern look clearer."], bestOption: "Check units and recording, repeat the observation where appropriate, and keep the record transparent.", explanation: "Transparent records and careful repetition help identify whether a pattern is supported by the observations." },
    { id: "model-limit", title: "Model and Limit", cue: "model, assumption, limit", focusPrompt: "What should an introductory scientific model make clear?", applyPrompt: "Which explanation uses a model responsibly?", options: ["What the model helps describe and what assumption or limit remains.", "That the model is identical to every real situation.", "That no evidence is needed once a model is named.", "That a simple diagram settles every question."], bestOption: "What the model helps describe and what assumption or limit remains.", explanation: "Models support explanation by simplifying; naming their scope and limits keeps the explanation honest." },
    { id: "evidence-replication", title: "Evidence and Replication", cue: "method, repeat, record", focusPrompt: "Why can repeating a stated method be valuable in a learning investigation?", applyPrompt: "Which response is most useful after an unexpected but carefully recorded result?", options: ["Repeat or compare the stated method while preserving a clear record of what happened.", "Hide the result to keep the report tidy.", "Claim the result proves a new theory immediately.", "Change the method without noting the change."], bestOption: "Repeat or compare the stated method while preserving a clear record of what happened.", explanation: "Repeated and transparent observations help learners decide what evidence is stable enough to interpret." },
    { id: "science-communication", title: "Scientific Communication", cue: "claim, evidence, uncertainty", focusPrompt: "What makes a short science explanation more careful?", applyPrompt: "Before sharing an investigation conclusion, which revision is strongest?", options: ["Separate the observation, supported claim, evidence, and remaining uncertainty.", "Present a guess as though it were a measured result.", "Omit the method so the conclusion appears simpler.", "State that uncertainty means no learning occurred."], bestOption: "Separate the observation, supported claim, evidence, and remaining uncertainty.", explanation: "Careful scientific communication shows what was observed, what follows from evidence, and what remains open." },
  ],
  "education-foundations": [
    { id: "observable-objective", title: "Observable Learning Objective", cue: "learner action, evidence, goal", focusPrompt: "What makes a learning objective observable?", applyPrompt: "Which revision turns a broad lesson aim into evidence a learner can show?", options: ["Name an action a learner can demonstrate and the evidence connected to it.", "Use only the word understand without a way to show it.", "Describe what the tutor will say instead of learner learning.", "Set a goal that cannot be checked in any form."], bestOption: "Name an action a learner can demonstrate and the evidence connected to it.", explanation: "An observable objective connects a learner action to evidence that can be reviewed thoughtfully." },
    { id: "inclusive-access", title: "Inclusive Access", cue: "same goal, fair route, support", focusPrompt: "How can a learning activity remain connected to one objective while supporting different learners?", applyPrompt: "Which choice keeps an inclusive adjustment aligned with the intended learning?", options: ["Offer an appropriate route or response format using the same relevant success criteria.", "Lower the objective without checking what support is needed.", "Require one format because differences are inconvenient.", "Assume access needs are unrelated to learning design."], bestOption: "Offer an appropriate route or response format using the same relevant success criteria.", explanation: "Different ways to access or show learning can be fair when they remain connected to the same intended evidence." },
    { id: "check-understanding", title: "Check for Understanding", cue: "prompt, learner evidence, next step", focusPrompt: "What should a quick learning check reveal?", applyPrompt: "After a learner gives an incomplete response, what is a constructive next step?", options: ["Use the learner’s evidence to choose a focused prompt, example, or revisit.", "Treat one incomplete response as a permanent label.", "Move on without looking at the response.", "Grade speed rather than the relevant evidence."], bestOption: "Use the learner’s evidence to choose a focused prompt, example, or revisit.", explanation: "A learning check is useful when it guides a respectful next teaching or study step." },
    { id: "feedback-cycle", title: "Feedback Cycle", cue: "specific, usable, revisit", focusPrompt: "What makes feedback useful for learning?", applyPrompt: "Which feedback response gives a learner a practical next step?", options: ["Name the relevant evidence, explain the gap, and suggest a focused revisit.", "Say only that the work is good or bad.", "Compare the learner publicly with others.", "Give a new task without explaining the connection."], bestOption: "Name the relevant evidence, explain the gap, and suggest a focused revisit.", explanation: "Specific feedback supports a learner when it makes the next action clear without reducing progress to a label." },
    { id: "lesson-sequence", title: "Learning Sequence", cue: "prior knowledge, practice, check", focusPrompt: "What supports a coherent short learning sequence?", applyPrompt: "Before introducing a new task, which planning question is most useful?", options: ["What learners already need, what guided practice will help, and what evidence will check the objective.", "How many slides can be shown without learner practice.", "Whether every learner will already know the topic.", "How to make the task difficult before explaining its purpose."], bestOption: "What learners already need, what guided practice will help, and what evidence will check the objective.", explanation: "A coherent sequence connects prior knowledge, guided work, independent effort, and a relevant check." },
    { id: "reflective-planning", title: "Reflective Planning", cue: "notice, evidence, revise", focusPrompt: "What is a useful focus for a private teaching reflection?", applyPrompt: "After a lesson activity does not produce the expected evidence, what should a planner do?", options: ["Notice the evidence, identify a possible revision, and plan what to check next time.", "Assume learners were the problem without looking at the activity.", "Discard all notes so the next plan starts from memory.", "Keep the same approach without considering the evidence."], bestOption: "Notice the evidence, identify a possible revision, and plan what to check next time.", explanation: "Reflective planning turns observed learning evidence into a modest, testable next improvement." },
  ],
  "social-sciences-foundations": [
    { id: "claim-evidence", title: "Claim and Evidence", cue: "claim, observation, support", focusPrompt: "What should a learner distinguish when reading a social claim?", applyPrompt: "Which response uses a small set of personal accounts responsibly?", options: ["The accounts are perspectives that can inform a broader question, not proof about everyone.", "The accounts prove every person shares the same experience.", "Personal accounts never matter in research.", "The authors should be identified publicly to make the claim stronger."], bestOption: "The accounts are perspectives that can inform a broader question, not proof about everyone.", explanation: "Respectful social inquiry values perspectives while avoiding overgeneralisation and protecting privacy." },
    { id: "sample-context", title: "Sample and Context", cue: "group, context, limit", focusPrompt: "What should be checked before extending a small survey finding to a wider group?", applyPrompt: "Which description keeps a response percentage in context?", options: ["Who responded, how they were invited, what the question asked, and the limits of the group.", "Only whether the percentage is high or low.", "That a small group automatically represents every learner.", "That no context is needed when a number is shown."], bestOption: "Who responded, how they were invited, what the question asked, and the limits of the group.", explanation: "Sample and context determine what a response count can and cannot support." },
    { id: "question-design", title: "Respectful Question Design", cue: "purpose, wording, consent", focusPrompt: "What makes a small interview or survey question more responsible?", applyPrompt: "Before asking about a learner’s experience, which preparation is most important?", options: ["Explain the purpose, use clear non-leading wording, and respect voluntary participation.", "Use a question that assumes the answer you want.", "Collect names when they are not needed.", "Share responses with others before explaining the activity."], bestOption: "Explain the purpose, use clear non-leading wording, and respect voluntary participation.", explanation: "Respectful wording and clear purpose help participants decide whether and how to contribute." },
    { id: "interpretation", title: "Interpretation and Alternative View", cue: "evidence, context, alternative", focusPrompt: "What is a careful way to interpret a social pattern?", applyPrompt: "Which revision makes an interpretation more open to evidence?", options: ["State the evidence, context, and a plausible alternative explanation to consider.", "Present one interpretation as certain without context.", "Ignore evidence that does not match the first idea.", "Describe a group with a fixed stereotype."], bestOption: "State the evidence, context, and a plausible alternative explanation to consider.", explanation: "Careful interpretation avoids stereotypes and keeps room for context and alternative explanations." },
    { id: "time-and-source", title: "Time and Source", cue: "source, sequence, corroborate", focusPrompt: "What can a source tell a learner about a historical or social event?", applyPrompt: "Before relying on one source for a conclusion, what should a learner consider?", options: ["What the source states, its context, and what other evidence could corroborate or complicate it.", "That one source settles every question.", "That later information should be ignored automatically.", "That a source has no perspective or limit."], bestOption: "What the source states, its context, and what other evidence could corroborate or complicate it.", explanation: "Sources can be meaningful evidence while still reflecting context, perspective, and limits." },
    { id: "respectful-dialogue", title: "Respectful Dialogue", cue: "reason, listening, response", focusPrompt: "What helps a group discuss a difficult social question respectfully?", applyPrompt: "Which next response keeps disagreement connected to reasons and evidence?", options: ["Represent the other view fairly, state your reason, and invite evidence-aware discussion.", "Attack the person instead of addressing the idea.", "Repeat a claim more loudly without reasons.", "Exclude anyone who disagrees."], bestOption: "Represent the other view fairly, state your reason, and invite evidence-aware discussion.", explanation: "Respectful dialogue makes room for reasoned disagreement without turning difference into personal attack." },
  ],
};

export const UNIVERSITY_TOPIC_UNITS: UniversityTopicUnit[] = Object.entries(universityTopicSeeds).flatMap(([packId, seeds]) => seeds.flatMap((seed) => unitsForSeed(packId, seed)));

export function universityTopicUnitsForPack(packId: string): UniversityTopicUnit[] {
  return UNIVERSITY_TOPIC_UNITS.filter((unit) => unit.packId === packId);
}

export function universityTopicUnitForId(unitId: string): UniversityTopicUnit | null {
  return UNIVERSITY_TOPIC_UNITS.find((unit) => unit.id === unitId) ?? null;
}

export function universityTopicModeLabel(mode: UniversityTopicMode): string {
  return ({ focus: "FOCUS", apply: "APPLY", reflection: "PRIVATE REFLECTION" })[mode];
}
